### ISSUE TITLE
bazel stuck in busy loop during analysis phase with pure = "on"

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#1023]
I updated kubernetes/kubernetes to 6d900bc95ae678bec5c91031b8e987957d2a7f93 and tried changing one of our go_binary rules to use `pure = "on"`, instead of the somewhat hacky (and invalid) static linking trick we've been using.

Mysteriously, trying to build this go binary causes bazel to get stuck in a busy loop:
```console
$ bazel build //cmd/kubectl
Analyzing: target //cmd/kubectl:kubectl (543 packages loaded)
```
(Top shows 200% CPU usage.)

To repro, you can clone https://github.com/ixdy/kubernetes/tree/pure-go-binaries.

I recently tried using `pure = "on"` in kubernetes/test-infra, and everything works as expected there.
I'm guessing we're doing something special or weird in k/k, but I'm not yet sure what.

**Comment by ixdy** [comment]
I've tested with both bazel 0.7.0 and 0.8.0rc2; same issue on both.

**Comment by ianthehat** [comment]
I have reproduced the issue, no idea what is causing it yet though.
Building without pure works.
Building with --features=pure almost works (the build proceeds correctly and gets to the point where it fails at link time because pure and cgo don't mix well right now)
Building with pure="on" locks up and ratchets the cpu usage to max.

**Comment by ianthehat** [comment]
It's not actually doing anything wrong, it's still making progress, it's just doing it very very slowly.
It seems like the aspect propagation gets pathologically slower the more dependancies it has already propagated across. I can see it still making progress nearly 30 minutes after it started.

It's clearly not viable as a build, but I think the problem is in Bazels aspect mechanism.
This means we either fix Bazel and wait for a new version with the fix, or we change away from the aspect based build (for now at least)

**Comment by jayconrod** [comment]
@ianthehat Do you think this is related to the performance regression in #1013?

**Comment by ianthehat** [comment]
It could easily be, it's clearly an exponential increase in aspect propagation cost, and it seems to be varied with the number of times a node is visited by an aspect, rather than depth or size of dependency graph. The leaf nodes of kubernetes are depended on through many many paths from the root, but much simpler graphs would just be slow rather than look like they were stuck.

There is almost no cost on really simple graphs, which is why we have not observed it on any of the test cases.

I have been working most of the night on rules that do not use an aspect, they are more limited in the set of modes they will accept, but they should work.

I will be sending a PR in the next hour or so I hope.

**Comment by jayconrod** [comment]
I got a [stack dump](https://gist.github.com/jayconrod/34f233c4babdd6f281d46390eed67d3f). This is after the build was running for about an hour with Bazel 0.8rc2.

I'm not familiar with Bazel internals, but it looks like only one of the threads is busy, and it's getting stuck combining two data structures with `+=` in Skylark. I'm guessing the left operand is a depset.

I spoke with @ianthehat earlier. It sounds like the non-aspect version of the rules he was working on also suffer this problem. So this is issue is probably not caused by aspects.

cc @katre

**Comment by ixdy** [comment]
This issue seems to have returned with #1029. :(

**Comment by jayconrod** [comment]
@ianthehat, it looks like #1033 will fix this. I'll re-open this issue until we can verify it's fixed though.
