### ISSUE TITLE
gazelle in vendored mode doesn't like grpc

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/rules_go#1024]
gazelle currently doesn't like if you depend on grpc *and* try to use `external = vendor` mode.

To make a gRPC server work in rules_go work, we need to use the `@org_golang_google_grpc` and `@org_golang_x_net` dependencies rather than vendoring them.

If one tries to vendor those packages, code linking fails because bazel already compiled grpc libraries for the go rpc rules. Example, for reference:

<pre>
server/main.go:11:2: method redeclared: grpc.addrConn.grpc.resetTransport
	method(*grpc.addrConn) func() error
	method(*grpc.addrConn) func(bool) error
server/main.go:11:2: inconsistent definition for type grpc.ClientConn during import
	struct { grpc.ctx context.Context; grpc.cancel context.CancelFunc; grpc.target string; grpc.authority string; grpc.dopts grpc.dialOptions; grpc.csMgr *grpc.connectivityStateManager; grpc.balancerWrapper *grpc.ccBalancerWrapper; grpc.resolverWrapper *grpc.ccResolverWrapper; grpc.blockingpicker *grpc.pickerWrapper; grpc.mu sync.RWMutex; grpc.sc grpc.ServiceConfig; grpc.conns map[*grpc.addrConn]struct {}; grpc.mkp keepalive.ClientParameters } (in "google.golang.org/grpc")
	struct { grpc.ctx context.Context; grpc.cancel context.CancelFunc; grpc.target string; grpc.authority string; grpc.dopts grpc.dialOptions; grpc.csMgr *grpc.connectivityStateManager; grpc.csEvltr *grpc.connectivityStateEvaluator; grpc.mu sync.RWMutex; grpc.sc grpc.ServiceConfig; grpc.conns map[grpc.Address]*grpc.addrConn; grpc.mkp keepalive.ClientParameters } (in "github.com/nictuku/zurigo/proto")
</pre>

Full errors here: http://termbin.com/3vw3

The solution is to use remote repositories for those sources. For example:
<pre>
go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/nictuku/zurigo/server",
    visibility = ["//visibility:private"],
    deps = [
        "//proto:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_x_net//context:go_default_library",
    ],
)
</pre>

 This works. But unfortunately every execution of gazelle will replace those remote repos with a vendored version. The only solution I could find was to not use vendoring, but stick to importing remote repositories. Remote repos are polyglot-friendly, but they are currently a lot more tedious to maintain than using the Go `dep` tool, I think. Is there a better way? Thanks

**Comment by jayconrod** [comment]
So the key issue here is that both external and vendored versions of the same libraries are getting pulled in. You can either force the rules to use the vendored versions, or force Gazelle to preserve the external versions for specific rules.

Using external versions is the simplest solution. Just write in the external deps, then add a `# keep` comment above to prevent Gazelle from modifying the attribute.

```
go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/nictuku/zurigo/server",
    visibility = ["//visibility:private"],
    # keep
    deps = [
        "//proto:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_x_net//context:go_default_library",
    ],
)
```

Alternatively, you could define a `go_proto_toolchain` that adds dependencies on vendored targets instead of external targets. Our default toolchain is `//proto:go_grpc_impl`. So you could copy that and change the deps. You'll probably want to do the same for `//proto:go_proto_impl`. Make sure to register the toolchain by copying and modifying `proto_register_toolchains`.

```
go_proto_toolchain(
    name = "go_grpc_impl_vendored",
    deps = [
        "//vendor/github.com/golang/protobuf/proto:go_default_library",
        "//vendor/google.golang.org/grpc:go_default_library",
        "//vendor/golang.org/x/net:go_default_library",
    ],
    options = ["plugins=grpc"],
    visibility = ["//visibility:public"],
)
```

Gazelle has some special casing for well known types that may not work in the vendored case, so you might end up manually modifying build files for these libraries.

**Comment by nictuku** [comment]
Thank you!
