### ISSUE TITLE
cgo build failing to find .h file

### ISSUE THREAD

**Issue by dbenamydd** [bazelbuild/rules_go#1052]
Hi there! I'm a new bazel user trying to build a small cgo project:

`go get -u github.com/jmoiron/golz4`

`cd $GOPATH/src/github.com/jmoiron/golz4`

Set WORKSPACE to
```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.7.0/rules_go-0.7.0.tar.gz",
    sha256 = "91fca9cf860a1476abdc185a5f675b641b60d3acf0596679a27b580af60bf19c",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains(go_version="1.9")
```

Set BUILD to
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
        "lz4.go",
        "lz4_hc.go",
        "src/lz4.h",
        "src/lz4.c",
        "src/lz4hc.h",
        "src/lz4hc.c",
    ],
    cgo = True,
    copts = [
        "-O3",
    ],
    importpath = "github.com/jmoiron/golz4",
    visibility = ["//visibility:public"],
)
```

`bazel build //:all`

```
...
ERROR: /home/vagrant/go/src/github.com/jmoiron/golz4/BUILD:3:1: C++ compilation of rule '//:go_default_library.cgo_c_lib' failed (Exit 1)
bazel-out/local-fastbuild/bin/go_default_library.cgo.dir/src_lz4hc.cgo1.c:46:19: fatal error: lz4hc.h: No such file or directory
 #include "lz4hc.h"
                   ^
```

I've tried a few permutations of changing how the files are included, passing include paths as copts, and can't get this to work. Am I doing something wrong or is this a bug?

Thanks so much!

Edit (2017-11-23) removed a junk `echo` from WORKSPACE shown here

**Comment by jayconrod** [comment]
Sorry for the slow response on this.

This has to do with the way Bazel handles cc_library rules. In general, includes are expected to be relative to the repository root. In cgo, we add the package directory as an additional include directory, but you'll need to add more directories when your sources spread out in multiple directories.

I looked into this package a bit closer because I was surprised that "go build" compiled it without error. lz4.go actually includes the full text of src/lz4.h and src/lz4.c, and lz4_hc.go does something similar. Including the .c files in the build will cause problems with duplicate symbols, but you need the files to be visible when cgo rules for the include to happen at all.

This is a really odd structure. Is this a library you have control over? If so, avoid including files like this. Build a separate cc_library that can be given as a dependency through `cdeps`. Alternatively, put all the sources in the same directory and put them in `srcs`.

**Comment by dbenamydd** [comment]
No worries, thanks for looking into it!

This all makes sense. I don't have direct control over it but I can figure out how to make this work for my use case from here, so I'll close this.

Thanks again for the help!!
