### ISSUE TITLE
Create tool to convert vendor.json to go_repository rules

### ISSUE THREAD

**Issue by tiziano88** [bazelbuild/rules_go#1082]
As a matter of fact I have just written such tool, is there any interest in adding it to the tools directory of this repo? I'd imagine it might be useful for other people.

**Comment by jayconrod** [comment]
I'm planning to add something like this to Gazelle, but some things need to be decided first. We're considering deprecating `go_repository` (#460) in favor of flat build files generated ahead of time by Gazelle. We need to make a final decision on whether and how to do that before adding this functionality to Gazelle, since we shouldn't add a bunch of rules to WORKSPACE that will immediately be deprecated.

**Comment by jayconrod** [comment]
Migrated to bazelbuild/bazel-gazelle#29
