### ISSUE TITLE
Please run buildifier against BUILD/bzl files

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_go#1093]
Shall we add a pre-merge hook to run `buildifier` in check mode, to make sure the code style is consistent?

For instance, in `proto/BUILD.bazel`, there are mixed usage of single and double quotes:

```
-load('//proto:toolchain.bzl', 'proto_toolchain', 'go_proto_toolchain')
+load("//proto:toolchain.bzl", "proto_toolchain", "go_proto_toolchain")
```

And, attributes are not sorted:

```
 toolchain(
     name = "go_proto",
-    toolchain_type = "@io_bazel_rules_go//proto:go_proto",
     exec_compatible_with = [],
     target_compatible_with = [],
     toolchain = "go_proto_impl",
+    toolchain_type = "@io_bazel_rules_go//proto:go_proto",
 )
````

**Comment by jayconrod** [comment]
Ideally, we would have a Bazel test that checks whether buildifier needs to be run. Our CI could run the test along with everything else. The buildtools repo ought to provide that. We would need to create a filegroup of build files to check, which would require bubbling them up through all build files, since glob doesn't cross package boundaries.

I don't really have time to set that up today, so I just ran buildifier and added this to my .git/hooks/pre-commit script (in case anyone else wants to use it):

```
buildifier_output=$(buildifier -mode=check $(find . -name BUILD.bazel))
if [ -n "$buildifier_output" ]; then
  echo "error: buildifier needs to be run" >&1
  exit 1
fi
```
