### ISSUE TITLE
Check minimum Bazel version

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1108]
We should check that the version of Bazel being used is at least the minimum supported version. Currently, error messages can be confusing when an earlier, unsupported version is used.

Parsing the version is non-trivial. Kubernetes does this at https://github.com/kubernetes/repo-infra/blob/master/defs/bazel_version.bzl (originally copied from TensorFlow). We should probably copy their implementation.

**Comment by BenTheElder** [comment]
We're also using this implementation [in kubernetes/test-infra](https://github.com/kubernetes/test-infra/pull/5234), it's been pretty nice, though I think we're a bit overly pessimistic about the minimum version. We probably wouldn't need to do this anymore if `rules_go` maintained a more definitive check. :+1:

**Comment by ixdy** [comment]
There's also a more different "definitive" version in https://github.com/bazelbuild/bazel-integration-testing/blob/master/bazel_version.bzl. 

I wonder if we should try to get this bit of skylark added into bazelbuild/bazel, [since it's pretty widely reused](https://github.com/search?q=_parse_bazel_version&type=Code&utf8=%E2%9C%93)...
