### ISSUE TITLE
Gazelle does not respect proto visibility.

### ISSUE THREAD

**Issue by nclinger** [bazelbuild/rules_go#1119]
Gazelle auto generates visibility public for all proto files, however, often you want to restrict visibility for proto files that are internal to a project and not part of its external facing API.

**Comment by jayconrod** [comment]
You can change the `visibility` attribute on the generated rules to something more restricted. Gazelle should not modify `visibility` attributes of existing rules. If you have `package(default_visibility = ...)`, Gazelle won't add `visibility` attributes to rules that don't have them. You can change attributes in bulk with [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer).

Any ideas on how this should work differently? I'd rather not add more configuration, since I think configuring `visibility` attributes directly works well.

**Comment by nclinger** [comment]
So I have a hello world example am playing with, that has an initial build file:

`
package(
    default_visibility = [
        "//go/src/builds/examples:__pkg__",
    ],
)
`

After running gazelle the build file is:
`
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_grpc_library")

package(
    default_visibility = [
        "//go/src/builds/examples:__pkg__",
    ],
)

proto_library(
    name = "helloworld_proto",
    srcs = ["helloworld.proto"],
    visibility = ["//visibility:public"],
)

go_grpc_library(
    name = "helloworld_go_proto",
    importpath = "metacloud/builds/examples/protobuf",
    proto = ":helloworld_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    importpath = "metacloud/builds/examples/protobuf",
    library = ":helloworld_go_proto",
)
`

Doesn't look like Gazelle is respective the existing package visibility?

As to ideas for, I reckon that as long as Gazelle respects #keep then that is actually fine.  You can add your own visibility and tell Gazelle to not override it right?

**Comment by jayconrod** [comment]
That's actually a bug. Sorry about that. Gazelle should not emit `visibility` attributes for any rule it generates when `default_visibility` is set in that file. #1126 will fix this.

Just to confirm, Gazelle won't *change* `visibility` attributes on rules that already have them set (manually or otherwise). You don't need a `# keep` comment for that. Gazelle won't *add* `visibility` to existing rules or generate new rules with `visibility` if `default_visibility` is set (after this fix lands).

**Comment by nclinger** [comment]
What if I want to have a default visibility X but for some things make them
have a visibility Y? Can I add the visibility to the generated build rules
and add # keep to prevent it from being changed?

**Comment by jayconrod** [comment]
Gazelle won't change visibility for rules in generated files. Gazelle will only set the visibility attribute if it's missing *and* there's no default visibility in that file. You don't need a `# keep` comment in that case.
