### ISSUE TITLE
Upgrading from rules_go 0.7.1 to 0.8.1 breaks tests because of missing dependencies.

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/rules_go#1142]
# Context
## Versions
While trying to upgrade our `rules_go` version to the latest `0.8.1` release from ~`0.7.0` (SHA `473ed9` to be exact which is between `0.7.0` and `0.7.1`) two of our tests started to fail. Upgrading to `rules_go 0.8.0` also breaks the tests in question. Only upgrading our Bazel version to `0.8.1` without the `rules_go` upgrade does not break the tests.

## Platforms
Reproduced on both Linux and OSX.
Go 1.8.3, 1.8.4 & 1.8.5.

# Symptoms
The breaking `go_test` targets both exhibit the particularity that they rely on a `data` dependency on a `go_binary` rule (these two tests appear to be the only examples of this pattern in our codebase).
- The `go_test` rule has the label `//go/src/foo:go_default_test` with:
```
  data = ["//go/src/foo/bar"],
```
- The `go_binary` rule with label `//go/src/foo/bar:bar"` is well-defined.
- The `go_test` with rule `//go/src/foo:go_default_test` runs the binary via:
```
exec.Command("bar/bar", ...)
```

With `rules_go` on `0.8.0` and `0.8.1` you then get:
```
fork/exec bar/bar: no such file or directory
```
whereas before it ran without issues.

**Comment by ianthehat** [comment]
The problem is the test is assuming the name of the binary will be the same as the path to the rule, which used to be true on unix (but not windows) but was not guaranteed, and is no longer true.
You need to ask the build system for the name of the file it is producing, and pass the information in to the test, the easiest way to do this is with $(location "://go/src/foo/bar:bar") in the test args parameter.
You can see how we do this in the [reproducible_binary](/bazelbuild/rules_go/blob/master/tests/reproducible_binary/BUILD.bazel) test.

**Comment by Helcaraxan** [comment]
I was suspecting something like that but could not find any reference to this. Probably because of a release-note or other mention of it that I have missed.

Let me try. Will post back to see whether that would fix it.

**Comment by jayconrod** [comment]
This was mentioned briefly in the 0.8.0 release notes, but they were long, and it's easy to miss.

I'll add a FAQ for this in #1144.

**Comment by Helcaraxan** [comment]
@ianthehat @jayconrod Thank you very much for the tip. I was indeed able to fix it using the suggestion.
