### ISSUE TITLE
Compatibility matrix for bazel_gazelle and rules_go

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_go#1158]
As a result of separating gazelle from this repo, we should consider put up a compatibility matrix in the README to indicate the right versions to use together -- as gazelle implicitly depend on certain version of rules_go. 

Alternatively, we should keep loading gazelle from rules_go, and let rules_go to import bazel_gazelle as an optional dependency and forward the rule as an alias.  This will help ease the burden of dependency management IMHO.

**Comment by ashi009** [comment]
Also, gazelle needs rules_go to build. Could you share the rationale for the split? I don't fully understand the benefit from this change.

**Comment by jayconrod** [comment]
+1 to more documentation on compatibility. I'll add this as soon as there's some incompatibility that needs to be considered.

I added a version number in go/def.bzl a little while ago so that Gazelle can automatically check when it's run with an incompatible version. It's not checking that yet (there are no incompatible versions since the split), but it's there when we need it.

There are a couple reasons for the split.

* Gazelle needs to depend on things that rules\_go doesn't need. Ideally, people should be able to depend on rules\_go alone without pulling in a bunch of other repos. For now, the dependencies are still shared because of `go_repository` (which uses Gazelle), but we'll deprecate and replace that soon.
* Gazelle should be versioned separately. I don't want to hold back a version of rules\_go or Gazelle because we're waiting on a feature or bug fix to be completed in the other one.
* We may want to add more non-Go functionality to Gazelle in the future.

**Comment by jayconrod** [comment]
One more thing: this allows people to fork and customize Gazelle without forking rules\_go. You can just point to a different repo.
