### ISSUE TITLE
Use gcc compiler instead of g++

### ISSUE THREAD

**Issue by preetiRK** [bazelbuild/rules_go#1172]
For rules_go version 0.8.0, I want to use gcc compiler instead of g++

I can see that the file **rules_go/go/private/rules/stdlib.bzl**
has the following code
 `"CC": cc_path,`

which resolves to CC : \usr\bin\g++

How can we change it to point to the gcc compiler?

I did the following changes `"CC": "/usr/bin/gcc",`. 
But is there a better way to do it?

**Comment by ianthehat** [comment]
The go rules use whatever cc toolchain you have configured, they do this because they also trigger cc_library and cc_binary rules, and the compilers need to match.
Changing this inside rules_go is not the right way to go, you need to look into the --compiler bazel flag or writing a custom CROSSTOOL.

**Comment by preetiRK** [comment]
Thanks for the response @ianthehat.
