### ISSUE TITLE
How to use .a files to build a go_test

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#118]
How to use .a files to build a go_test? my *_test.go files import ginkgo and gomega, but it too troublesome to build ginkgo and gomega with bazel. So I want to use ginkgo.a and gomega.a to build my go_test. Here is my BUILD file:

`package( default_visibility = ["//visibility:public"], )
 load("//go:def.bzl", "go_library", "go_test", "cgo_library")

go_test(
         name = "main_controller",
         srcs = ["main_controller_test.go"],
         deps = [
             ":cgo_enabled"
            ],
       )

cgo_library(
         name = "cgo_enabled",
         srcs = ["ginkgo.a", "gomega.a"],
         )`

But bazel shows the error:

`ERROR: /root/testgo/hsa-service-center/src/servicecenter/controllers/BUILD:39:1: Traceback (most recent call last):
        File "/root/testgo/hsa-service-center/src/servicecenter/controllers/BUILD", line 39
                cgo_library(name = "cgo_enabled", srcs = ["gin..."])
        File "/root/testgo/hsa-service-center/src/go/def.bzl", line 973, in cgo_library
                _cgo_import(name = "%s.cgo.importgen" % name, <6 more arguments>)
        File "/root/testgo/hsa-service-center/src/go/def.bzl", line 977, in _cgo_import
                go_srcs[0]
List is empty.
ERROR: error loading package 'servicecenter/controllers': Package 'servicecenter/controllers' contains errors`
How to solve it?

**Comment by pcj** [comment]
`cgo_library` wants you to give it a non-empty source file list: https://github.com/bazelbuild/rules_go/blob/master/go/def.bzl#L927.

If it's empty, it dies here https://github.com/bazelbuild/rules_go/blob/master/go/def.bzl#L977.  (probably the code should check for this).

Anyway, that does not solve your problem, since you want to pass in `*.a` files directly in.  I'm not aware of a way to do this today with rules go.  I've thought maybe there should be a `go_import` that roughly works like `java_import`to pass along transitive archive dependencies.

However, building ginkgo and gomega might not be as hard as you think with the new `new_go_repository` rule.  https://github.com/bazelbuild/rules_go#new_go_repository.  Have you tried it?

**Comment by GinFungYJF** [comment]
Because of the proxy problem, the new_go_repository doesn't work.Are there any other ways to build ginkgo and gomega?

**Comment by pmbethe09** [comment]
I don't understand "the proxy problem".  You are behind a proxy-server that
won't allow go get?
