### ISSUE TITLE
Skylark error with go_binary.embed

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_go#1184]
Just beginning to try out the `embed` feature.  

```python
go_binary(
    name = "app",
    srcs = [
        "app.go",
    ],
    embed = [
        "//etc/ssl:certs",
    ],
)
```

```sh
		@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect(...)
	File "/home/pcj/.cache/bazel/_bazel_pcj/edffb82b373c1795fe8130838c96263e/external/io_bazel_rules_go/go/private/rules/aspect.bzl", line 39, in _go_archive_aspect_impl
		go_context(ctx, ctx.rule.attr)
	File "/home/pcj/.cache/bazel/_bazel_pcj/edffb82b373c1795fe8130838c96263e/external/io_bazel_rules_go/go/private/context.bzl", line 147, in go_context
		attr._go_context_data
No attribute '_go_context_data' in attr. Make sure you declared a rule attribute with this name.
Available attributes: _action_listener, _cc_toolchain, _cc_toolchain_type, _config_dependencies, _genrule_setup, _host_jdk, _is_executable, _toolchains, cmd, compatible_with, deprecation, distribs, executable, features, generator_function, generator_location, generator_name, heuristic_label_expansion, licenses, local, message, name, output_licenses, output_to_bindir, outs, restricted_to, srcs, stamp, tags, testonly, toolchains, tools, visibility
```

Any suggestions?

Version: latest (at PR 1178 transitive link stamping)

**Comment by achew22** [comment]
@pcj, what is the type of `//etc/ssl:certs`? Based on the name I would guess it's a filegroup with some SSL certs. `embed` is used, in this context, to have multiple `go_library` rules that all define the same go package coexist under a common importable path. For example

```
go_library(
  name = "demo_library",
  srcs = ["demo.go"],
  importpath = "example.com/demo",
)

go_grpc_proto_library(
  name = "demo_proto",
  proto = "//path/to/proto",
  importpath = "example.com/demo",
)

go_library(
  name = "union",
  embed = [":demo_proto", ":demo_library"],
  importpath = "example.com/demo",
)
```

You could then depend on the `:union` target to get the `example.com/demo` package.

If you're seeking to embed data from a flegroup or a file, I would suggest looking at [`go_embed_data`](https://github.com/bazelbuild/rules_go/blob/master/extras/embed_data.bzl#L69) [(example)](https://github.com/bazelbuild/rules_go/blob/master/tests/go_embed_data/BUILD.bazel#L32) or [`bindata`](https://github.com/bazelbuild/rules_go/blob/master/extras/bindata.bzl#L30) [(example)](https://github.com/bazelbuild/rules_go/blob/master/examples/bindata/BUILD.bazel).

Possibly I'm misunderstanding your question though. Could you add a little bit more context about your intent?

**Comment by ianthehat** [comment]
We do actual compilation in an aspect, so that we can build in multiple modes.
The aspect traverses deps and embeds, picking up GoLibrary objects to form GoSource entries that get compiled into GoArchive objects.
To be used in an embed, you must provide a valid GoSource object, and to do that you must have access to a GoContext, which can only be built from a _go_context_data and a go_toolchain, so you have to declare you want both of those in any rule that you want to embed.
The reason is because we need to collect the deps that the GoSource carries in the same compilation mode.
The go_source rule is the simplest example to start from.
If you could tell me what you are trying to achieve I can offer more advice...

**Comment by pcj** [comment]
`go_embed_data` was indeed what I was looking for.  Thanks!
