### ISSUE TITLE
Could `rules_go` cache the golang tool chain binaries more aggressively?

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/rules_go#1185]
It seems like every time we change our WORKSPACE in certain ways, Bazel has to redownload this file:  `https://storage.googleapis.com/golang/go1.9.2.darwin-amd64.tar.gz`

That's quite a large file. Could it be cached in more cases?

Let me know if you need detailed repro steps (e.g: an analysis of what kind of WORKSPACE updates seem to trigger this redownload).

**Comment by ianthehat** [comment]
There is nothing rules_go can do to affect the caching, that's just a Bazel thing.
You can use --experimental_repository_cache, it will say it is downloading but just get the archive from the cache rather than the internet. Or you can use a proxy.

We can affect when it needs to re-run the sdk repository rule though (which it will do even if the cache works). It should only be refetching it if you upgrade rules_go or switch sdk, if there are other changes that cause it let us know what they are. Also, if you do clean --expunge that will obviously force it to re-fetch.

**Comment by nictuku** [comment]
Got it. I think in this case we had upgraded rules_go - which isn't common. Your comment helped me understand the problem and how to avoid the re-downloads. Thank you.
