### ISSUE TITLE
Invoking CC through a shell script is broken

### ISSUE THREAD

**Issue by yasushi-saito** [bazelbuild/rules_go#1202]
I have a small repro in

https://github.com/yasushi-saito/bazeltest

    bazel build --crosstool_top=//toolchain --cpu=k8  //:test

(I tested this setup only on Linux k8, but a similar problem happens on darwin too).

rules_go, commit 9cf23e2aab101f86e4f51d8c5e0f14c012c2161c can successfully compile the thing.
But commit 396f2424dd7c336e4b07b4f19d476f0749bc73dd fails with

```
bazel: Entering directory `/scratch-nvme/saito/bazel/_bazel_ysaito/8e1be0812e73f4331c48993fc6bb33d0/execroot/bazeltest/'
[0 / 9] [-----] BazelWorkspaceStatusAction stable-status.txt
[5 / 13] no action
[5 / 13] GoStdlib external/go_stdlib_linux_amd64_cgo/bin/go; 1s linux-sandbox ... (2 actions running)
ERROR: /scratch-nvme/saito/bazel/_bazel_ysaito/8e1be0812e73f4331c48993fc6bb33d0/external/go_stdlib_linux_amd64_cgo/BUILD.bazel:4:1: error executing shell command: 'export GOROOT="$(pwd)/bazel-out/k8-fastbuild/bin/external/go_stdlib_linux_amd64_cgo" GOOS="linux" GOARCH="amd64" CGO_ENABLED="1" CC="$(pwd)/toolchain/cc_wrapper.sh" CXX="$(pwd)/toolchain/cc_wrapper...' failed (Exit 2)
# runtime/cgo
fork/exec /scratch-nvme/saito/bazel/_bazel_ysaito/8e1be0812e73f4331c48993fc6bb33d0/bazel-sandbox/5518594992772081040/execroot/bazeltest/toolchain/cc_wrapper.sh: no such file or directory
```

The problem is the sandbox doesn't contain toolchain/cc_wrapper.sh, even though tools/{CROSSTOOL,BUILD} are declaring this file in all_files.

**Comment by yasushi-saito** [comment]
Ping?

The problem seems to be happening inside _stdlib_impl in
https://github.com/bazelbuild/rules_go/blob/master/go/private/rules/stdlib.bzl

I think the cgo rule needs to add some dependency to the files declared in crosstool all_files, but I don't have expertise in this code path to debug further.

**Comment by ianthehat** [comment]
Me neither...
I honestly have no idea how to get the files needed by the cc toolchain so we can have them as inputs, it works at the moment only because all existing cc toolchains use absolute paths to pre-installed tools.
I know how it will work once we get to the point where the cc rules use the proper toolchain system, but that's going to be a while.

**Comment by promiseofcake** [comment]
> I know how it will work once we get to the point where the cc rules use the proper toolchain system, but that's going to be a while.

Is there any update or place I can follow along for this underlying issue @ianthehat?

**Comment by jayconrod** [comment]
I don't think there is any public design doc or single issue to follow.

Last I heard, you can configure C/C++ compilers with `cc_toolchain` rules, which are a mix of regular build rules and proto / CROSSTOOL strings in attributes. I don't think automatic toolchain selection is working yet, and I don't think any more information is exposed to Skylark than before. So we still can't create actions to compile or link individual files.

That is needed for an ideal implementation of cgo and stdlib, but we could probably do something now that works better than what we have without additional Bazel support. Haven't had bandwidth yet to test and implement it though.

**Comment by promiseofcake** [comment]
> Last I heard, you can configure C/C++ compilers with cc_toolchain rules, which are a mix of regular build rules and proto / CROSSTOOL strings in attributes. I don't think automatic toolchain selection is working yet, and I don't think any more information is exposed to Skylark than before. So we still can't create actions to compile or link individual files.

So we do have this project which we use to build our pure C++ where we are doing that: [vsco/bazel-toolchains](https://github.com/vsco/bazel-toolchains)
[vsco/bazel-toolchains: tools/cpp/BUILD](https://github.com/vsco/bazel-toolchains/blob/master/tools/cpp/BUILD)

But we run into two issues, the one linked in this issue: 
* Our provided tools are relative to `external/org_chromium_clang_<arch>` but the working  ends up being the cgo runtime path: `
bazel-out/darwin-fastbuild/bin/external/go_stdlib_darwin_amd64_cgo/src/runtime/cgo/external/org_chromium_clang_mac/bin/clang`

```
tree bazel-sample/external/org_chromium_clang_mac/bin
bazel-godel/external/org_chromium_clang_mac/bin
├── clang
├── clang++ -> clang
├── clang-cl -> clang
├── llvm-symbolizer
└── sancov
```

* A second issue where the wrong toolchain is pulled (`linux` is pulled on `darwin` even when being explicit).

```
go_binary(
    name = "hello",
    srcs = glob(["hello.go"]),
    visibility = ["//visibility:public"],
    pure = "off"
)
```

```
bazel build \
  --host_cpu='darwin' \
  --cpu='darwin' \
  --compiler='compiler' \
  --glibc='macosx' \
  --crosstool_top=@co_vsco_bazel_toolchains//tools/cpp:default-toolchain \
  //tools/hello:hello
```

With `--toolchain_resolution_debug`, it seems that our provided toolchains are not even considered, but I do see that it will pick up my toolchain if I make the host_os the only option (how I reproduce the first part).

Sorry if that's a lot and if there are parts related to bazel itself and not this project, but we are seeing success on our c++ monorepo with the toolchain.

**Comment by jayconrod** [comment]
Sorry for the slow response. I've been swamped after the Go summit last week and some travel.

> Our provided tools are relative to external/org_chromium_clang_<arch> but the working ends up being the cgo runtime path: bazel-out/darwin-fastbuild/bin/external/go_stdlib_darwin_amd64_cgo/src/runtime/cgo/external/org_chromium_clang_mac/bin/clang

I'm not completely sure I follow, but the problem is relative paths in the toolchain, right? This was mentioned in a few other issues. A big obstacle is that we use `go install` to build the standard library, and internally, the Go build system creates temporary directories and runs compiler processes in them. So any relative paths will be wrong. Some people have worked around this by wrapping the C compiler in a shell script that absolutizes paths. A better interim solution would be for [go/tools/builders/stdlib.go](https://github.com/bazelbuild/rules_go/blob/master/go/tools/builders/stdlib.go) to absolutize paths in `CC`, `CFLAGS`, other other parts of the toolchain before invoking `go install`. A proper long-term solution would be to generate build files that we can use to build the standard library with `go_tool_library` or something similar.

Thank you for posting the toolchain repo by the way. I expect that will be extremely helpful for verifying changes in this area.

> A second issue where the wrong toolchain is pulled (linux is pulled on darwin even when being explicit).

I suspect the cause of this is the way we determine the host platform in [sdk.bzl](https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl#L28). At that point, we are only aware of the platform where Bazel is invoked, not the platform where actions are actually executed. I'm not sure whether `--host_cpu` is exposed in Skylark at that stage, and if it is, its values are arbitrary, so we can't really interpret them in repostory rules.

I need to do more research on remote execution and chat with the core Bazel folks about solutions before proposing any solution. I know there is some ongoing work with repository rules that may affect this.

**Comment by jayconrod** [comment]
(Re-triaging old issues)

Closing as obsolete. Both Bazel's handling of C/C++ toolchains and rules_go integration with those toolchains have been rewritten since this issue was filed.
