### ISSUE TITLE
How do I use the bindata rule from extras?

### ISSUE THREAD

**Issue by novabyte** [bazelbuild/rules_go#1216]
I've tried to understand the make up of the code and added it to my Bazel project but I use 0.8.1 of the rules and can't resolve `go_context`? Is it possible to use the bindata rule directly from the http_archive download of the rules?

**Comment by novabyte** [comment]
I've figured out my mistake. The structure of the repo after 0.8.1 is significantly different and uses `go_context` which was written after this release. I've updated my code to use the older version of the `extras/bindata.bzl` rule. This works well now.

The last part I'm interested in is what the best practice is around generated files and Go projects with the `go_rules`. I use the bindata rule to generate the data as code source file. I'd like to check it into the repository so that `go build -i` continues to work in development.

What is the best practice advice? Is it possible to configure Bazel to write the output into the source tree so it can be checked in?

**Comment by ianthehat** [comment]
There is no good way to do this right now. Bazel by design does not modify the source directory as part of a normal run, and does not give you any way to do so. We jump through some fairly crazy hoops in the gazelle rule to allow you to `bazel run //:gazelle` and have it actually do anything, but I would not recommend that technique.

I do have some plans for good ways to drop generated code back into the source directory, along with tests that check the ones in the source directory are up to date that you could use as presubmit failures, but I have not had time to write them and see how well it works yet.

**Comment by novabyte** [comment]
That's ok @ianthehat. Thanks for the reply. I've opted for a rather awkward but workable solution for now which is to have a shell script move the files around so they can be added to the source tree. It's a manual step and could result in stale generated code but practical enough for now.

My solution looks like:

```sh
#!/usr/bin/env bash

# This command uses Bazel to (re-)generate Go files which should be
# checked into the source tree for simpler development builds.

set -o errexit
set -o nounset
set -o pipefail

parent_dir=$( cd "$(dirname "$0")" ; pwd -P )
pushd "${parent_dir}" > /dev/null

if ! [[ -x "$(command -v bazel)" ]];
then
    echo "Error: 'bazel' is not installed or executable from the system PATH." >&2
    exit 1
fi

# (re-)generate Go code
bazel build //dashboard:generated
if [[ $? != 0 ]];
then
    exit 1
fi

gen_file="../bazel-bin/dashboard/generated.go"
if ! [[ -e "${gen_file}" ]];
then
    echo "Error: '${gen_file}' was not generated or could not be found."
    exit 1
else
    cat "$gen_file" > "../dashboard/generated.go"
fi
```

Hope the strategy helps others.
