### ISSUE TITLE
go_proto_library appears to require explicitly restating dependencies

### ISSUE THREAD

**Issue by creachadair** [bazelbuild/rules_go#1228]
Given two `proto_library` rules, e.g.,

    proto_library(
        name = "a_proto",
        srcs = ["A.proto"],
    )
    proto_library(
        name = "b_proto",
        srcs = ["B.proto"],
        deps = [":a_proto"],
    )

I tried using `go_proto_library` to define Go versions, e.g.,

    go_proto_library(
        name = "a_go_proto",
        proto = ":a_proto",
        importpath = "kythe.io/kythe/proto/a_proto",
    )
    go_proto_library(
        name = "b_go_proto",
        proto = ":b_proto",
        importpath = "kythe.io/kythe/proto/b_proto",
    )

But upon attempting to build `b_go_proto` I was informed that `b.pb.go` has an

    import of kythe.io/kythe/proto/a_proto, which is not a direct dependency

Adding to the `b_go_proto` rule `deps = [":a_go_proto"]` allowed it to build. Is it really necessary to restate the dependencies explicitly? If so, that seems broken: Other languages are able to resolve their proto-based dependencies just fine, and Go should be able to do better I think.

Hopefully I am just doing something wrong. I have added appropriate `go_package` options to all the .proto files, despite having found an issue claiming it is no longer necessary—we are stuck on Bazel 0.7.0 until I can get our Go protobuf rules working again, which predate the existence of these and were broken by recent Skylark changes. Did I miss any other requirements?

**Comment by ianthehat** [comment]
Yes, because the import to label mapping does not have to be unique, and the proto_library to go_proto_library also does not have to be unique.
If you are using gazelle, it should do this for you and get it right for all the simple cases where there was no ambiguity. This is no different to any other go import, all the proto dep does is tell you what package needs importing, just like an import line in a go file, it does not tell you which go_library rule represents that compiled package.

The go_package option is no longer needed, and has no effect at build time. It can still act as a hint to gazelle when generating the go_proto_library rules though.

**Comment by creachadair** [comment]
> Yes, because the import to label mapping does not have to be unique, and the proto_library to go_proto_library also does not have to be unique.

That is true for other languages, such as C++ and Java as well—why do those languages not require this special dispensation but Go does?

**Comment by ianthehat** [comment]
It's not true for other languages...
The way other languages work is by propagating an aspect across the proto hierarchy and generating exactly one language specific output per proto rule. 
That aspect is allowed access to only information carried by the proto rule, which means it cannot vary it's behavior in any way, and more importantly it cannot add extra sources to the generated library.
Inside google, go works the same way, but that pattern is not capable of dealing with the way the go community use proto, where adding extra files to the generated .pb.go files to form a package is common behaviour. This requires us to have a full hierarchy of go_proto_library rules, rather than the aspect.
We also allow variants, you can have two go_proto_library rules that work from the same proto_library, which means you now have to make a decision about which of those variants you are depending on in anything that depends on that proto.

**Comment by strican** [comment]
@ianthehat - Can you explain this a bit more? It sounds like you're describing certain patterns that are specific to go but not to protos, and those conflict. For example, one commenter in #707 describes using an external proto repo, which is our use case as well. This seems to be relatively common, and it should be expected given that protos are meant to be compiled into multiple languages. Therefore, the rules go uses to interact with the generic proto libraries should at least support common methods of use and not be restricted to go patterns.

I'm new to bazel, so forgive if these suggestions are not realistic, but here are a few ideas I had:

1. Could using the default packaging be an option that we supply to `go_proto_library`?
2. Could we have a go_proto_repository rule for specifically this case, where gazelle can't auto-generate the dependencies?
3. You mentioned a `go_proto_source` rule in the other issue? Assuming it has the behavior described, that would work to.

**Comment by jayconrod** [comment]
@ianthehat investigated this closely. As explained above, the aspect approach is not viable because it doesn't allow any variation in how Go code is generated from .proto. I think the biggest problem was that you couldn't generate code with and without gRPC, but there may have been other issues. In general, people use lots of different protoc plugins, and we need to support them. We can't do that without explicit dependencies.

I'm not sure I understood your suggestions. What did you mean by default packaging?

I'd rather not expand the API surface by adding new rules unless we can't solve a problem any other way. We also have very limited bandwidth for feature work right now.

**Comment by strican** [comment]
@jayconrod, I was referring to this line.

>  adding extra files to the generated .pb.go files to form a package is common behaviour.

In my mind, the "default" packaging behavior would be to _not_ add extra files, thus we could avoid the problem being described. Maybe some kind of behavior where if a certain flag is set, it invokes an aspect-based implementation and if not, then it can use the existing one? Or just a new aspect that is available for anyone that needs it.

Based on what you're saying, it sounds like there might be another way to accomplish what I'm asking. The ways I've seen so far are:
1. Manually create every corresponding go library for each proto. Sure, this seems like it'd work, but it hardly seems sustainable, and it requires external consumers to understand the entire dependency graph of the proto repo. That defeats the purpose of having separate projects for those.
2. Use gazelle to generate the go libraries inside the proto repo. Again, because go here is behaving in a way that is inconsistent with pretty much every other language, it adds dependencies to otherwise language-neutral protos on go and prevents a clean separation of the contracts from the consumers of the contract. Having a separate `protos-go` repo also is impossible because we get right back to the first problem.
3. An aspect-based implementation allows for the above scenario but might prevent other common patterns with consuming local protos.

So either I'm missing something or there seems to be a gap here (unless you're saying "manually define and keep in sync a local go version of the dependency graph of an external repo" is a sufficient solution).

**Comment by creachadair** [comment]
My information may be out of date now, but I think we are basically dealing with a legacy impedance mismatch. Inside Google the protobuf rules basically all plumb dependencies by default into the per-language actions. This works because there are relatively few protobuf generators, and the aspect-driven rules mostly configure which variation you get with flags on the code-generator rule. I had hoped we could do something similar here, at least as a default.

Unfortunately, the Go protobuf rules from inside Google bear (at least as of when I left) little resemblance to the ones defined in `rules_go`. I filed this issue because the Kythe project uses a lot of Go protobufs, and we wanted a clean way to specify the rules so that we could import the project into Google without having to rewrite all the rules. A default as @strican described would be ideal, but as far as I can tell there is no plan to make the two rule-sets compatible. 

(For Kythe, we wound up writing a bunch of macros and doing some explicit rewriting on import—our work was not considered a high-priority for either internal or external Go development, and we had to get something working)

**Comment by jayconrod** [comment]
Solution #2 is the recommended approach.

So is the goal to have a repository that only has `proto_library` rules and no `go_proto_library`, `java_proto_library`, etc alongside those rules?

**Comment by creachadair** [comment]
> So is the goal to have a repository that only has `proto_library` rules and no `go_proto_library`, `java_proto_library`, etc alongside those rules?

Having to write a `go_proto_library` rule was fine for us—the problem we had was that we had to manually propagate the dependencies from the `proto_library` rules into the `go_proto_library` mirrors. (I can't speak for @strican).

In the end, we wound up just maintaining it manually and using a combination of shim macros and Copybara rules to hack it on import.

**Comment by strican** [comment]
> So is the goal to have a repository that only has `proto_library` rules and no `go_proto_library`, `java_proto_library`, etc alongside those rules?

Yes. The idea being that it's not the job of the proto repo to say what languages it supports. By nature of being a proto, it supports anything protoc supports. It doesn't make sense to update the proto repo when you want to consume the protos in a new language - the protos didn't change. Imagine a process by which a proto repo requires an API review to be completed for changes. Now you need an exemption for this change when it should have never been in the scope of the protos repo in the first place.

Furthermore, the dependencies and rules for each of the different languages are varied and complex. I think it's fair to say that bazel isn't the easiest thing to debug. Not adding the complexity of every language's bazel dependencies and rules seems like a strictly good thing. It also reduces the likelihood of someone with no experience with the Go rules hitting an issue with them. They're all localized in Go repos because they're building the protos there. And likewise devs in those repos won't need to worry about the Typescript rules, etc.

And this approach extends when there are multiple consumers, too. An intermediate protos-go repo can easily be created using this approach that can provide packages for the compiled go_proto_libraries. Part of the appeal of bazel is how it allows external projects to be included as if they're local without needing to worry about distribution or hosting beyond git. This breaks the promise of working with simple modules in a first-class way.

**Comment by strican** [comment]
@creachadair - Was using gazelle not an option for you? That seems like the approach we would take if we have to, but it means compromising on the separation I laid out above.

**Comment by creachadair** [comment]
> @creachadair - Was using gazelle not an option for you? That seems like the approach we would take if we have to, but it means compromising on the separation I laid out above.

It wasn't at the time (I don't think it was released yet, though the repository existed). It might be now, though I'm not clear on how Gazelle will affect imports.

**Comment by strican** [comment]
> I'm not clear on how Gazelle will affect imports.

Me neither. 🙃

One thing I'll say is that I keep running into scenarios that "should work" according to the principles of bazel but end up not working. It basically forces me to actually implement the entire end-to-end build system I'm imagining before actually deciding that the approach is viable.
