### ISSUE TITLE
go_repository specificy custom proto compiler

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_go#1246]
I mentioned it already here https://github.com/bazelbuild/bazel-gazelle/issues/34, as I suppose this issue would be dependent on that one, but it would be nice to be able to specify the proto compiler third party dependencies, so I could simply do:

```
go_repository(
        name = ".....",
        commit = "....",
        importpath = "...",
        build_file_proto_compiler = "@io_bazel_rules_go//proto:gogofaster_grpc",
    )
```

Right now I am running into an issue where I have my own go_proto_libary that is compiled using `gogofaster` and it depends on an other proto (`@org_golang_google_genproto//googleapis/rpc/status:go_default_library`) to be specific, which is not build using `gogofaster` and then the compiler complains about undefined fields in the generated code, which should be there when compiling this third party dependency with `gogofaster`.

**Comment by ianthehat** [comment]
I don't think this is a good idea. The external repository may be shared by multiple dependencies, changing the gazelle arguments would break the others. Adding proto specific knowledge to go_repository is unpleasant at best, and we are trying to kill go_repository, so adding more features to it is counter-productive at this time.

If the repository added build files, gazelle would get turned off and you would get broken again
You don't need this anyway, the go_proto_library rules don't need to be in the same package as the proto_library so  you can just add a bunch of them to your repository.

If we really are going to to this, then at most we should add a gazelle_args attribute where you can specify custom gazelle arguments rather than adding knowledge about this specific argument.

**Comment by Globegitter** [comment]
I agree @ianthehat that specifying `gazelle_args` would be a nice solution. Well the main reason this came up for us is because our code depends on a third party googleapi proto but also the grpc library depends on that same proto. So if we depend on another one that is compiled with gogofaster we are getting some `type redeclation` error on compilation of the generated proto code.  So my thinking was, would be great if we could make everyone depend on the gogofaster compiled proto and that would hopefully solve that problem. 

But maybe the new `importmap` stuff could help with that problem also.

**Comment by jayconrod** [comment]
I don't think we've adequately addressed this problem yet, but let's point to bazelbuild/bazel-gazelle#181 as  the canonical issues for Gazelle+go_repository support for gogoprotobuf.
