### ISSUE TITLE
Documentation build

### ISSUE THREAD

**Issue by lexfrei** [bazelbuild/rules_go#1293]
Hello!
Are there any plans for adding a rule for docs build?
In my dreams, it will build static HTML docs on every build.

**Comment by ianthehat** [comment]
At the very least there are plans to make it easy to run such tools yourself, and I suspect a working example of a go_doc rule would be a minimum proof of concept.

**Comment by chrislovecnm** [comment]
@lexfrei do you have a work around?

**Comment by jayconrod** [comment]
(Re-triaging old issues)

Closing as out of scope for rules_go (though this is important functionality that would be valuable to have).

When #512 is implemented, tools built on `golang.org/x/tools/go/packages` will work in Bazel workspaces automatically. `golang.org/x/tools/cmd/godoc` could be modified to load files using `golang.org/x/tools/go/packages` instead of assuming `GOROOT` and `GOPATH`.
