### ISSUE TITLE
go_repository should have a 'timeout' parameter

### ISSUE THREAD

**Issue by lazdmx** [bazelbuild/rules_go#1305]
Currently I have to use very slow cellular network and it makes an issue especially in attempts to fetch big repos like `github.com/docker/docker`. Every attempt fails with a timeout (current default is 600sec) error because of ~200MB must be fetched.

So, I think that it would be helpful if `go_repository` will have a `timeout` parameter that will be passed directly to `repository_ctx.execute`?

**Comment by jayconrod** [comment]
I'd rather not have `timeout` be a property of repository rules. Ideally, it should be something you set locally, rather than something checked into your repository. Bazel doesn't provide a way to do that, unfotunately.

Really though, I can't think of a reason why `timeout` should actually be on by default for commands executed in repository rules. In this case, the download is still making progress (you could always ^C it if it weren't).

We can't actually disable the timeouts for these commands, but in #1315, I've raised it to 86400s (a day). Hopefully, that helps. I'll file an issue with Bazel itself later.
