### ISSUE TITLE
go_proto_library emits generated source under bazel-bin

### ISSUE THREAD

**Issue by creachadair** [bazelbuild/rules_go#1325]
Given a go_proto_library target like `//foo:foo_go_proto`, running

    bazel build //foo:foo_go_proto

will emit the generated source not under `bazel-genfiles` like other proto generator rules, but in a location like

    bazel-bin/foo/linux_amd64_stripped/foo_go_proto~/blah.org/foo/foo_go_proto/foo.pb.go

While arguably not a bug, this seems like a gratuitous difference, and since the standard recommendation for understanding how something works in the Go generated code for protobuf target is to read the generated source, this difference makes it harder to locate the source.

The extra path noise surrounding the generated code is also not great—it makes sense for the compiled output, but not for the generated source. Ideally the generated source should not need to depend on architecture-specific details (particularly for Go which does not admit switches for such variations in the generator).

**Comment by jayconrod** [comment]
About `bazel-genfiles`, my understanding is that everything should go in `bazel-bin` unless there's a specific compatibility reason that it needs to go in `bazel-genfiles`. I'm not sure what those compatibility reasons are (something something C++ header generation), but as far as I know, they don't apply to us. This is briefly mentioned in the documentation for [rule](https://docs.bazel.build/versions/master/skylark/lib/globals.html#rule); see `output_to_genfiles`. It's regrettable that there are two separate output trees in the first place, but I assume it's too late to remove genfiles entirely from Bazel.

About configuration info in output file names: we declare all output files using the same infrastructure. This simplifies our implementation. These paths aren't really intended to be exposed directly to users, and no one should depend on them since they may change. We have an experimental mechanism, [`go_path`](https://github.com/bazelbuild/rules_go/blob/master/go/private/tools/path.bzl) for constructing a buildable Go source tree that includes generated code. We'll probably extend and improve that, but that's the direction we want to go in.

**Comment by strican** [comment]
@jayconrod - Do you have more info on `go_path`? I don't see it in the docs, but it appears to be in master. I had planned on writing a script to copy the outputs of `go_proto_library` into the source tree (where they can be .gitignore'd) for the sake of IDE integration. It sounds like `go_path` would solve that issue, so I'm keen to use it.

**Comment by creachadair** [comment]
> @jayconrod - Do you have more info on `go_path`? I don't see it in the docs, but it appears to be in master. I had planned on writing a script to copy the outputs of `go_proto_library` into the source tree (where they can be .gitignore'd) for the sake of IDE integration. It sounds like `go_path` would solve that issue, so I'm keen to use it.

If your goal is to check in copies of the generated source so that your Go packages can be built without invoking Bazel, then you'll have to use a script. Bazel will not write files into the source tree, independent of whether you're using Go.

We did this in Kythe, using a [Python script](https://github.com/kythe/kythe/blob/master/kythe/proto/generate_go_protobufs.py). To ensure we don't forget to run this script, I also added tests that generate the source and compare it to what is checked in, and fail if they differ.

I don't claim our implementation is ideal, but it does work. If you want to see what we did, https://github.com/kythe/kythe/blob/f9a7e299c8f89316e8a09635b143023a1950d6d3/tools/build_rules/testing.bzl#L3 is the macro to perform the test (basically a genrule to copy files around and a `sh_test` to run `diff` on the results), and https://github.com/kythe/kythe/blob/f9a7e299c8f89316e8a09635b143023a1950d6d3/kythe/proto/go.bzl#L36 is the macro that conjoins the proto generator with the test rule.

Writing and debugging this stuff can be a real pain, so apologies in advance if any of this doesn't make sense.

**Comment by strican** [comment]
@creachadair - I made it to this thread because the bazel-bin directory structure is much less conducive to having a script pull them all out. Your script could be helpful in that regard.

As far as `go_path` is concerned, it sounds like whatever that rule does would allow me to get the benefits of that source tree without actually needing to copy the generated files over. That would be ideal.

**Comment by creachadair** [comment]
> As far as `go_path` is concerned, it sounds like whatever that rule does would allow me to get the benefits of that source tree without actually needing to copy the generated files over. That would be ideal.

It depends what you are trying to accomplish. For us, it's important to have the files in the source tree, because we want `go get` to work for our protobuf packages in Go without the user having to install Bazel and the whole toolchain. That in turn is essential to making everything else in the project `go get`table, as we depend heavily on protobuf packages.

However, if you are only trying to run tools on the generated files, and don't actually need to check them in, you can probably do something simpler.

**Comment by jayconrod** [comment]
@strican Here's the [`go_path` documentation](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path).

`go_path` is primarily useful for running tools that expect to be run in something that looks like a `GOPATH` directory, including generated code. For Bazel actions that consume a `go_path`, see the [`GoPath` provider](https://github.com/bazelbuild/rules_go/blob/master/go/providers.rst#gopath).

If you do end up needing to check in generated files, @creachadair's solution is the right approach.

**Comment by strican** [comment]
Gotcha. Well it actually seems like the solution I'm looking for is tracked by #512. It doesn't seem like that's ready for consumption though, is it?

**Comment by strican** [comment]
One other thing to note - with the move towards modules, is go_path sufficient? Copying it into the source tree assumes we're using a local GOPATH, right? And it seems like we'd need to output `go.mod` files in `go_path` at least if we're using `replace` in our consuming `go.mod` files ([as suggested here](https://www.reddit.com/r/golang/comments/ah0w1q/modules_and_local_imports/)).

**Comment by jayconrod** [comment]
Tools that are compatible with modules should use `golang.org/x/tools/go/packages`. The solution for #512 is a driver for that framework that loads package data for Bazel workspaces. It's likely we'll need a second driver to be run within actions, but it will probably be able to consume the same information.
