### ISSUE TITLE
Inconsistent behavior between go test and go_test rule

### ISSUE THREAD

**Issue by crazytan** [bazelbuild/rules_go#1336]
In tests, when an invalid argument is given for a verb in `fmt.Printf` function, `go test` and `go_test` rule have different test outcome. Say we have this simple test for package `hello`:
```
package hello
import (
	"fmt"
	"testing"
)
func TestPrintf(t *testing.T) {
	fmt.Printf("%d", "abc")
}
```
When running `go test hello`, it outputs
```
./hello_test.go:9: Printf format %d has arg "abc" of wrong type string
FAIL	hello [build failed]
```
But when I run `bazel test //...` with this BUILD, test passed.
```
go_test(
    name = "go_default_test",
    srcs = ["hello_test.go"],
)
```

**Comment by ianthehat** [comment]
That's because in recent versions of the go tool it is running vet checks at the same time as it builds the test, we just build and run the test.
You will notice the message you are getting includes `[build failed]` to indicate it's not a test failure. There is nothing that tells you it's a vet failure rather than a compile failure though.
#1292 is tracking us adding that feature.
