### ISSUE TITLE
Remove @io_bazel_rules_go repository

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_go#135]
I made a change to let remote repositories refer to the main repository by its name (https://github.com/bazelbuild/bazel/commit/5c071429e83b5c6d872c755d3da21ad934638111) but it broke the go rules (http://ci.bazel.io/job/rules_go/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/370/console) because the WORKSPACE already has a local repository with the same name as the workspace (https://github.com/bazelbuild/rules_go/blob/master/WORKSPACE#L16-L19).  So it got rolled back.

Can you remove that repository rule?  I gave it a quick look, but it didn't seem trivial.

**Comment by pmbethe09** [comment]
I don't know a clean way to fix rules_go in advance of your change.

However if your change works, than we can just remove the
local_repository(name = "io_bazel_rules_go", ...)
as soon as your change lands and it should Just Work.

Happy to coordinate that.

**Comment by kchodorow** [comment]
Well... unfortunately we test rules_go against both Bazel at HEAD and the latest release (0.3.2), which doesn't have the change.  So the go_rules would have to support both, for a while (or look broken on CI until the next release.)

**Comment by pmbethe09** [comment]
I had a look at this, but it gets really tricky due to all of the recursive
references in BUILD rules, but also the way that new_go_repository
recursively uses gazelle and fetch_repo.

I am not sure that it is possible to do this cleanly.  Any way to time up
for submission just before a bazel release?

**Comment by yugui** [comment]
This `local_repository` was necessary because `BUILD` files in buildifier and generated `BUILD` files in `@org_golang_x_tools` refer `@io_bazel_rules_go`.

For the latter one, I used to examine another approach. We might tentatively introduce this approach as a workaround.  The approach was to add a special attribute `rules_go` to `go_repository`, which specifies the repository name of rules_go.

For buildifier, we can regenerate all the `BUILD` files in buildifier as @pmbethe09 said.

**Comment by yugui** [comment]
I tried implementing in https://github.com/bazelbuild/rules_go/tree/workaround/recursive-ws-ref.
But the merger did not merge `load` statements as I expected because mismatch of the first argument.

So we need a better way to deal with buildifier.  Several ugly solutions come to my mind.
* Define a special rule only for buildifier and modify `BUILD` files in it
* Accept a post-checkout script in an attribute of `go_repository` and apply `sed`. 

`@io_bazel_buildifier//:BUILD`:
```bzl
load("@io_bazel_rules_go//go:def.bzl", "go_prefix")

go_prefix("github.com/bazelbuild/buildifier")

load("//go:def.bzl", "go_prefix")
```

`@io_bazel_buildifier//core:BUILD`:
```bzl
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load(":build_defs.bzl", "go_yacc")

go_yacc(
    src = "parse.y",
    out = "parse.y.go",
)

go_library(
    name = "go_default_library",
    srcs = [
        "lex.go",
        "print.go",
        "quote.go",
        "rewrite.go",
        "rule.go",
        "syntax.go",
        "tables.go",
        "walk.go",
    ],
    visibility = ["//visibility:public"],
)

go_test(
    name = "build_test",
    size = "small",
    srcs = [
        "parse_test.go",
        "print_test.go",
        "quote_test.go",
    ],
    data = glob(["testdata/*"]),
    library = ":go_default_library",
)

load("//go:def.bzl", "go_library", "go_test")

go_test(
    name = "go_default_test",
    srcs = [
        "parse_test.go",
        "print_test.go",
        "quote_test.go",
    ],
    library = ":go_default_library",
)
```

**Comment by yugui** [comment]
@kchodorow, @pmbethe09 
In #141, I have added two hacks.  We can safely remove these hacks when we drop support of Bazel 0.3.2 or earlier. Could you take a look? 

1. Add an attribute `go_rules_bzl_only_for_internal_use` to `new_go_repository`.  This attribute overwrites the path to `go/def.bzl` in generated `BUILD` files.
2. Add a rule `buildifier_repository_only_for_internal_use`. This fetches buildifier in the same way as `go_repository` and replaces all the occurrence of `@io_bazel_rules_go//` with `@//`.
