### ISSUE TITLE
Support for vgo

### ISSUE THREAD

**Issue by kaoet** [bazelbuild/rules_go#1362]
Is there any plan to support vgo? https://research.swtch.com/vgo

**Comment by jayconrod** [comment]
I think we'll mainly support vgo by having Gazelle import repositories at specific tags or commits into WORKSPACE. Gazelle supports this now for dep (`gazelle update-repos -from_file Gopkg.lock`). We will expand that to support vgo and other dependency management systems.

**Comment by kaoet** [comment]
There is more to do than just supporting import from `go.mod`. If the top project is built with vgo, all `vendor` directory should be ignored, and gazelle should not generate build rules for them. It should also apply to those external projects brought in by `go_repository`.

**Comment by jayconrod** [comment]
Sure, there's definitely more to do than just importing `go.mod`. I expect nearly all this work will be done in Gazelle though: it will take a vgo project and generate WORKSPACE and BUILD.bazel files that tell Bazel to build the same thing. I don't expect `go_binary`, `go_library`, `go_test` to need much modification.

**Comment by zllak** [comment]
Just my two cents, but isn't it way too early to start supporting vgo ? It's not even a finalized proposal, it's just an experiment.

**Comment by mmikulicic** [comment]
Go modules are going to be included in Go 1.11, to be released soon

See https://github.com/golang/go/wiki/Modules

Note on nomenclature: vgo is the name of the experimental tool implementing Go modules, thus IMHO the issue should be renamed to "Support Go modules"

**Comment by jayconrod** [comment]
Closing some old issues. I don't believe rules_go will need to change anything to support Go modules, f.k.a. vgo. `go_binary`, `go_library`, and `go_test` won't need to work any differently.

Instead, all the heavy lifting will be done by Gazelle. It should look something like `gazelle update-repos -from_file=go.mod`.

**Comment by wking** [comment]
Related Gazelle issues are bazelbuild/bazel-gazelle#200 and bazelbuild/bazel-gazelle#292.

**Comment by mmikulicic** [comment]
The go toolchain is now able to perform hermetic builds based on the contents of the go.mod and go.sum files.

The go tool will download dependencies in `$GOPATH/pkg/mod` (e.g. `$GOPATH/pkg/mod/golang.org/x/crypto@v0.0.0-20170808112155-b176d7def5d7`)

All we have to do is to ensure that the go.{mod,sum} file are accessible from the sandbox and ensure that the build sandbox can write to $GOPATH/pkg/mod

If every go_{library,binary} rule had an implicit dependency to the go.{mod,sum} files, then developers wouldn't need to care about maintaining explicit dependencies with gazelle.

The downside is that a single change in the go.mod file will trigger a fully project rebuild as far as bazel is concerned, but which in turn would be mostly cached by the go toolchain.

wdyt?

**Comment by jayconrod** [comment]
`go build` is a different build system than Bazel. Gazelle will be able to import go.mod files and generate/update equivalent WORKSPACE files (I plan to finish adding that next week when I'm back from GopherCon), but rules_go will not use them directly.

> If every go_{library,binary} rule had an implicit dependency to the go.{mod,sum} files, then developers wouldn't need to care about maintaining explicit dependencies with gazelle.

Then we'd be in a situation where sandboxed actions need to fetch and verify repositories over the network. Bazel actions should be hermetic.

**Comment by mmikulicic** [comment]
> Bazel actions should be hermetic.

I know it's not ideal to perform networking IO during the execution phase, but technically actions can perform network IO with `requires-network`, as long as the actions are logically hermetic, i.e. their outputs is fully described by their inputs and doesn't depend on external values that might change while the action inputs stay constant. The go.mod+go.sum combo makes execution of the logic behind `go build` hermetic even if it downloads stuff.
That said, I totally get why this wouldn't be kosher.

What bothers me is the duplication of dependency declarations. The go.mod file would be the file users manage through the go tooling (e.g. when bumping up a version of a dependency, which might require to bump up a transitive dependency and so on; the go tool knows how to deal with that).
Then this file has to be fed into `gazelle`.
I'm already having a hard time selling bazel to my co-workers, so I'd really like finding a solution that doesn't involve this last step, at least for simple projects.

Could we offload the downloading of packages referenced by go.mod in the analyze phase, so that execution only references previously downloaded files (but still without requiring a full entry in the WORKSPACE for each external repository?)

**Comment by jayconrod** [comment]
> I know it's not ideal to perform networking IO during the execution phase, but technically actions can perform network IO with requires-network, as long as the actions are logically hermetic, i.e. their outputs is fully described by their inputs and doesn't depend on external values that might change while the action inputs stay constant.

I agree this could be done hermetically, but it would make a lot of people very unhappy, especially in enterprise CI environments.

> What bothers me is the duplication of dependency declarations. The go.mod file would be the file users manage through the go tooling (e.g. when bumping up a version of a dependency, which might require to bump up a transitive dependency and so on; the go tool knows how to deal with that).

I get what you're saying here, and I've heard a lot of the same feedback about build files in general. Ultimately though, go.mod is a build file for a different build system with different semantics, and Bazel won't read it. I'll try to make the Gazelle import workflow as smooth as possible.

**Comment by mkmik** [comment]
I was trying to implement the `update-repos -from_file go.mod` feature in gazelle, and I didn't find a good way to translate the go.mod into `go_repository` (via github.com/bazelbuild/bazel-gazelle/internal/repos.Repo) rule.

In particular the go.mod and go.sum files don't contain the full git commit, so it would work dependencies that have a tag but not for something like v0.0.0-20170411212101-a0d1ef9a7ccb.
While it's possible to hack around it by checking out the repo in a temporary dir, and then finding
the commit that matches the shortened sha and the datestamp, this would require more bandwidth and wouldn't work with non-git dependencies.

Thus, I was thinking: if `go_repository` rules are just workspace rules that download some external files at some specific version, why don't we have a `go_modules(mod="go.mod", sum="go.sum")` workspace rule that runs:

```
GOPATH=bazel-out/....??? go mod download
```

go mod download will always download the very same files every time, and it will be executed during the analyze phase.

`go_modules` would then run gazelle on each downloaded repository (e.g. somedir/pkg/mod/github.com/foo/bar@v1.0.0), controlled by an analogous of the `build_file_generation` attribute of the `go_repository` rule.

I think this would result in having bazel having a fully dependency graph in pretty much the same way as it does right now, albeit all go dependencies would be under the same repository rule, e.g.:

`@gomodules//github.com/foo/bar:go_default_library`

I assume the rule should live in the gazelle repository but I posted this here because of thread continuity
