### ISSUE TITLE
Duplicate package in go_path

### ISSUE THREAD

**Issue by junghoahnsc** [bazelbuild/rules_go#1386]
Hello,

After go_rule introduced `https://github.com/bazelbuild/rules_go/tree/master/proto/wkt` package, go_path fails with the following warnings:

```
DEBUG: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/io_bazel_rules_go/go/private/tools/path.bzl:72:7: Duplicate package
Found github.com/golang/protobuf/ptypes/any in
  @com_github_golang_protobuf//ptypes/any:go_default_library
  @io_bazel_rules_go//proto/wkt:any_go_proto
DEBUG: /home/jhahn/.cache/bazel/_bazel_jhahn/096b9924a546d44702313d7a4b963776/external/io_bazel_rules_go/go/private/tools/path.bzl:72:7: Duplicate package
Found github.com/golang/protobuf/ptypes/duration in
  @com_github_golang_protobuf//ptypes/duration:go_default_library
  @io_bazel_rules_go//proto/wkt:duration_go_proto
...
```

Is `io_bazel_rules_go//proto/wkt:xxx_go_proto` required? How can I resolve this?

Thanks,

**Comment by jayconrod** [comment]
The `@io_bazel_rules_go//proto/wkt:xxx_go_proto` dependencies are introduced by `go_proto_compiler` rules that declare them in their `deps` attribute. That's intended to be the standard way to pick up WKT dependencies.

Where are the `@com_github_golang_protobuf` dependencies coming from? Are those declared explicitly anywhere? You should be able to drop them.

At some point, it will be an error to have more than one package declaring the same `importpath` without `importmap`. We've seen mysterious errors because the compiler / linker get confused by this.

FYI, I'm working on rebuilding `go_path`, so it may be significantly different in the next release. Hopefully not too much.

**Comment by junghoahnsc** [comment]
I checked all dependencies and found that gcloud lib is using this:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/internal/protostruct/protostruct.go#L19

Is there any way to remap import when a third-party lib is using `@com_github_golang_protobuf` like this?

If not, it won't be possible to avoid this conflict.

**Comment by jayconrod** [comment]
Interesting. I assume you're importing `google-cloud-go` with `go_repository`? Gazelle will generate a `go_library` for this directory that depends on `@com_github_golang_protobuf` because of that import. 

Gazelle suppresses proto imports of WKTs when generating `go_proto_library` rule. It should map regular Go imports to the rules in `@io_bazel_rules_go`. I've filed bazelbuild/bazel-gazelle#159 to track this. This should be fixed before the next release.

**Comment by jayconrod** [comment]
Closing old issues. This should be fixed.
