### ISSUE TITLE
gp_repository is not downloading dependency 

### ISSUE THREAD

**Issue by AlexShemeshWix** [bazelbuild/rules_go#1411]
Hi
Im on
MacOS 10.13.2
Go 1.10
Bazel 0.11.1-homebre

I have repo
https://github.com/wix-playground/BazelBuildForGo
ve created branch for this issue 
https://github.com/wix-playground/BazelBuildForGo/tree/extentaldeps

It contains 2 projects . project1 and project2.
project1 uses coreos/etcd.

Ive defined dependency for project 1 in WORKSPACE 

```
go_repository(
    name = "com_github_coreos_etcd_client",
    commit = "f5c56401d74401f040258afeb5fbdd875fafaf69",
    importpath = "github.com/coreos/etcd",
)
```

and i reference it later on in project1/BUILD.bazel

```
go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/wix-private/BazelBuildForGo/project1",
    visibility = ["//visibility:private"],
    deps = [
        "//project1/p1lib:go_default_library",
        "@com_github_coreos_etcd_client//client:go_default_library",
    ],
)

```

It suppose to fetch coreos/etcd package and run gazelle for it to generate BUILD files.

When i run 

`bazel build //project1:project1`

I get error 

```
ERROR: /Users/user1/dev/go/src/github.com/wix-private/BazelBuildForGo/project1/BUILD.bazel:3:1: no such package '@com_github_coreos_etcd_client//client': BUILD file not found on package path and referenced by '//project1:go_default_library'
ERROR: Analysis of target '//project1:project1' failed; build aborted: Loading failed
INFO: Elapsed time: 0.274s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

What am i doing wrong and where my dependencies suppose to be downloaded to?
Thanks

**Comment by jayconrod** [comment]
I cloned this project and checked out this branch. `bazel build //project1:project1` works for me. It looks like you're doing everything correctly. Are there any local changes might not be checked in?

You can fetch an external repository manually `bazel fetch @com_github_coreos_etcd_client//...`. That will force Bazel to download the repo and run Gazelle. You can look inside Bazel's cache directory to see where it checks out the repository (`bazel-out` and other symlinks point inside the directory). For me, it gets fetched to `/usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/e50452befd29566078d4e7629b64d9ab/external/com_github_coreos_etcd_client`.

**Comment by AlexShemeshWix** [comment]
Hi.
If i do bazel fetch @com_github_coreos_etcd_client//...
it gives me error

ERROR: /private/var/tmp/_bazel_alexshe/df78026a5ee0c7ed3d23dd05c3a3b1
f7/external/com_github_coreos_etcd_client/BUILD:7:9: invalid character: '$'
ERROR: /private/var/tmp/_bazel_alexshe/df78026a5ee0c7ed3d23dd05c3a3b1
f7/external/com_github_coreos_etcd_client/BUILD:8:7: invalid character: '!'
ERROR: /private/var/tmp/_bazel_alexshe/df78026a5ee0c7ed3d23dd05c3a3b1
f7/external/com_github_coreos_etcd_client/BUILD:8:34: Tabulations are not
allowed for identation. Use spaces instead.
ERROR: /private/var/tmp/_bazel_alexshe/df78026a5ee0c7ed3d23dd05c3a3b1
f7/external/com_github_coreos_etcd_client/BUILD:18:31: invalid character:
'&'
ERROR: /private/var/tmp/_bazel_alexshe/df78026a5ee0c7ed3d23dd05c3a3b1
f7/external/com_github_coreos_etcd_client/BUILD:28:4: invalid character: '$'


How can i configure gazelle to always use BUILD.bazel file?

Another question is how do i  write rule in BUILD file for gazelle to use
"-build_file_name BUILD.bazel" parameter?

gazelle(
    name = "gazelle",
    command = "fix",
    extra_args = [
        "-build_file_name",
        "BUILD.bazel",
    ],
    prefix = "github.com/wix-private/BazelBuildForGo",
)


is not working.
Thanks

**Comment by jayconrod** [comment]
Ah, this makes more sense. github.com/coreos/etcd has bash scripts named `build` that Bazel and `go_repository` are interpreting as build files. I wasn't seeing this error because my workstation has a case sensitive file system.

In general, Bazel will look for both `BUILD.bazel` and `BUILD`; it will prefer `BUILD.bazel` if both are present.

`go_repository` by default will only run Gazelle if neither `BUILD.bazel` nor `BUILD` are present. You can force it to ignore `BUILD` files and run Gazelle by setting `build_file_name = "BUILD.bazel"` and `build_file_generation = "on"` like this:

```
go_repository(
    name = "com_github_coreos_etcd_client",
    build_file_generation = "on",
    build_file_name = "BUILD.bazel",
    commit = "f5c56401d74401f040258afeb5fbdd875fafaf69",
    importpath = "github.com/coreos/etcd",
)
```

It looks like there are directories that contain `build` scripts that don't have .go files. Gazelle won't generate BUILD.bazel files in those directories, so a `bazel fetch` on the whole repo will break because of that. You can still fetch, build, and depend on individual targets though. For example, `bazel build @com_github_coreos_etcd_client//pkg/flags:go_default_library`.

---

To answer your second question, the [`gazelle` rule](https://github.com/bazelbuild/bazel-gazelle#bazel-rule-1) has a small number of configuration parameters. Most configuration is done via [directives](https://github.com/bazelbuild/bazel-gazelle#directives), which are comments written in build files. Directives are more powerful than attributes and command line arguments, since they can apply in specific build files and subtrees.

So you can write this:

```
# gazelle:prefix github.com/wix-private/BazelBuildForGo
# gazelle:build_file_name BUILD.bazel
gazelle(
    name = "gazelle",
    command = "fix",
)
```

**Comment by AlexShemeshWix** [comment]
Thanks for your help
Ive merged all changes to master.
Ive also implemented packaging binaries to tar and creating docker image.
https://github.com/wix-playground/BazelBuildForGo
