### ISSUE TITLE
go_vet_test rule

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#1459]
why does this rule have a test declared along with it?

**Comment by jayconrod** [comment]
`go_vet_test` is a macro around two rules: `_go_vet_generate` builds a bash script that runs vet, and that script is run with `sh_test`. If I remember correctly, the reason was that rules can't return bash scripts as executables for testing because Windows doesn't know how to execute them.

FYI, vet functionality will likely be rewritten in the next month or two. We're working on open sourcing a static analysis framework that can run vet and other things.

**Comment by jeb2239** [comment]
what if I made a go binary wrapper around go vet? it should be able to return that right?

**Comment by jayconrod** [comment]
Sure, that would work. Though I suspect the command we're issuing is simple enough that we don't need a wrapper at all.

**Comment by jeb2239** [comment]
```
load("@io_bazel_rules_go//go:def.bzl", "gazelle", "go_library", "go_path", "go_test", "go_vet_test")

go_library(
    name = "go_default_library",
    srcs = ["lib.go"],
    importpath = "distributedbuspoc/mylib",
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["lib_test.go"],
    #deps=[":go_default_library"],
    embed = [":go_default_library"],
)

genrule(
    name = "coverage_gdt",
    srcs = ["lib_test.go"],
    outs = ["coverage.dat"],
    cmd = "$(location :go_default_test) --test.coverprofile coverage.dat",
    tools = [":go_default_test"],
)

```

I was wondering if I could do something like this.

**Comment by jayconrod** [comment]
I figured. Seems like it might work. You'll need to pass some extra flags to `bazel build` to enable coverage instrumentation on certain libraries. It might not work for tests that require data files, and maybe not with race / msan / cross compilation / other modes.

Since there hasn't been much progress on coverage aggregation or reporting within Bazel core, I've been thinking about building a (temporary) tool for running a collection of tests, combining their data, then generating a coverage report from that. That would probably come later this quarter or early next quarter. Not sure you want to wait, I know it's an urgent issue for you.

We're making progress on getting vet and other static analysis running. #1487 is a big step toward that.

**Comment by jeb2239** [comment]
```
genrule(
  name ="generate_swagger",
  srcs=[
    ":go_default_library",
    ":swagger_path",
    "@go_sdk//:files"
  ],
  local=1,
  outs=["swagger.json"],
  cmd = "export CGO_ENABLED=1; export GOROOT=/home/barriosj/go ;export GOPATH=$(location :swagger_path); $(location //cmd/swagger) generate spec -b github.com/go-swagger/go-swagger/fixtures/goparsing/petstore/rest  > $@",
  tools = ["//cmd/swagger","@go_sdk//:tools"]
)
```

Another thing I am having trouble with is accessing go information via a gen rule. Do you know a good way to do this?

**Comment by jayconrod** [comment]
We store a decent amount of Go metadata in [providers](https://github.com/bazelbuild/rules_go/blob/master/go/providers.rst). Basically everything that you can find out during analysis (without actually opening source files) is in there.

Genrules can't directly consume providers. If you need the information during analysis, you'll need to write a Bazel rule and execute the genrule command as an action. If you only need the information during execution, you might be able to write a small rule that writes provider information to a json file or something, then consume that file as a source.

You may be interested in Kubernetes' [`go_genrule`](https://github.com/kubernetes/repo-infra/blob/master/defs/go.bzl), which was very recently rewritten to use `go_path`.
