### ISSUE TITLE
go_path busted on duplicate vendored deps

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#1509]
go_path, with the latest rules_go ca213b3006c8eed6b3f1ea649cab36b817901b46 and with 0.12.0, breaks on duplicate vendored dependencies that are depended on by different packages. I'm not sure how to fix this.

Do you have any ideas how to make this work now? The go_path code is from https://github.com/jmhodges/bazel_gomock/blob/master/gomock.bzl

```
ERROR: /Users/jmhodges/founding/src/founding/go/svc/howsmyssl-billing/BUILD:190:1: in go_path rule //go/svc/howsmyssl-billing:stripe_mock_gomock_gopath: 
Traceback (most recent call last):
	File "/Users/jmhodges/founding/src/founding/go/svc/howsmyssl-billing/BUILD", line 190
		go_path(name = 'stripe_mock_gomock_gopath')
	File "/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/io_bazel_rules_go/go/private/tools/path.bzl", line 72, in _go_path_impl
		_add_manifest_entry(manifest_entries, manifest_entry_m..., <3 more arguments>)
	File "/private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/external/io_bazel_rules_go/go/private/tools/path.bzl", line 174, in _add_manifest_entry
		fail("{}: references multiple files (...))
src/vendor/github.com/gogo/protobuf/proto/clone.go: references multiple files (external/io_k8s_api/vendor/github.com/gogo/protobuf/proto/clone.go and external/io_k8s_apimachinery/vendor/github.com/gogo/protobuf/proto/clone.go)
```

**Comment by jayconrod** [comment]
I've been thinking about how to fix this. There are a couple `go_path` bugs related to vendoring. The issue is that we don't really know in which "repository" vendored packages should be written to within the output directory. We try to infer everything from `importpath` and `importmap` which is a little lossy.

Gazelle does write external repository names into `importmap` attributes in vendored packages. So if we assume standard naming conventions are followed, we can get very close. It may not be 100% accurate though.

**Comment by jayconrod** [comment]
I came up with a "fix" for this, but it was complicated and error-prone. I think it's actually better to have Gazelle set `importmap` to the location where files should be placed in `go_path`. This will result in some amount of build file churn unfortunately, but I think it's a better solution in the long run.

**Comment by jmhodges** [comment]
I’m up for it
