### ISSUE TITLE
os.Getwd("PWD") and os.Getwd() don't match expectation and spec

### ISSUE THREAD

**Issue by dape-wg2** [bazelbuild/rules_go#1561]
The bazel test encyclopedia defines the working directory of the test as:

> The initial working directory shall be $TEST_SRCDIR/$TEST_WORKSPACE.

But as this tiny test shows it doesn't work as defined
```golang
func TestBrokenGetwd(t *testing.T) {
	// Bazel test encyclopedia state that the initial working
	// dir of the test should be $TEST_SRCDIR/$TEST_WORKSPACE.
	//
	// https://docs.bazel.build/versions/master/test-encyclopedia.html
	//
	// However, as this test shows, this is not true...

	wd, _ := os.Getwd()
	pwd := os.Getenv("PWD")
	spec := os.Getenv("TEST_SRCDIR") + "/" + os.Getenv("TEST_WORKSPACE")

	//...the os.Getwd() returns the wrong working directory...
	if wd != spec {
		t.Errorf("wrong working dir; got:%q want:%q", wd, spec)
	}

	//...but the PWD environment variable is correct.
	if pwd != spec {
		t.Errorf("wrong working dir; got:%q want:%q", pwd, spec)
	}
}
```

My guess is that this is a problem in the os.Getwd() implementation but since it surfaces in bazel I file the bug here (to minimize the risk of a "working as intended" answer)

**Comment by jayconrod** [comment]
There are some conflicting requirements here. Many Go tests that were written with the intention of running under `go test` assume that they are run in the package directory. If we followed the Bazel convention exactly, we would break basically every test out there. So instead, when a `go_test` executable starts, we switch to the package directory (actually an equivalent directory in the sandbox) so that tests can find their data files.

We do have an escape hatch: if you want a test to run in a specific directory, you can set `rundir = "path/to/dir"`. That accepts a path relative to the repository root directory, so if you want a test to run in the root directory, use `rundir = "."`.

I've pushed #1563 which sets `PWD` to the current directory in the generated test code. `os.Getwd` doesn't set this automatically (I think it's mostly only important for shells). However, `go test` does set it, so we should, too.

**Comment by dape-wg2** [comment]
Thanks; rundir = "." allow me to remove my workaround (using os.Getenv("PWD") insead of os.Getwd()).
As someone with 9+ years of blaze experience this behavior took me a bit by surprise; but I guess I'm the "odd one" in this case :)

Thanks!
