### ISSUE TITLE
Keep supporting Go 1.8, at least until Appengine has Go 1.9 out of beta

### ISSUE THREAD

**Issue by yohcop** [bazelbuild/rules_go#1567]
It's a bit sad that these rules are now incompatible with the Appengine production version of Go in the standard environment (https://cloud.google.com/appengine/docs/standard/go/runtime)

I get that it's difficult, and that packages want to move on, but the software development story is broken otherwise.

And I needed to update rules_go because other rules (typescript) depend on a newer version of this package.

Thanks,

**Comment by jayconrod** [comment]
Go 1.8 is no longer supported by the Go developers. I've made Go 1.9 the minimum version in master so that we can switch to invoking the compiler and linker with importcfg files. This will reduce overhead and will reduce errors related to command line length limits.

There's no released version of rules_go that has dropped support for Go 1.8 though. Older branches of rules_go are still supported and are receiving updates, and Go 1.8 support won't be going away there. I expect to support the 0.12 branch for several more months at least.

Could you elaborate on the TypeScript dependency? Are they migrating to a specific recent version of rules_go? The boilerplate in their README file uses 0.8.1. Their WORKSPACE file uses 0.10.3.

**Comment by yohcop** [comment]
Sorry, you are right. Somehow I must have tried at head, thinking at was using 0.12. But 0.12 still has Go 1.8.

Regarding rules_typescript. I was a bit in dependency hell, and I have not solved all the issues just yet. But I updated rules_typescript on my project in order to use rules_webtesting actually. And it's rules_webtesting that's the repo that forced me to update rules_go (their README mentions head, but their WORKSPACE has 0.12). I now also have to update the proto rules, and other things.

Thanks for the response,

**Comment by jayconrod** [comment]
Sorry about the dependency hell. There have been a number of breaking changes in the last couple rules_go releases as we remove some long-deprecated functionality. I expect we'll be more stable in the future.

I'll close this issue now. Let me know if you run into any other problems with rules_go.

**Comment by yohcop** [comment]
Literally 2 days later, Go 1.9 is the default on Appengine :)
https://cloud.google.com/appengine/docs/standard/go/release-notes
