### ISSUE TITLE
Add appengine platform, or document how to build with custom go tags.

### ISSUE THREAD

**Issue by yohcop** [bazelbuild/rules_go#1573]
Maybe this already exists and I couldn't find it.
The [third_party/com_github_golang_protobuf/proto/BUILD.bazel.in](https://github.com/bazelbuild/rules_go/blob/master/third_party/com_github_golang_protobuf/proto/BUILD.bazel.in) file does not include [pointer_reflect.go](https://github.com/golang/protobuf/blob/master/proto/pointer_unsafe.go#L32), which is necessary for building/using protos on appengine. I am guessing this is first a bug/missing feature with Gazelle.

To bypass this first bug, I tried overriding the BUILD.bazel.in file with an overlay (like the third_party files in this repo), adding pointer_reflect.go to the list of sources. But when building, the file is still ignored. Probably for the same reason it doesn't appear in the BUILD file in the first place: it has the [+build tags](https://github.com/golang/protobuf/blob/master/proto/pointer_unsafe.go#L32):

`// +build !purego,!appengine,!js`

I think I would need a --platform=@io_bazel_rules_go//go/platform:appengine or something like that? I tried the simple thing of defining one in [list.bzl](https://github.com/bazelbuild/rules_go/blob/master/go/platform/list.bzl) but that created a dependency loop (hu?)

```
> bazel run :tree --fetch --platforms=@io_bazel_rules_go//go/platform:appengine
Starting local Bazel server and connecting to it...
.
ERROR: /home/y/.cache/bazel/_bazel_y/353cc7731d9fb1ef948c81259e5d7654/external/io_bazel_rules_go/go/platform/BUILD.bazel:12:1: in config_setting rule @io_bazel_rules_go//go/platform:appengine: cycle in dependency graph:
    //:tree
.-> @io_bazel_rules_go//go/platform:appengine [self-edge]
`--
This cycle occurred because of a configuration option
```

Any help would be appreciated!

p.s. The long fix is to overlay a bunch of files from this repo, to propagate a change removing the +build tags from pointer_reflect.go. I would override [third_party/manifest.bzl](https://github.com/bazelbuild/rules_go/blob/master/third_party/manifest.bzl) to add an overlay of pointer_reflect.go, fork a pointer_reflect.go file without the +build tag, and override the aforementioned BUILD.bazel.in too. All this is going to be brittle.

Thanks

**Comment by jayconrod** [comment]
pointer_reflect.go has the build tags:

```
// +build purego appengine js
```

So at least one of those needs to be set in order to build it. In Gazelle, you can set build tags with `-build_tags=appengine`. That won't help you with the overlay repository rule though; manually adding the source to the rule is fine in this case. When you go to build with Bazel, you can set build tags with `bazel build --define=gotags=appengine`.

I'm not sure that will get you all the way there though. Last I heard, in order to build Go for AppEngine, you had to build against a special version of the standard library. And when you "build" a program, you're actually packaging up source files and sending them to AppEngine to compile with a special sandboxing toolchain. I *think* that is no longer true with AppEngine Flex, but I don't know much about that.

**Comment by yohcop** [comment]
Thanks, that was helpful.

Actually your message made me realize that I didn't need to override pointer_reflect.go. I just needed to include it in the srcs of the relevant BUILD rule. The rest (selecting appengine tag, and the right source file) is taken care of later by the dev server and the compilation by the appengine service.

I have a custom BUILD rule that packages all the transitive dependencies of the "main" go package, and transitive data dependencies, in a form that the Appengine dev server, as well as the upload functionality, works. That's for Appengine Standard environment. All I needed was to get the right set of sources, and I was missing this pointer_reflect.go file. But I also build the project locally, with standard go_library, mostly for testing. Which is why I opened a bug regarding Go 1.8 the other day. And then, literally 2 days ago, Go 1.9 was launched out of beta.... :)

By the way, any intention to have the overlay functionality available in plain bazel, or in bazel tools? This way I (we) can stop duplicating those rules in various projects? [In gazelle](https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/overlay_repository.bzl), [in rules_go](https://github.com/bazelbuild/rules_go/blob/master/go/private/tools/overlay_repository.bzl)

**Comment by yohcop** [comment]
And I found the doc for Gazelle, regarding build_tags. I was looking in the wrong place, so closing this.
Thanks,

**Comment by jayconrod** [comment]
> By the way, any intention to have the overlay functionality available in plain bazel, or in bazel tools?

Not quite, but you may find the patch functionality in the Skylark `git_repository` and `http_archive` to be useful. See https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L106. Basically, you can give it a list of patch files to apply after checking out the repo. Those rules are in `@bazel_tools//tools/build_defs/repo:http.bzl` and `git.bzl`. They're the official replacements for the native versions.

I suppose they make my overlay rules somewhat redundant, but I still prefer to maintain build files as files instead of patches.

**Comment by yohcop** [comment]
Thanks for the tip. Yes, I prefer plain files to diffs too.
