### ISSUE TITLE
Argument list too long linking on mac

### ISSUE THREAD

**Issue by BenTheElder** [bazelbuild/rules_go#1637]
On kubernetes master branch `bazel build //test/e2e:e2e.test` fails with:

`Action failed to execute: java.io.IOException: Cannot run program "/usr/bin/sandbox-exec" (in directory "/private/var/tmp/_bazel_bentheelder/c99a7ed2e9dbc7676356495197988838/sandbox/darwin-sandbox/1/execroot/__main__"): error=7, Argument list too long`

(above this is a massive command line with lots of args like `-dep '//staging/src/k8s.io/apimachinery/pkg/api/meta/table:go_default_library=k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/meta/table=bazel-out/darwin-fastbuild/bin/staging/src/k8s.io/apimachinery/pkg/api/meta/table/darwin_amd64_stripped/go_default_library~/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/meta/table.a'`

It looks like this is a massive link option, which become to large after updating to rules go 0.12

`1ad1c8c7f8` `Merge pull request #64122 from ixdy/update-rules_go-and-gazelle` seems to be the breaking point.

/cc @ixdy 

reported by @spiffxp

**Comment by ixdy** [comment]
oh, looking at that command line snippet, I bet it wasn't updating to rules_go 0.12 so much as adding an importmap on everything under `staging/src/` (https://github.com/kubernetes/kubernetes/pull/64122/commits/b42e9125c45dc26a2a713cb47f16363f171eb9d7)

**Comment by jayconrod** [comment]
Looks like we'll need to switch to `-importcfg` files sooner rather than later.

Will you need the fix for this backported to older release branches (e.g., 0.12), or is it okay for it to just be on 0.14? The fix will require the SDK to provide more information to the compiler than it currently does, so backporting will be non-trivial.

Also, do you need the fix to support Go 1.8 or older? The feature that would fix this is in Go 1.9. Go 1.8 would require a very different solution.

**Comment by ixdy** [comment]
rules_go 0.14 should be fine. I don't think there's anything blocking us from updating besides time.

The oldest version of Go we're using is 1.9, but that's also on a branch that's using a much older version of rules_go. The only branch encountering this issue is using go 1.10.3.

**Comment by spiffxp** [comment]
thanks for filing @BenTheElder I completely forgot this morning

https://gist.github.com/spiffxp/ef70004a6179fd4bf3efa720f111b038 if you want to see the actual command that failed

otherwise, yes, what @ixdy said

**Comment by BenTheElder** [comment]
Thanks @jayconrod !

**Comment by jayconrod** [comment]
FYI @BenTheElder @ixdy @spiffxp Please try with `master` and reopen if you're still having issues with the command line being too long. We might still get long command lines with C/C++ compile / link actions. Also, there may still be paths that are too long on macOS and Windows.

I think I'd like to tag a major release (0.15.0) with this soon (this week) rather than backport it to an older release branch. Let me know if that doesn't work for you. That may require Bazel 0.16.0 as a minimum supported version because of #1550, but that probably won't matter unless you're building for arm64.
