### ISSUE TITLE
Can't use descriptor.proto with go_proto_llibrary

### ISSUE THREAD

**Issue by yohcop** [bazelbuild/rules_go#165]
In order to use extensions on fields, messages, etc, I have to import google/protobuf/descriptor.proto. However the import fails. I tried various things, looking at the BUILD files in external/, but could find something that worked. Any idea? Or is it something missing?

```
% cat lib/BUILD 
load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")
go_proto_library(
    name = "foo_proto",
    srcs = [
        "foo.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
```
```
% cat lib/foo.proto 
syntax = "proto3";

package cmd;

import "google/protobuf/descriptor.proto";

message ServiceOptions {
  string opts = 1;
}
message MethodOptions {
  string opts = 1;
}

extend google.protobuf.ServiceOptions {
  ServiceOptions Service = 7791;
}
extend google.protobuf.MethodOptions {
  MethodOptions Method = 7792;
}
```
```
% bazel build lib:foo_proto
INFO: Found 1 target...
ERROR: /xxxx/lib/BUILD:11:1: Generating into bazel-out/local-fastbuild/bin/lib/foo_proto failed: linux-sandbox failed: error executing command /xxxx/.cache/bazel/_bazel_y/1129aeaeb86f4311cfe08c57d10b52b4/execroot/go-bzl/_bin/linux-sandbox ... (remaining 6 argument(s) skipped).
google/protobuf/descriptor.proto: File not found.
lib/foo.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
Target //lib:foo_proto failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.259s, Critical Path: 0.07s
```

Thanks,

**Comment by pmbethe09** [comment]
If you want descriptor.proto, you can get it at:
google.golang.org/genproto/protobuf

**Comment by pmbethe09** [comment]
well, all dependencies in bazel must be declared.  So the
go_proto_library(name = "foo_proto", ...)

Needs to depend on something that provides descriptor.proto, as here when
protoc is run in a sandbox, only foo.proto is visible.

**Comment by yohcop** [comment]
Yeah, I guess there were a couple of problems, maybe only 1 of them related to this repo actually.

First, I somehow thought that descriptor.proto would be a "well known proto", that should be included magically, but that's not the case. so my mistake. But I actually did try to find a go_proto_library target that would provide descriptor.proto. This brings me to my second problem.

descriptor.proto is not distributed with https://github.com/golang/protobuf/. I don't know why, since other well-know types/protos are distributed. This seems kind of a shared issue between repos, because this repo will generate targets for ptypes/duration.proto for example, but nothing for descriptor.proto (since it's not in the dependent proto).

So I can do (from the doc):
```
go_proto_library(
  name = "my_proto",
  srcs = ["my.proto"],
  deps = [
    ":other_proto",
    "@com_github_golang_protobuf//ptypes/duration:go_default_library",
  ],
)
```

but there is no `@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library` for example.

Alternatively, this package depends on `@com_github_google_protobuf`, which also has a `descriptor.proto`, in a `filegroup` called `well_known_protos`. But there are no `go_proto_library` for this either.

I didn't know however about google.golang.org/genproto/protobuf. Why is it yet another package?

So I think this package, or one of the other two mentioned should be able to provide a ":descriptor_proto" target.

I can copy descriptor.proto myself, and create the related BUILD file, but it sounds like it should be in the distribution. (And then I ran into issue #173).

Thanks for answering anyway.

**Comment by pcj** [comment]
Hi @yohcop you can also try the `go_proto_library` rule in [rules_protobuf](https://github.com/pubref/rules_protobuf).  It supports subdirectories and the well-known protos.  You can refer to the test/example:

https://github.com/pubref/rules_protobuf/blob/master/examples/wkt/go/BUILD

**Comment by pmbethe09** [comment]
Yeah, I found the same issue in @com_github_golang_protobuf//
protoc-gen-go/descriptor
and the simplest thing should be to add the descriptor.proto to that
directory, although your .proto will not work for languages other than Go
(which is annoying).  As it will use 'import
"protoc-gen-go/descriptor/descriptor.proto";' instead of the familiar
'import "google/protobuf/descriptor.proto";'

And similarly google.golang.org/genproto
<http://google.golang.org/genproto/protobuf> would be 'import
"protobuf/descriptor.proto";' which is also unsatisfactory.

I suppose the ugly but compatible thing to do would be to create your own
google/protobuf directory, and then use a genrule to copy the well-known
.proto into the directory, and then go_proto_library

**Comment by pmbethe09** [comment]
@pcj that importmap is a nice feature.

**Comment by yohcop** [comment]
Any thoughts on potentially merging the two projects/efforts? This bazelbuild/rules_go repo seems more "official" than the pubref/ one, and pubref/ supports every languages ever ;).
Maybe the go_proto_library doesn't have to be bundled with other rules_go or other languages, and a new `bazelbuild/goproto` could unify both efforts?

**Comment by pmbethe09** [comment]
What @pcj has at pubref looks pretty useful.

However, some internal developers at Google wanted a just a
go_proto_library for bazel which was part of rules_go.
As such this go_proto_library addresses all of our internal needs,
including a matching syntax to other internal stuff  (using srcs and
has_services rather than pubref's protos and with_grpc)
Note: rules_go is not officially supported by the Go team, but they are
aware of us, and our maintainers are a couple of current and former
Googlers.
