### ISSUE TITLE
Update github.com/google/go-genproto

### ISSUE THREAD

**Issue by doroginin** [bazelbuild/rules_go#1656]
Please update github.com/google/go-genproto to the latest revision
https://github.com/bazelbuild/rules_go/blob/c73c25f2ead2b6d2cf772878e88a650f07a3de7c/go/private/repositories.bzl#L141

In https://github.com/grpc-ecosystem/grpc-gateway/pull/712 project we need this https://github.com/google/go-genproto/commit/383e8b2c3b9e36c4076b235b32537292176bae20 version.

**Comment by achew22** [comment]
Would it also be possible to make a knob to control the version or is it better for us to explicitly list our dependencies?

**Comment by jayconrod** [comment]
@doroginin I'll update this today. I'll likely do another major release (0.15.0) this week because there's some other stuff I want to ship.

@achew22 It's better to explicitly list dependencies. In cases where you need to override a version, you can write the rule *before* the call to `go_rules_dependencies()`. I just wrote up an example of this: [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies).

If you're providing a similar macro for grpc-gateway, it may get confusing for users very quickly though. Bazel's working on recursive WORKSPACE evaluation, but it may be some time before that's ready.
