### ISSUE TITLE
github.com/golang/protobuf/ptypes is declared by rules_go and com_github_golang_protobuf

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#1674]
This makes the `go_path` rule fail with the following error:
```
Traceback (most recent call last):
	File "/Users/steeve/go/src/github.com/znly/zenly-client-core/BUILD.bazel", line 58
		go_path(name = 'core.gopath')
	File "/private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/external/io_bazel_rules_go/go/private/tools/path.bzl", line 74, in _go_path_impl
		_add_manifest_entry(manifest_entries, manifest_entry_m..., <3 more arguments>)
	File "/private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/external/io_bazel_rules_go/go/private/tools/path.bzl", line 193, in _add_manifest_entry
		fail("{}: references multiple files (...))
src/github.com/golang/protobuf/ptypes/duration/duration.pb.go: references multiple files (bazel-out/ios_arm64-fastbuild/bin/external/io_bazel_rules_go/proto/wkt/darwin_arm64_pure_stripped/duration_go_proto%/github.com/golang/protobuf/ptypes/duration/duration.pb.go and external/com_github_golang_protobuf/ptypes/duration/duration.pb.go)
```

**Comment by jayconrod** [comment]
This error is happening because both `@io_bazel_rules_go//proto/wkt:duration_go_proto` and `@com_github_golang_protobuf//ptypes/duration:go_default_library` are dependencies of the `go_path`. They are not compatible, since they are logically the same library built in different ways (one is built from a .proto, one is built from checked-in .pb.go files).

You can get the chain of dependencies with:

```
$ bazel query 'somepath(//zenly-client-core:core.gopath, @io_bazel_rules_go//proto/wkt:duration_go_proto)'
$ bazel query 'somepath(//zenly-client-core:core.gopath, @com_github_golang_protobuf//ptypes/duration:go_default_library)'
```

[Avoiding Conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) has more information about this. I'm happy to answer any questions, too (and amend the documentation if it would be helpful).

**Comment by steeve** [comment]
Awesome! Indeed it was because of legacy rules (probably generated by an older Gazelle version). All good!
