### ISSUE TITLE
rules_go's use of special customized overlays for some external libraries prevents users from managing those library versions

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/rules_go#1683]
I've hit this same issue with multiple external libraries (protobuf, grpc, bindata, and previously toml before Gazelle got extracted). In short, the use of "standard" Gazelle-ified paths in [go/private/repositories.bzl](https://github.com/bazelbuild/rules_go/blob/0.15.0/go/private/repositories.bzl) makes life extremely hard for users that want to manage the versions of these libraries themselves. In the current situation we can't pull them in with `go_repository`, and can't vendor them, because rules_go assumes they've got BUILD files coming from a special hand-crafted overlay instead of the standard generator.

For any libraries used by rules_go that require a custom overlay, please give them a different name (like `rules_go_internal_...`) or use `@ io_bazel_rules_go//vendor/` paths so the rules_go deps don't stomp all over the global external library namespace.

**Comment by jayconrod** [comment]
The reason we declare most of these repositories is not because rules_go itself depends on them; it's because targets built using rules_go depend on them implicitly. For example, if you use `go_proto_library` with the `go_grpc` compiler, you need `org_golang_google_grpc`, and that depends on `org_golang_x_net`.

It's important that we declare these with standard names instead of using a private vendor directory or an internal name since it's likely that users will also depend on these. If we had a private copy, it would be very hard to avoid conflicts.

For the most part, these repositories can be overridden with `go_repository`, as long as they're declared before `go_rules_dependencies()`. There are instructions at [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies). The reason we use overlays instead of `go_repository` internally is so that rules_go doesn't need to depend on Gazelle (anymore).

I think the only repos with manual modifications are `com_github_golang_protobuf` (which contains a couple extra rules for `ptypes` and similar libraries that Gazelle may reference) and `go_googleapis` (the root build file contains some directives for Gazelle). 

If you want to create your own overlay for these, you can check out the repo at your preferred version, copy rules_go's overlay there, then run Gazelle. Then you can use `git diff` to produce a .patch file that can be passed to `git_repository` or `http_archive` (use the versions  `@bazel_tools//tools/build_defs/repo`).

**Comment by jmillikin-stripe** [comment]
> It's important that we declare these with standard names instead of using a private vendor directory or an internal name since it's likely that users will also depend on these. If we had a private copy, it would be very hard to avoid conflicts.

But you're taking the standard name and using it for a non-standard definition of these repos. The presence of the rules_go overlay means that it's not possible to use either standard Bazel or Go tooling to manage e.g. the protobuf version.

**Comment by jayconrod** [comment]
`com_google_protobuf` doesn't actually have an overlay. You can override that with standard tooling.

`com_github_golang_protobuf` has a couple of extra rules for libraries like `ptypes` that depend on the WKTs. Both versions are needed in different situations. How would you want that to be different? I guess we could declare two different versions of `com_github_golang_protobuf` which could be generated with `go_repository` under different settings.

**Comment by jayconrod** [comment]
One thing that may help a bit: I've been planning to convert the overlays into .patch files and add support to Gazelle for directly updating those patch files. That would let us use the standard `git_repository` and `http_archive` (the ones in `@bazel_tools` that accept patch files) instead of the Gazelle variants that accept overlays. That would make it easier to modify and replace an overlay.

**Comment by jmillikin-stripe** [comment]
Ideally rules_go would use Gazelle's `go_repository` to define `@com_github_golang_protobuf`, with no additional overlay or patching. Changes made by rules_go to upstream sources are disruptive because the user doesn't have much choice in them.

> One thing that may help a bit: I've been planning to convert the overlays into .patch files and add support to Gazelle for directly updating those patch files.

That doesn't seem to be going in the right direction -- why does rules_go need to modify these upstream repos at all? And if there are truly settings that must be present in a `BUILD` file as if integrated into the repo, shouldn't they be merged upstream?

`github.com/golang/protobuf` includes pre-generated Go files for the built-in protobuf types, so there shouldn't any need to run `protoc` on them. From the sources present in that repo it should be possible to bootstrap `protoc`, so there's no need for the rules_go-specific overlay as a loop breaker.

**Comment by jayconrod** [comment]
Let me show you the two versions of `ptypes`.

```
go_library(
    name = "go_default_library",
    srcs = [
        "any.go",
        "doc.go",
        "duration.go",
        "timestamp.go",
    ],
    importpath = "github.com/golang/protobuf/ptypes",
    visibility = ["//visibility:public"],
    deps = [
        "//proto:go_default_library",
        "//ptypes/any:go_default_library",
        "//ptypes/duration:go_default_library",
        "//ptypes/timestamp:go_default_library",
    ],
)

go_library(
    name = "go_default_library_gen",
    srcs = [
        "any.go",
        "doc.go",
        "duration.go",
        "timestamp.go",
    ],
    importpath = "github.com/golang/protobuf/ptypes",
    visibility = ["//visibility:public"],
    deps = [
        "//proto:go_default_library",
        "@io_bazel_rules_go//proto/wkt:any_go_proto",
        "@io_bazel_rules_go//proto/wkt:duration_go_proto",
        "@io_bazel_rules_go//proto/wkt:timestamp_go_proto",
    ],
)
```

`go_default_library` depends on the pre-generated WKT libraries. People who want to generate proto code ahead of time should depend on this library. There are lots of reasons to do this: many projects need to build both with Bazel and "go build" and need .pb.go files checked in. And many protos, especially vendored protos, can't be built with Bazel because of limitations in `proto_library`.

`go_default_library_gen` depends on `go_proto_library` rules for the WKTs. People who want to generate proto code at build time should depend on this library.

There only difference between these libraries is the `deps` list. There is nothing to upstream.

Gazelle will resolve `github.com/golang/protobuf/ptypes` to one of these, depending on the proto mode.

If this repo were generated with plain `go_repository`, one of these rules wouldn't exist, and the use case that depends on it would break. It may still be possible to support both use cases by moving one of the rules somewhere else, or perhaps by providing two variants of this repository generated by Gazelle under different settings. I don't think there's a way to do this without breaking current users, and I'm not convinced the additional complexity is justified.

**Comment by jayconrod** [comment]
In our meeting today, we discussed using an internal repository for building protoc-gen-go, separate from `com_github_golang_protobuf`.

I'll look into how this would work soon. I may need to ask some follow-up questions.

**Comment by jayconrod** [comment]
Just wanted to give a quick update on this.

I did a little prototyping and found that I could get `go_proto_library` to build `protoc-gen-go` out of an internal copy of `github.com/golang/protobuf`. That would let you upgrade `com_github_golang_protobuf` separately.

However, I don't think this actually helps that much. I think the part you want to upgrade is `github.com/golang/protobuf/proto`, and that's the part that has the build file customizations that make upgrading difficult.

What I'm thinking now is that `go_repository` that should accept patches to be applied after Gazelle runs, similar to how `git_repository` and `http_archive` accept patches to apply after a repository is checked out. rules_go would have a patch checked in, and you could use that when you upgrade. So you would add something like this to your WORKSPACE:

```
go_repository(
    name = "com_github_golang_protobuf",
    importpath = "github.com/golang/protobuf",
    tag = "v1.2.0",
    build_file_proto_mode = "disable_global",
    patches = ["@io_bazel_rules_go//third_party:com_github_golang_protobuf.patch"],
)

**Comment by jayconrod** [comment]
Gazelle at `master` now has a `go_repository` that accepts patches. It accepts the same arguments as Bazel's [`git_repository`](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/git.bzl) and [`http_archive`](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl).

I've also converted `go_rules_dependencies` to use patches instead of overlays. That should make it *much* easier to distinguish the stuff generated by Gazelle from the handwritten rules.

In particular, you should be able to use the rule below to upgrade proto:

```
go_repository(
    name = "com_github_golang_protobuf",
    build_file_proto_mode = "disable_global",
    commit = "7011d38ac0d201eeddff4a4085a657c3da322d75",
    importpath = "github.com/golang/protobuf",
    patch_args = ["-p1"],
    patches = ["@io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch"],
)
```

This runs Gazelle and then applies `@io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch`, which adds a few additional rules and aliases. Note that this should be called *before* `go_rules_dependencies`.

I've updated the documentation at [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies) with more information and another example.

I'll close this issue now because I think this is about as good as we can do without introducing conflicts or breaking other projects.
