### ISSUE TITLE
nogo with vet does not respect excludes_files

### ISSUE THREAD

**Issue by arguile-** [bazelbuild/rules_go#1800]
If you register `nogo()` with vet enabled, it doesn't look like you can exclude directories -- for example `vendor/*` -- from being processed like you can with analyzer configurations.

For example:
```bazel
nogo(
    name = "nogo",
    config = "nogo.json",
    vet = True,
    visibility = ["//visibility:public"],
)
```
Would run vet on all compiled libraries, including those from vendor.

Ideally vet would respect a configuration entry for itself. Eg.
```json
{
    "vet": {
      "exclude_files": {
        "vendor/*": "third party code"
      }
    }
}
```
At least it didn't look like this was possible with a quick glance at the nogo code.

**Comment by jayconrod** [comment]
We're in the process of migrating the vet support to regular analysis passes (all of the vet analyzers have already been checked into `golang.org/x/tools/go/analysis/passes/...`). So vet will no longer be a special case.

That said, `exclude_files` only filters file names. It won't let you filter based on `importmap` or `importpath`.

@stjj89 WDYT? Is there a good way to do this, i.e., including or excluding a subgraph of dependencies? Would top-down analysis handle this and should we wait for that?

**Comment by stjj89** [comment]
> We're in the process of migrating the vet support to regular analysis passes (all of the vet analyzers have already been checked into `golang.org/x/tools/go/analysis/passes/...)`. So vet will no longer be a special case.

Yeah, I think it makes sense to wait until we switch to the vet analyzers to make vet configurable. Adding that code for that now wouldn't be worth it since it'll be discarded in a few weeks.

> That said, exclude_files only filters file names. It won't let you filter based on `importmap` or `importpath`.
>
> @stjj89 WDYT? Is there a good way to do this, i.e., including or excluding a subgraph of dependencies? Would top-down analysis handle this and should we wait for that?

I might be missing something here, but the current regular expression exemption mechanism (i.e. `"vendor/*"`) should be sufficient for OP's use case.

My plan for top-down and bottom-up analyses allows you to specify subgraphs that you want dependencies to apply to. I didn't have a subgraph exclusion mechanism in mind, but it shouldn't be hard to include that feature if we already have a way to specify a subgraph to analyze.

We might want to cross this bridge when we get there. If we're at a point where users can either globally enforce checks with filename-based exemptions or specify subgraphs to analyze, I suspect cases where we need to exclude a subgraph from checks will be rare.
