### ISSUE TITLE
Bazel (0.21.0) run gazelle keeps asking for different toolchains despite not needing them

### ISSUE THREAD

**Issue by veqryn** [bazelbuild/rules_go#1883]
I am trying to run bazel on Windows 10, and it keeps asking for different golang toolchains, even though none of them are used in my project.

Here is my bazel version:
```
PS C:\Users\xxxxxxx\workspace\go\src\github.com\ReturnPath\xxxxxxxx> bazel version
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\users\xxxxxxx\workspace\go\src\github.com\returnpath\xxxxxxxx/.bazelrc
INFO: Invocation ID: 3b454d98-9257-4815-addb-23df6de962d3
Build label: 0.21.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:16 2018 (1545224296)
Build timestamp: 1545224296
Build timestamp as int: 1545224296
```

Here is the error message:
```
PS C:\Users\xxxxxxx\workspace\go\src\github.com\ReturnPath\xxxxxxxx> bazel run //:gazelle --incompatible_remove_native_git_repository=false --incompatible_remove_native_http_archive=false
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\users\xxxxxxx\workspace\go\src\github.com\returnpath\xxxxxxxx/.bazelrc
INFO: Invocation ID: 73698559-a50d-4fdf-8ebe-ddb862a40cb0
ERROR: While resolving toolchains for target //:gazelle: invalid registered toolchain '@go_sdk//:go_linux_ppc64': Analysis failed
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.265s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Here is our WORKSPACE file:
```
SDKS = {
    "darwin_amd64": ("go1.11.4.darwin-amd64.tar.gz", "48ea987fb610894b3108ecf42e7a4fd1c1e3eabcaeb570e388c75af1f1375f80"),
    "linux_amd64": ("go1.11.4.linux-amd64.tar.gz", "fb26c30e6a04ad937bbc657a1b5bba92f80096af1e8ee6da6430c045a8db3a5b"),
    "windows_amd64": ("go1.11.4.windows-amd64.zip", "eeb20e21702f2b9469d9381df5de85e2f731b64a1f54effe196d0f7d0227fe14"),
}

load("@io_bazel_rules_go//go:def.bzl", "go_download_sdk", "go_register_toolchains", "go_rules_dependencies")

go_download_sdk(
    name = "go_sdk",
    sdks = SDKS,
)
```

We do not have `linux_ppc64` files anywhere in our project at all.

**Comment by jayconrod** [comment]
I haven't been able to reproduce this yet because my Windows machine refuses to execute downloaded binaries, and I haven't been able to update to Bazel 0.21.0. Probably needs to be reimaged.

In the mean time, a couple questions:

* Are you running Bazel with any other `--incompatible` flags? Maybe in an rc file?
* Do you see anything interesting running with `--toolchain_resolution_debug`?
* Do you see this issue if you don't use `go_download_sdk`? I don't see anything wrong there, but something to check.

About the error message, `@go_sdk//:go_linux_ppc64` is a toolchain that runs on your host system (`windows_amd64`) that can generate code for `linux_ppc64`. We declare and register toolchains for each platform the Go SDK can generate code for. These are needed for cross compilation of any kind. I don't know why Bazel would consider the toolchain invalid though. It's too bad there's not more information there.

**Comment by veqryn** [comment]
Someone else at work who knows bazel a bit better helped out and updated our rules_go to a newer version, after which this error disappeared.

I now have a different error, but I'll make a new issue for it if I can't solve it in the next few hours:
```
/bin/bash: C:/users/cduncan/_bazel_xxxxxxx/445idx3f/execroot/com_returnpath_xxxxxxxx/bazel-out/x64_windows-fastbuild/bin/gazelle.bash: No such file or directory
```
