### ISSUE TITLE
bazel resolves go imports incorrectly

### ISSUE THREAD

**Issue by jdc2172** [bazelbuild/rules_go#19]
For a simple repo structure like below, bazel fails to build when go files contain imports like `$prefix/lib1`. Instead, bazel builds only when `lib2` imports `lib1` via `$prefix/lib1/lib1`, which is erroneous when using the `go` tool to build.

```
$REPO/
 BUILD
 WORKSPACE
 lib1/
   lib1.go
   BUILD
 lib2/
   lib2_depends_on_lib1.go
   BUILD
```

The problem might stem from the `go_prefix` implementation. Quoting from `go_prefix` description:

> In Go, imports are always fully qualified with a URL, eg. github.com/user/project. Hence, a label //foo:bar  from within a Bazel workspace must be referred to as github.com/user/project/foo/bar

Which means a repo like above, if the `BUILD` file for `lib1` declares a library with name `lib1`, then importing it requires go files to use `$prefix/lib1/lib1` instead of the usual `$prefix/lib1`

**Comment by Limdi** [comment]
> if the BUILD file for lib1 declares a library with name lib1

"go_default_library" is a special target name denoting the library will be importable via 
"$go_prefix/package-path" instead of the default "$go_prefix/package-path/target-name".

I suppose it could be explained in the README or in the skylar rules incase documentation will get generated from them.

Name the library "go_default_library" in the BUILD-file for lib1 and try again.

**Comment by jdc2172** [comment]
Ah, thanks - I'll try again with that

I thought go_default_library was an example name for the library, not a
special target. I think this definitely should go in the documentation
somewhere

**Comment by yugui** [comment]
Admins, can you close this issue?
