### ISSUE TITLE
Use depsets instead of lists?

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#1922]
I may be singing to the choir here I was wondering if it would be a good idea to plan switch from lists to `depset`s in all the go rules (especially thinking about `go.sdk_files` and friends).

Especially regarding Bazel's memory consumption.

What do you think guys ?

**Comment by jayconrod** [comment]
I think we're mostly already using depsets in most situations where it makes sense to do so, specifically in the construction of `GoArchive`.

Keep in mind that depsets are expensive to construct. The Bazel implementation uniques the elements of the `direct` list and the sets of the `transitive` list during construction, even though this doesn't impact the final iteration order. It also makes a few copies of everything along the way. So basically, we'd like to avoid constructing depsets unless they can save us time at each compilation step.

The main situation depsets are useful is when we're aggregating information through a large dependency graph, especially one with a lot of cross edges (shared dependencies).

You mentioned `go.sdk_files` specifically. I think the right thing to do there is deprecate that field and remove it altogether. Actions should depend on smaller subsets of those files instead of `go.sdk_files`, which contains everything. Another optimization I've been thinking of is providing the standard library as a single .zip file input. This should reduce transfer overhead for remote execution and analysis in general. Not sure if it's a net win for the local case though.

**Comment by steeve** [comment]
Very clear jay, thank you!
