### ISSUE TITLE
Migrate bazel_test rules to go_bazel_test

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#1959]
`bazel_go_integration_test` is defined in https://github.com/bazelbuild/bazel-integration-testing, among other languages.

The framework there creates a scratch workspace (with a WORKSPACE that has `local_repository` rules already set up), then allows tests to run Bazel commands and check the results.

This is basically what `bazel_test` does. `bazel_test` is pretty ugly and difficult to modify, and I've bee thinking about a rewrite for a while. It would be better to leverage shared test infrastructure with other languages though.

**Comment by jayconrod** [comment]
Instead of migrating to `bazel_go_integration_test`, I plan to migrate these tests to `go_bazel_test`.

**Comment by gonzojive** [comment]
@jayconrod, may you please say more about the decision not to use [bazel-integration-testing](https://github.com/bazelbuild/bazel-integration-testing)?

One feature of `bazel-integration-testing` that I like is the approach to working with external repositories. Repository archives can be cached so that no network access is needed within the test of the scratch workspace. This is discussed in [import.bzl](https://github.com/bazelbuild/bazel-integration-testing/blob/165440b2dbda885f8d1ccb8d0f417e6cf8c54f17/tools/import.bzl) and [RepositoryCache.java](https://github.com/bazelbuild/bazel-integration-testing/blob/165440b2dbda885f8d1ccb8d0f417e6cf8c54f17/java/build/bazel/tests/integration/RepositoryCache.java).

I also noticed that go_bazel_test adds the "local" tag to rules, which [prevents running the test in a sandbox](https://bazel.build/reference/be/common-definitions). Presumably that means these tests don't get run as part of tools like buildkite, but I'm not sure about that.
