### ISSUE TITLE
Pain point - Getting the file name of a built go_binary

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_go#1964]
I'm in the final stretch of migrating my company's developer tooling from go cli to bazel, and I wanted to report this pain point that keeps cropping up in hopes that there's a solution I'm not seeing.

We have developers using a mix of MacOS and Linux, with a CI/CD system and production infrastructure on Linux, which I presume is the common case. A persistent pain point in writing developer tooling is getting the path to a built binary, which pops up in Makefiles, configuration files,  flag values, and deployment descriptors. Since the go_binary includes a platform-dependent string in the path (in contrast to 'go build'), I have to get the dynamic platform value in a lot of different contexts, or hard code linux if I know it's not going to be run in development.

I suppose that the rationale of the current naming is to support cross-compilation to any platform in a generic way. In practice, many of our programs use native libraries and we are not set up to cross-compile those. Developers test on their workstation, and we rely on our CI/CD system to build & test our software for production. I suspect this is the common case. 

These are the only ideas I have for making this easier:

- Write (or symlink) output binaries built for the host platform to something deterministic, using the static string "host" in place of "darwin_amd64_stripped", e.g. bazel-bin/path/to/program/HOST/program

- Similar to above, except remove the descriptive directory structure and make the last built binary bazel-bin/path/to/program, which brings it more in line with other rules. This obviously removes the ability to build multiple platforms without manually copying out each version right after you build it. I perceive that use case as a vast minority use case, and such a thing is in line with how "go build" works, so additional ceremony seems acceptable from my perspective.

- Make it easier for scripts to get the resulting program from a bazel build invocation. I believe manually parsing the textual output is the only way, which seems error-prone enough that I haven't tried that.

Any thoughts on this topic?

**Comment by Globegitter** [comment]
While I do agree that rules_go could maybe do something nicer like provide the binary also under a fixed path bazel now provides the `aquery` command to also get this kind of information in a more parseable way. So you can just do `bazel aquery //:target` and it will give you the output of all actions of that target amongst other things. See: https://blog.bazel.build/2019/02/15/introducing-aquery.html

**Comment by jayconrod** [comment]
Ah, we've had this discussion a few times before. We include configuration information in output file paths is so that builds in different configurations don't clobber each other. Originally, we didn't have this, and the cache was getting poisoned when people switched between race / non-race configurations. When split transitions are supported in the future, this will be critical for multi-configuration builds. So configuration info will continue to be part of the path.

There is an escape hatch: [go_binary](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-binary) has an `out` attribute which lets you set the output filename. When set, the output path will not include configuration info, so it's more deterministic (but Bazel adds it's own stuff like `k8-fastbuild`, and I can't do anything about that).

Bazel does provide a way to locate output files, but it's complicated. `--build_event_json_file` (or `--build_event_proto_file` if you prefer proto). This writes build event protocol messages. The `gazelle` wrapper parses this with a very kludgy regexp to find the gazelle binary. If you can rely on `jq` being available, that would make life much easier.

**Comment by robfig** [comment]
Interesting.. thank you for the context and options! aquery seems a bit heavyweight, but I'll keep that in mind. I'm surprised that output binaries having the same path is enough to poison the cache; I was under the impression the cache key contained a lot more info than that (like the flags it was built with). 

I missed the `out` attribute; it looks like that does exactly what I was asking about, thanks!
