### ISSUE TITLE
specifying custom protoc compiler

### ISSUE THREAD

**Issue by rickypai** [bazelbuild/rules_go#2018]
Hi,

I'm wondering if there's a way to specify a custom target for the `protoc` executable when generating protobuf libraries with `go_proto_library` and `go_proto_compiler`. It seems like what I want to do is be able to specify `go_protoc` in a `go_proto_compiler` target, then reference the said target in `compilers` of `go_proto_library` targets.

https://github.com/bazelbuild/rules_go/blob/f900a9e520e9fdb7b81511f9aa5de2e43da19e2a/proto/compiler.bzl#L169-L173

I'm wondering if it would be reasonable to make `_go_protoc` a publicly-overridable attribute?

Thanks a lot!

### What version of rules_go are you using?

0.18.1

### What version of gazelle are you using?

0.17.0

### What version of Bazel are you using?

0.23.2

### Does this issue reproduce with the latest releases of all the above?

blocked on 0.24.x for other reasons

### What operating system and processor architecture are you using?

darwin x64

### Any other potentially useful information about your toolchain?

we want to use a custom fork of `protoc`

**Comment by jayconrod** [comment]
Yes, this is possible, but not with `go_proto_compiler`. You'll need to write a new rule that provides `GoProtoCompiler`. The important part of this is the `compile` field, which generates actions for a `go_proto_library`.

Alternative `protoc` executables are likely to work differently than `protoc` (e.g., they might accept different sets of parameters), so I don't think it makes sense to make this configurable in `go_proto_compiler`.

**Comment by rickypai** [comment]
thank you! i will give this a try

**Comment by robbertvanginkel** [comment]
I've found this issue because I was trying to override the `protoc` executable using bazel's [`--proto_compiler`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--proto_compiler) flag:
```
--proto_compiler=<a build target label> default: "@com_google_protobuf//:protoc"
The label of the proto-compiler. 
Tags: affects_outputs, loading_and_analysis
```
and changes to that flag do not seem to be picked up with rules_go, which provides its own default, not looking at bazel's provided setting, without option to override a few lines below the snippet suggested above in https://github.com/bazelbuild/rules_go/blob/f900a9e520e9fdb7b81511f9aa5de2e43da19e2a/proto/compiler.bzl#L174-L178

The reason I'm trying to provide an alternative protoc compiler is to have users use precompiled `protoc` binaries rather than having users compile protoc from source. This seems like a reasonable use case to me and I'd expect rules_go to be able to use the proto_compiler set by the bazel flag.

**Comment by jayconrod** [comment]
As far as I know, `--proto_compiler` is not exposed to Starlark rules. If Bazel provides a way to set the proto compiler that's exposed to Starlark rules, I'd be happy to use that. [Toolchains](https://docs.bazel.build/versions/master/toolchains.html) would probably be the right way to do it, but some work would need to be done in Bazel core to make that happen.
