### ISSUE TITLE
Advice requested: workflow for local modifications to dependency

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_go#2021]
I often dive into dependency code and add prints to understand what's going on or diagnose problems. That was super easy with GOPATH, and not too hard with modules (using a replace directive). I don't see any good way to do this with `go_repository`, and I wanted to ask if there was a workflow I'm missing, or if you were open to a pull request adding one.

## Detailed workflow

Today I start with a definition generated by Gazelle like this:
```
go_repository(
    name = "com_github_qri_io_jsonschema",
    importpath = "github.com/qri-io/jsonschema",
    sum = "h1:03fNJCjKOTPGT0T40hX2UQ3nwq0Zqsl3wFgGwKjtUp4=",
    version = "v0.0.0-20190304170034-8d0aab861541",
)
```

To hack on it, I create a fork in the Github UI, change the definition to reference my fork, push each change to it, and update the commit to latest:
```
go_repository(
    name = "com_github_qri_io_jsonschema",
    importpath = "github.com/qri-io/jsonschema",
    commit = "e692c7183c262489f869a9b4e6563e9709b80d3b",
    remote = "git@github.com:robfig/jsonschema.git",
    vcs = "git",
)
```

I think this is too laborious. In other cases I would use `local_repository`, but here I need `go_repository` so that Gazelle does its magic. 

Assuming there's no easier way, would you be open to a feature like this?
```
go_repository(
    name = "com_github_qri_io_jsonschema",
    importpath = "github.com/qri-io/jsonschema",
    local_path = "/Users/robfig/jsonschema",
)
```

(I'm assuming that's easy to implement, but I really have no idea)

Thanks again!
Rob

**Comment by jayconrod** [comment]
Personally, I'm pretty happy with checking out a repo, pointing to it with `local_repository`, and re-running Gazelle when things change, but yeah, I can see how it's a little tedious.

A `go_local_repository` rule has been proposed in the past. I think that would be handy for your use case, but it's tricky to implement. Repository rules are basically Starlark functions that execute shell commands to populate an empty directory tree. So this would build a symlink tree from a source directory, then use Gazelle to generate build files in that tree.

The problem is it's not obvious when the repo rule should be re-evaluated. If it's not re-evaluated, you'll have a symlink tree that doesn't include new files or does include deleted files. Rules are re-evaluated when their attributes change or one of the files referenced by labels they resolve change. But you can't resolve labels for files that don't exist yet. There is a `local` attribute that forces the rule to be re-evaluated on every build, but that seems prohibitively expensive to me. Maybe it would be okay for small repos.

The main reason I haven't implemented this though is that I expect people would point it toward vendor subdirectories in their own repos. The aliasing there is a level of complication I haven't been willing to deal with.

**Comment by Globegitter** [comment]
Could also having support for replace help here: https://github.com/bazelbuild/bazel-gazelle/issues/488?

**Comment by jayconrod** [comment]
@Globegitter It probably wouldn't help in this situation. We won't support file system replace directives for the reasons above. We'll support module replace directives, which will let you retrieve a soft fork of a module (e.g., your own fork while you are waiting for a PR to merge upstream).

**Comment by achew22** [comment]
To toss another idea out there, I often use `--override_repository` to achieve this.

```
  --override_repository (an equals-separated mapping of repository name to path; may be used multiple times)
```

Ex:

```
bazel build --override_repository=io_bazel_rules_go=/home/achew/Projects/rules_go //...
```

To locally modify rules_go and see the impact of the change in my repo. It isn't exactly ergonomic for golang based stuff, but it isn't too hard to invoke gazelle in the other repo and then it works.

**Comment by robfig** [comment]
This is helpful, thanks. I'll try local_repository and running gazelle manually. That sounds a lot easier than what I'm doing today at least.
