### ISSUE TITLE
Flagless multiplatform build support

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/rules_go#2026]
### What version of rules_go are you using?

0.18.1

### What version of Bazel are you using?

0.23.2-homebrew

Will the go rules support the `platforms` attribute described in https://bazel.build/roadmaps/configuration.html under "Flagless multiplatform builds"?  If so, is the late 2019 estimate accurate?

**Comment by jayconrod** [comment]
This will be supported after the underlying Bazel features are implemented and exposed in Starlark. We'll migrate the `goos`, `goarch`, and other `mode` attributes to use this internally, since they're causing a lot of problems.

I don't have any target date for this at the moment, but it's one of the higher priority projects in rules_go.

**Comment by jschaf** [comment]
Thanks.  If I understand correctly, this is blocked by https://github.com/bazelbuild/bazel/issues/6519.

**Comment by jayconrod** [comment]
Yes, right.

I'll close this issue because there's nothing concrete to do right now, and the upstream design may change. We'll add whatever support is needed in rules_go once Bazel has this capability though.
