### ISSUE TITLE
rules_go depends on an old version of Skylib

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_go#2071]
This command fails since https://github.com/bazelbuild/rules_go/commit/a3e3b985a361dff8f728ccc1ae11b8e93e4b84c2:
```
$ bazel build ... --nobuild --incompatible_new_actions_api
...
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/63c478cc326e1221ca1a1ff458aee3ab/external/io_bazel_rules_go/go/private/skylib/lib/unittest.bzl", line 169, in unittest.end
		env.ctx.file_action(output = env.ctx.outputs.executa..., <2 more arguments>)
Use ctx.actions.write instead of ctx.file_action. 
```

Since that commit, it looks like rules_go depends on an old version of Skylib. Using a more recent version should be enough to fix the build error.

**Comment by laurentlb** [comment]
I was confused, the problem was in the private copy of Skylib.

**Comment by jayconrod** [comment]
Reopening because #2074 doesn't update the private copy of Skylib to a newer version.

Since I moved repository definitions to `go/deps.bzl`, I don't think we need a complete private copy of Skylib. We probably only need `versions.bzl`. Everything else could be referenced through an external repo. Needs more evaluation.

@laurentlb I'm curious how you caught this failure. Is there something in CI that runs rules tests with incompatible flags? I haven't found an efficient way to do this yet.

**Comment by laurentlb** [comment]
We use this Buildkite pipeline: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags
We check the results before flipping any flag.
