### ISSUE TITLE
go_proto_library generated sources as implicit output targets

### ISSUE THREAD

**Issue by blico** [bazelbuild/rules_go#2111]
I am curious if it is possible for `go_proto_library` rules to declare their generated sources as [implicit output targets](https://docs.bazel.build/versions/master/be/common-definitions.html#implicit-outputs).

This would make it possible to query for `go_proto_library`'s generated sources with `bazel query 'kind("generated file", ...)'`.  Also, you could generate a specific file target with something like `bazel build //foo/bar:baz.pb.go`.

If this is not possible, do you have any recommended way to query a repo for all of its generated sources?

**Comment by jayconrod** [comment]
I don't think this is feasible for `go_proto_library`. I'd rather not expose the output file names. It's an implementation detail that's subject to change, and it varies a lot with the proto compiler being used, so I'd prefer not to freeze that in the API.

About querying all generated files: do you mean all generated files from `go_proto_library`, or all generated files of any kind? `go_proto_library` makes its source available in the `go_generated_srcs` output group, though the names of those sources are not frozen. I'm not sure how to query for all generated files. `bazel aquery` might be able to do it, but I haven't tried it.

**Comment by linzhp** [comment]
In our repo, we don't check-in generated code. For IDEs to resolve imports, we have to copy all generated code (from proto, thrift, gomock, etc) to somewhere discoverable by IDEs. So we need to find all generated code depended by a project transitively.

There are 3 options we have right now:
1. Build all transitive dependencies of the project. This is the most expensive, but more exhaustive way. It will not only generate the code, but also compile and link them, although for IDEs to resolve imports, we don't need to compile and link generated code. Also, compilation and linking errors will be mixed with code-gen errors. We often have to make the code buildable before making IDEs work. But people often need helps from IDEs to make the code buildable...
2. Add `go_generated_srcs` output group to all Bazel targets that generate Go code.
3. Like @blico suggested, make existing code-gen rules respond to `bazel query 'kind("generated file", ...)'`. 

Both 2 and 3 require changes to existing Bazel rules. Option 2 is easier to implement, but it's Go specific. I think this is a general problem for any languages when it comes to IDE integration with Bazel.  It's better to have some standard interface across different languages to find all generated code. That's why we were thinking about Option 3. Or is there any other plan to help IDEs resolving generated code (well, besides checking in generated code).

**Comment by jayconrod** [comment]
For IDE support, #512 is the plan. It's been open for a long time, but nothing is blocking it anymore, and it's the highest priority feature work currently planned for rules_go. I haven't been able to give it much attention over the last couple months: keeping up with Bazel incompatible changes has blown my time budget for rules_go and Gazelle. However, Bazel is entering a stability period for a few releases before Bazel 1.0, and I'm hoping to have more time to work on it after rules_go 0.19.0 is out.

**Comment by jayconrod** [comment]
Closing old issues. I don't think rules_go can do anything beyond the `go_generated_srcs` output group.

**Comment by reddaly** [comment]
Here is a macro and rule I'm using to achieve this:

Usage:

```starlark
load("//bazel:write_go_generated_srcs.bzl", "write_go_proto_srcs")

go_proto_library(
    name = "service_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "github.com/google/xtoproto/proto/service",
    proto = ":service_proto",
    visibility = ["//visibility:public"],
    deps = ["//proto/recordtoproto"],
)

write_go_proto_srcs(
    name = "write_generated_protos",
    go_proto_library = ":service_go_proto",
    src = "service.pb.go",
)
```

```starlark
# Contents of bazel/rite_go_generated_srcs.bzl:

load(
    "@io_bazel_rules_go//go:def.bzl",
    "GoLibrary",
    "GoSource",
    "go_context")
load(
    "@io_bazel_rules_go//proto:compiler.bzl",
    "GoProtoCompiler",
)
load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")

def _output_go_library_srcs_impl(ctx):
    go = go_context(ctx)

    srcs_of_library = []
    importpath = ""
    for src in ctx.attr.deps:
        lib = src[GoLibrary]
        go_src = go.library_to_source(go, ctx.attr, lib, False)
        if importpath and lib.importpath != importpath:
          fail("importpath of all deps must match, got {} and {}",
            importpath, lib.importpath)
        importpath = lib.importpath
        srcs_of_library.extend(go_src.srcs)

    if len(srcs_of_library) != 1:
      fail("expected exactly one src for library, got {}", len(srcs_of_library))

    if not ctx.attr.out:
      fail("must specify out for now")

    # Run a command to copy the src file to the out location.
    _copy(ctx, srcs_of_library[0], ctx.outputs.out)

def _copy(ctx, in_file, out_file):
  # based on https://github.com/bazelbuild/examples/blob/main/rules/shell_command/rules.bzl
  ctx.actions.run_shell(
      # Input files visible to the action.
      inputs = [in_file],
      # Output files that must be created by the action.
      outputs = [out_file],
      progress_message = "Copying {} to {}".format(in_file.path, out_file.path),
      arguments = [in_file.path, out_file.path],
      command = """cp "$1" "$2" """
    )

output_go_library_srcs = rule(
    implementation = _output_go_library_srcs_impl,
    attrs = {
        "deps": attr.label_list(
            providers = [GoLibrary],
            aspects = [],
        ),
        "out": attr.output(
          doc = ("Name of output .go file. If not specified, the file name " +
          "of the generated source file will be used."),
          mandatory = False,
        ),
        "compiler": attr.label(
            providers = [GoProtoCompiler],
            default = "@io_bazel_rules_go//proto:go_proto",
        ),
        "_go_context_data": attr.label(
            default = "@io_bazel_rules_go//:go_context_data",
        ),
    },
    toolchains = ["@io_bazel_rules_go//go:toolchain"],
)


def write_go_proto_srcs(name, go_proto_library, src, visibility = None):
  generated_src = "__generated_" + src
  output_go_library_srcs(
      name = name + "_generated",
      deps = [go_proto_library],
      out = generated_src,
      visibility = ["//visibility:private"],
  )

  write_source_files(
      name = name,
      files = {
          src: generated_src,
      },
      visibility = visibility,
  )
```
