### ISSUE TITLE
Irregular behavior with piped stdin in go_test between rules_go versions

### ISSUE THREAD

**Issue by steventangx** [bazelbuild/rules_go#2125]
### What version of rules_go are you using?

Current version:
bazel = 0.27.0
gazelle = 0.17.0
rules_go = 0.18.6

Prior version:
bazel = 0.21.0
gazelle = 0.16.0
rules_go = 0.16.5

### Does this issue reproduce with the latest releases of all the above?

Yes, and only on recent releases of the above.

### What operating system and processor architecture are you using?

Centos7, x86_64

### What did you do?

Ran `bazel test //cmd/stuff/tests:go_default_test` against `rules_go = 0.16.5` and `rules_go = 0.18.6`

stuff_test.go
```
func hasPipedStdin() bool {
	f := os.Stdin
	stat, _ := f.Stat()
	if stat.Mode()&os.ModeNamedPipe == 0 {
		return false
	}

	return true
}
func TestStuff(t *testing.T) {
	t.Run("should not have piped stdin", func(t *testing.T) {
		assert.False(t, hasPipedStdin())
	})
}
```

### What did you expect to see?

Result from `rules_go = 0.16.5`:

```
INFO: Build completed successfully, 14 total actions
//cmd/stuff/tests:go_default_test                                        PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
```

### What did you see instead?

Result from `rules_go = 0.18.6`:
```
==================== Test output for //cmd/stuff/tests:go_default_test:
--- FAIL: TestStuff (0.00s)
    --- FAIL: TestStuff/should_not_have_piped_stdin (0.00s)
        stuff_test.go:21: 
                Error Trace:    stuff_test.go:21
                Error:          Should be false
                Test:           TestStuff/should_not_have_piped_stdin
FAIL
================================================================================
```
I would expect the test case to pass since I'm not piping anything to stdin.
Executing `bazel run` against the function above also returns back the correct output - `false`. This error only seems to occur when I run `bazel test`.

**Comment by jayconrod** [comment]
Tests executables are run by Bazel. Nothing in rules_go should be modifying stdin within the test executable before tests are run.

So two things could have caused a change in behavior:

1. A newer version of Bazel executes tests differently. What happens when you use rules_go 0.18.6 with Bazel 0.21.0?
2. A newer version of Go (supported by default in newer versions of rules_go) handles stdin differently in the test infrastructure. What happens when you use rules_go 0.16.5 with Bazel 0.21.0? If that doesn't work, what happens when you use an older version of Go with rules_go 0.18.6 (by setting `go_version = "1.10"` in `go_register_toolchains` for example)?

Without knowing what Bazel is doing here, I'd expect it to use a pipe in some cases (especially with `--test_output=streamed`) and a file in other cases. I don't think any particular kind of input is guaranteed.

**Comment by steventangx** [comment]
Thanks for the clarification. Yes, my mistake, the issue seems to stem from bazel version 0.27.0.
