### ISSUE TITLE
documentation of wtool

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#214]
wtool is mentioned in [some places](https://github.com/bazelbuild/rules_go/issues/195#issuecomment-260772903) but it's not documented in the README. The current `-help` isn't super helpful about what input wtool takes.

    $  wtool -help
    Usage of wtool:
      -asis
        	if true, leave the import names as-is (by default they are treated as bazel converted names like org_golang_x_net
      -verbose
    	    if true, logging extra information

It'd be nice if those docs could include how to get it building with `bazel run @io_bazelbuild_rules_go//go/tools/wtool`. Currently, it fails with `The repository named 'io_bazel_buildifier' could not be resolved and referenced by '@io_bazel_rules_go//go/tools/wtool:wtool'.` if you don't know how to add that repo in.

**Comment by jmhodges** [comment]
Guessing at stuff doesn't help much either since it's not clear to a newbie (or me!) what "4 parts" are needed.

   $  wtool io_bazel_buildifier
    2016/12/02 01:30:46 workspace names must be 4-parts or longer: "io_bazel_buildifier"

    $  wtool github.com/bazelbuild/buildifier
    2016/12/02 01:31:20 workspace names must be 4-parts or longer: "github.com/bazelbuild/buildifier"

**Comment by pmbethe09** [comment]
You are using wtool correctly, but I guess I put in an error check
expecting longer repo names.  The "4 parts" are the parts split on '_'
https://github.com/bazelbuild/rules_go/blob/master/go/tools/wtool/main.go#L87

Specifically in the case of buildifier, I think you want a 'go_repository',
rather than a 'new_go_repository', as it already has BUILD files.

It was just a script I wrote to solve my own problems, so I shared it, but
it is not exactly the most robust or well documented.

On Fri, Dec 2, 2016 at 4:32 AM, Jeff Hodges <notifications@github.com>
wrote:

> Guessing at stuff doesn't help much either since it's not clear to a
> newbie (or me!) what "4 parts" are needed.
>
> $ wtool io_bazel_buildifier
>
This works for say 'wtool com_github_golang_glog'
but apparently not for 3 '_'


> 2016/12/02 01:30:46 workspace names must be 4-parts or longer:
> "io_bazel_buildifier"
>
> $  wtool github.com/bazelbuild/buildifier <http://github.com/bazelbuild/buildifier2016/12/02>
>
> use -asis to avoid it trying to convert from a bazel-repo-name to an
import path
wtool -asis github.com/bazelbuild/buildifier

**Comment by jmhodges** [comment]
Yeah, just an FYI, that `asis` didn't work, because I was adding to try to get gazelle and buildifier to build from my repo and the rules_go repository expects a `io_bazelbuild_buildifier` while `asis` makes it `github.com_bazelbuild_buildifier`.

I think you're implying wtool isn't going get fixes discussed in this ticket, and, if so, I'd ask for it to be taken back out since it'll just confuse folks.

**Comment by pmbethe09** [comment]
Sorry, what fixes would you like?
* better documentation?
* works for io_bazelbuild_buildifier

anything else?

**Comment by ianthehat** [comment]
wtool is now deprecated, in favour of gazelle editing the workspace with full merging logic.
See bazelbuild/bazel-gazelle#47 for the new update-repos command
