### ISSUE TITLE
Allow go_test rule to optionally return compiled test binary and not execute it

### ISSUE THREAD

**Issue by alex-broad** [bazelbuild/rules_go#2259]
This is an enhancement request.

It seems `go_test` actually compiles the test binary, but doesn't export this back to the caller like `go_binary` does.

This would be useful to allow building and execution of tests (especially integration tests) in external contexts (e.g. in containers, with their running dependencies available).

So, I am requesting two options:
1. To be able to export the test binary in a similar manner to `go_binary`
1. To be able to pass an option to disable execution of the test itself by bazel

**Comment by jayconrod** [comment]
What do you mean by export? If you `bazel build` a `go_test` rule (instead of `bazel test`) it produces an executable.

`go_test` returns that executable through the `DefaultInfo` provider, so you can also use it in `filegroups` or anything else that expects a list of files.

`go_binary` works the same was as far as the executable is concerned, so I'm not exactly sure what the difference is.

**Comment by alex-broad** [comment]
Ah, in which case this was down to my lack of understanding about how Bazel worked in this regard. Thanks for your input. Closing.
