### ISSUE TITLE
Undefined test functions when using `go_test`

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_go#2301]
### What version of rules_go are you using?

0.20.2

### What version of gazelle are you using?

0.19.1

### What version of Bazel are you using?

1.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS Catalina on amd64.

### Any other potentially useful information about your toolchain?

No.

### What did you do?

I have a simple `go_test` rule, for a simple library. This is the `BUILD.bazel` file under `foo/pkg/bar`:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lib",
    srcs = ["xxx.go"],
    importpath = "foo/pkg/bar",
    visibility = ["//visibility:public"],
)

go_test(
    name = "test",
    srcs = ["xxx_test.go"],
    importpath = "foo/pkg/bar",
    deps = [":lib"],
)
```

`xxx_test.go` contains:

```go
package bar

import (
	"testing"
)

func TestXxx(t *testing.T) {
}

```

I'm doing `bazel build //pkg/bar:test`.

### What did you expect to see?

A successful compilation.

### What did you see instead?

```
/private/var/tmp/_bazel_duarten/18d4d4fe625c2f83e91dbc80b9b94787/sandbox/darwin-sandbox/148/execroot/foo/bazel-out/darwin-fastbuild/bin/pkg/bar/darwin_amd64_stripped/test%/testmain.go:22:14: undefined: events.TestXxx
```

**Comment by duarten** [comment]
Simple repro:

Workspace
```python
workspace(name = "foo")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "b9aa86ec08a292b97ec4591cf578e020b35f98e12173bbd4a921f84f583aebd9",
    urls = [
        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "86c6d481b3f7aedc1d60c1c211c6f76da282ae197c3b3160f54bd3a8f847896f",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.1/bazel-gazelle-v0.19.1.tar.gz",
    ],
)


http_archive(
    name = "com_github_bazelbuild_buildtools",
    strip_prefix = "buildtools-master",
    url = "https://github.com/bazelbuild/buildtools/archive/master.zip",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/master.zip"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
```

BUILD.bazel
```python
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix foo
gazelle(name = "gazelle")
```

bar/xxx.go
```go
package bar

type A struct {
	id int
}
```

bar/xxx_test.go
```go
package bar

import "testing"

func TestXxx(t *testing.T) {
}
```

bar/BUILD.bazel
```python
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lib",
    srcs = ["xxx.go"],
    importpath = "foo/bar",
    visibility = ["//visibility:public"],
)

go_test(
    name = "test",
    srcs = ["xxx_test.go"],
    importpath = "foo/bar",
    deps = [":lib"],
)
```

**Comment by jayconrod** [comment]
This should actually be a link error. #1327 is the issue for that, so I'll close this as a duplicate.

The problem in this example is that both the library and the test (which depends on your library via `deps`) claim to have the same package path (set by `importpath = "foo/bar"`). The linker will only pick one of them, and it looks like the library wins here.

The test target should be written as:

```
go_test(
    name = "test",
    srcs = ["xxx_test.go"],
    embed = [":lib"],
    importpath = "foo/pkg/bar",
)
```

Note the `embed` instead of `deps`. This will cause test sources with the same package name as the embedded library to be compiled into the same .a file. Test sources with a package name that ends with `_test` will be compiled into a separate .a file, but there's no conflict since it also has a separate package path.

If your project is also buildable with `go build`, you can generate Bazel build files automatically with [Gazelle](https://github.com/bazelbuild/bazel-gazelle).
