### ISSUE TITLE
gazelle errors with build_file_name

### ISSUE THREAD

**Issue by kyessenov** [bazelbuild/rules_go#234]
I'm trying to add a new go repository from github.com/coreos/pkg:
new_go_repository(
    name = "com_github_coreos_pkg",
    commit = "fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8",
    build_file_name = "BUILD.bazel",
    importpath = "github.com/coreos/pkg",
)

On a Mac, build fails with an error:
2016/12/20 10:26:09 BUILD.bazel:3:12: syntax error near /
(obtained from this command: ../io_bazel_rules_go_repository_tools/bin/gazelle -go_prefix "github.com/coreos/pkg" --mode print -repo_root . --build_file_name=BUILD.bazel)

There is of course "build" executable file at the root of this repo.
I'm unable to get more details on the failure, but it should be easy to reproduce.

**Comment by pmbethe09** [comment]
@twpayne any ideas?

**Comment by twpayne** [comment]
Initial investigation indicates that this has nothing to do with `build_file_name`, i.e. I get the same error whether `build_file_name` is `BUILD.bazel` or the default `BUILD`.

The test repo I'm using to reproduce the problem has:

`WORKSPACE`:

```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "035639ff3569e98976ff7e5b5040c9f19444dfe5",
)

load("@io_bazel_rules_go//go:def.bzl", "go_repositories", "new_go_repository")

go_repositories()

new_go_repository(
    name = "com_github_coreos_pkg",
    commit = "fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8",
    build_file_name = "BUILD.bazel",
    importpath = "github.com/coreos/pkg",
)
```

`BUILD`:

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_prefix")

go_prefix("github.com/twpayne/go-example")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    visibility = ["//visibility:private"],
    deps = ["@com_github_coreos_pkg//timeutil:go_default_library"],
)

go_binary(
    name = "go-example",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)
```

`main.go`:

```
package main

import (
	"fmt"
	"time"

	"github.com/coreos/pkg/timeutil"
)

func main() {
	fmt.Printf("%v\n", timeutil.ExpBackoff(1*time.Second, 1*time.Second))
}
```

I generated the `BUILD` file with:

    gazelle -go_prefix=github.com/twpayne/go-example .

So, my immediate suspicion is that it has something to do with some aspect of the `github.com/coreos/pkg` repository that is not yet correctly handled by `rules_go`.

(it's 1am here right now so I can't investigate further at this instant)

**Comment by twpayne** [comment]
BTW the error is

```
ERROR: /Users/twp/src/github.com/twpayne/go-example/BUILD:5:1: no such package '@com_github_coreos_pkg//timeutil': failed to generate BUILD files for github.com/coreos/pkg: 2016/12/21 01:03:29 /private/var/tmp/_bazel_twp/3513a22270a03e449662801500605cb5/external/com_github_coreos_pkg/BUILD.bazel:3:12: syntax error near /
 and referenced by '//:go_default_library'.
ERROR: Analysis of target '//:go-example' failed; build aborted.
```

**Comment by twpayne** [comment]
The problem occurs because [`github.com/coreos/pkg`](https://github.com/coreos/pkg) contains a file called [`build`](https://github.com/coreos/pkg/blob/master/build) containing

```
#!/bin/bash -e

go build ./...
```

Gazelle tries to parse this as a BUILD file, and raises an error.

**Comment by kyessenov** [comment]
I specified "build_file_name" option to use a different file "BUILD.bazel". Can we not parse BUILD (or build) file with this option?

**Comment by twpayne** [comment]
The problem is that `build_file_name` only applies to *new* files that are created (or updated). Gazelle tries to read all existing `BUILD` and `BUILD.bazel` files, computes the new contents, and writes the new file as `build_file_name`, possibly removing the old file if it was named differently.

What happens in your case here is that Gazelle finds a file called `build`, which appears as `BUILD` on macOS because of macOS's case insensitivity. It tries to parse it as a `BUILD` file but fails, resulting in the error.

It's not really clear what the correct course of action when Gazelle can't parse a `BUILD`. Two reasonable options:

* Throw an error. This catches invalid `BUILD` files.

* Ignore it. This makes Gazelle tolerant to files called `BUILD` that aren't actually `BUILD` files (as in this case) but at the risk of missing invalid `BUILD` files and overwriting existing files called `BUILD`.

**Comment by lizan** [comment]
Can gazelle ignore `build` but only parse `BUILD`, to be consistent with bazel itself?

Instead of `os.Stat` [here](https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/gazelle/main.go#L190) reading the parent dir will return a case sensitive filename.

**Comment by twpayne** [comment]
Interesting idea, but I think it would be fragile.

On macOS, `build`, `Build`, `BUILD` etc. are all the same filename. Bazel itself will read a file called `build` because it cannot tell the difference.

Even if we hack in pseudo-case-sensitivity by reading the parent directory, we'll get strange behaviour. For example, if we write a file called `BUILD` then this will overwrite `build` if it exists. `BUILD` and `build` simply cannot exist simultaneously in the same directory in macOS.

In the case of `github.com/coreos/pkg` I'd simply submit a PR to remove the `build` file or rename it to `build.sh`. It's not a long script.

**Comment by kyessenov** [comment]
I requested a rename.
I would suggest to have some work around this issue in rules_go. It is difficult to chase dependencies that have strange "build" files in them.
Would it be a lot of work to add file type detection to Bazel for shell scripts?
For example, you could detect a hash-bang prefix and skip parsing the file.

**Comment by lizan** [comment]
For the particular case it works.

@twpayne A directory with

- BUILD.bazel (valid BUILD file)
- build (shellscript, not valid BUILD syntax)
- srcs...

build successfully, bazel does ignore `build`, not sure if it does the pseudo-case-sensitivity or ignore the parsing error. I just meant gazelle should keep consistent with that behavior.

**Comment by jayconrod** [comment]
We've made some improvements to the way Gazelle deals with existing BUILD and BUILD.bazel files. I believe this is resolved.
