### ISSUE TITLE
Is Cross Building GO application on MacOS X to Debian using platform linux_amd64_cgo supported?

### ISSUE THREAD

**Issue by ebrunouber** [bazelbuild/rules_go#2351]
### What version of rules_go are you using?
0.20.2
### What version of gazelle are you using?
92bc7b03d768a3581bd9bdd30d5e3635bbf854da
### What version of Bazel are you using?
1.1.0
### Does this issue reproduce with the latest releases of all the above?
Toolchain is fixed, unable to currently upgrade versions.

### What operating system and processor architecture are you using?
Host platform is Max OS X Mojave, Target is linux_amd64 (debian)

### Any other potentially useful information about your toolchain?
Attempting to cross compile a go application on MacOS X Mojave to linux_amd64.
One eternal package used https://github.com/mindprince/gonvml (NVIDIA Management Library (NVML) bindings for Go) is required to build using cgo.

### What did you do?
bazel build --toolchain_resolution_debug --sandbox_debug --verbose_failures --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 <path to source code>

gives the error:
  exec env - \
    CGO_ENABLED=0 \
    GOARCH=amd64 \
    GOOS=linux \
    GOROOT=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib% \
    GOROOT_FINAL=GOROOT \
    PATH=/bin:/usr/bin \
 .....
/private/var/tmp/_bazel_ebruno/35e15ec32e40a6d7ce2d0d8ac9152241/sandbox/darwin-sandbox/2256/execroot/__main__/external/com_github_google_cadvisor/accelerators/nvidia.go:29:2: imported and not used: "github.com/mindprince/gonvml" as empty
/private/var/tmp/_bazel_ebruno/35e15ec32e40a6d7ce2d0d8ac9152241/sandbox/darwin-sandbox/2256/execroot/__main__/external/com_github_google_cadvisor/accelerators/nvidia.go:43:24: undefined: gonvml
Which I would expect since a CGO_ENABLED is 0.

bazel build --toolchain_resolution_debug --sandbox_debug --verbose_failures --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64_cgo

### What did you expect to see?

A tool chain match, CGO_ENABLED set to 1 and a successfully build.

### What did you see instead?
INFO: ToolchainResolution:   No toolchains found
ERROR: While resolving toolchains for target @io_bazel_rules_go//:cgo_context_data: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
ERROR: Analysis of target '//src/code.uber.internal/infra/cexporter:cexporter' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type

My question(s) are hopefully straight forward.

1) Was this topic [Build on darwin for Docker container](https://github.com/bazelbuild/rules_go/issues/354) "fixed/enhanced" in later/current releases of bazel".
Specifically were the comments:  
Cross compilation only works for pure Go targets. There are some issues with cgo that we're working out.
Platforms aren't connected with the --cpu flag, which Gazelle uses to filter platform-specific sources and deps. We'll fix this after Bazel 0.8 is released.

Fixed/enhanced in latter/current release of bazel? If so which version?

2) Using MacOS X Mojave for go applications is platform linux_amd64_cgo supported on any version of bazel?

3) Is there an existing published cc compiler bazel toolchain that could be loaded in the workspace and/or Build file for a debian target when specifying --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64_cgo?

     
4) I have looked at a significant amount of documentation on creating toolchains, it seems to be a bit daunting.   LLVM toolchain for Bazel on github seems to be the best "example" to follow.

5) What would be a recommend approach for including/publishing a cc toolchain  in the docker containing doing the cross-compile build?  Assuming this can be done with the current versions of bazel?

**Comment by jayconrod** [comment]
Cross-compiling with cgo is supported, but you're responsible for configuring and registering a cross-compiling C/C++ toolchain. So make sure you're able to build a `cc_binary` target using the same `--platforms` flag first.

Answers to your specific questions:

1. As of Bazel 2.0.0, I believe C/C++ toolchain selection is still tied to `--cpu`, but you can flip `--incompatible_enable_cc_toolchain_resolution` to use platforms instead. That flag has been around for a while, and it seems to be working fine. I expect the default will be flipped for Bazel 3.0.0 in a couple months, but follow bazelbuild/bazel#7260 for details.
2. Should work as long as you have a working C/C++ toolchain. The minimum supported version of Bazel is 1.2.0. I know people have been able to cross-compile from macOS to Android using the NDK.
3. Not that I know of.  But maybe ask in rules_cc or on the bazel-discuss mailing list?
4. Yeah, especially for C/C++, the mechanism for defining toolchains has changed over time, and it was never easy. Folks on bazel-discuss can point to the most up-to-date resources.
5. Rather than relying on Docker, I would look into creating a repository or tarball around a set of toolchain binaries, along with build files and workspace macros needed to configure and register it. Then you could reference that through WORKSPACE in any Bazel project whether you're running a Docker container or not.

**Comment by ebrunouber** [comment]
Your answer  is helpfully and for my questions complete.
Thank you for the timely and succinct response.

Eric Bruno
ebruno@ext.uber.com

**Comment by hsyed** [comment]
Would it be possible to get an example of setting up a toolchain on Mac / Linux the way it used to work before the cc toolchain stuff was enabled in rules_go --i.e., on a Mac the Xcode toolchain was automagically configured.

**Comment by jayconrod** [comment]
@hsyed On Mac, the Xcode toolchain is still automatically configured. If that's not what you're seeing, please open an issue with more detail.
