### ISSUE TITLE
--test_output=errors output now also contains successfully passed tests, i.e. became too verbose...

### ISSUE THREAD

**Issue by robbertvanginkel** [bazelbuild/rules_go#2364]
`bazel test` output with `--test_output=errors` now also contains successfully passed tests, i.e. became too verbose...

_Originally posted by @asv in https://github.com/bazelbuild/rules_go/issues/236#issuecomment-583345560_

**Comment by robbertvanginkel** [comment]
Unfortunately, passing verbose output from `-test.v` trough test2json is the only supported way to get full output for creating a testreport that not only contains failures but also indications of how many tests were successful.

https://github.com/bazelbuild/rules_go/blob/9c9136c7d2800810ec1668b9a2b94677a32c515c/go/tools/testwrapper/wrap.go#L46-L53

Potentially, we could keep the `-test.v` in the args so we will still continue to receive all events, but instead of having the process' stdout be a `MultiWriter` that writes everything to `os.Stdout`, we could set it to only the Converter and have the converter write to a `MultiWriter`, where we write both to the jsonbuffer and a writer that based on `-test.v` being specified externally we write all output or failed test output to stdout.

**Comment by jayconrod** [comment]
Having shorter, cleaner output for `--test_output=errors` seems like a win. This has ended up being pretty chatty.

@robbertvanginkel The approach you outlined seems viable, but pretty complicated. WDYT about flipping the default so that we don't generate XML output or pass `-test.v` to tests? I think XML output is mostly just needed in CI, and it doesn't seem unreasonable to ask people to add `--test_env=GO_TEST_WRAP=1` in that environment if they need this.

**Comment by robbertvanginkel** [comment]
I think there's a case for keeping the test wrapper on, it could also help with https://github.com/bazelbuild/rules_go/issues/1918 to change the working directory for tests before the test binary exexcutes rather than in `main()`.

I'd prototyped the above idea in https://github.com/robbertvanginkel/rules_go/commit/0e7d13dd286cf5d62ae4e784432a543b2eeec3d4, but I'm not set on this as solution. It is a little more complicated, but not too terrible. The trickier part would be keeping the printing behavior in sync with the standard go toolchain. If this is mostly used for users reading the output from their terminal, maybe printing the exact same limited output isn't that important.

https://github.com/bazelbuild/rules_go/issues/1918 is argument to keep the wrapper, which you'd want fixed regardless of local/ci. Maybe we should add an env variable like `GO_TEST_WRAP_TESTV=1`?

**Comment by jayconrod** [comment]
Good point about keeping the wrapper for #1918. `GO_TEST_WRAP_TESTV=1` probably makes more sense (or maybe renamed to `GO_WRAP_TEST_XML=1`).

If you're up for keeping `-test.v` and filtering the output sent to stdout so it looks like `-test.v` was not set, I'd be happy to accept a PR for that. Less configuration is great, but less complexity is good, too.

**Comment by achew22** [comment]
Out of curiosity, would the test wrapper be useful for reporting coverage?

**Comment by jayconrod** [comment]
@achew22 Sorry no, coverage is pretty separate.

Currently, you can test with `bazel coverage` and select targets to instrument using `--instrumentation_filter` (kind of like `-coverpkg`). The instrumentation mostly works, and the generated test main gathers coverage data and writes it to a file.

There are some missing pieces in Bazel though. There needs to a common format that all languages convert their coverage into. There needs to be a way for languages to provide tools to do that. There needs to be a way to merge multiple sets of coverage data. And Bazel needs to be able to display that information in a useful way. Blaze has some facilities for that, but I don't think they're open source, and they wouldn't serve all the needs of open source devs in any case.

There were some presentations on coverage at BazelCon 2018. I'm not sure what's new since then. The [roadmap](https://bazel.build/roadmaps/coverage.html) and the [design doc](https://docs.google.com/document/d/1-ZWHF-Q-qCKf19ik-t33ie58BkNurrYYzKR4OLtcilY/edit?usp=sharing) are pretty far out of date.

**Comment by robbertvanginkel** [comment]
@jayconrod do you have a target release date for the next rules_go version that would include https://github.com/bazelbuild/rules_go/pull/2348? I'd prefer to go the less configuration route but it will take me a bit more time then adding another env check, and I think it'd be good if the next release won't change the default chattiness.

**Comment by jayconrod** [comment]
This would be in `v0.22.0`, which should ship in early April. I aim to cut a new minor version of rules_go once a quarter, near the beginning of the quarter.

**Comment by robbertvanginkel** [comment]
I should be able to have a PR up well before that (probably in the next week or 2).

**Comment by jayconrod** [comment]
@robbertvanginkel I'd like to ship `v0.23.0` in 2-3 weeks (early May). Will you have a chance to look at this before then?

No big deal if not, but I may roll back #2348, then we can roll forward with a fix when it's ready.

**Comment by robbertvanginkel** [comment]
I'll get a PR up this week.

**Comment by robbertvanginkel** [comment]
I put up https://github.com/bazelbuild/rules_go/pull/2456, going with the approach to remove adding `-test.v` by default and instead have the user control it through an env variable. This seemed more durable than trying to recreate the toolchain's printing behavior.

I put it under a new environment variable `GO_TEST_WRAP_TESTV` instead of the existing `GO_TEST_WRAP_TESTV`, so we could still choose to solve #1918 through the wrapper without requiring to tie that to setting `-test.v`.
