### ISSUE TITLE
Add '-s' flag for go compilation in 'dbg' mode

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/rules_go#238]
Follow on from 
https://github.com/bazelbuild/rules_go/issues/220
when compiling with bazel build -c dbg
the '-s' flag should be added to the go compilation steps.
What about -c fastbuild ?

**Comment by ianthehat** [comment]
I don't think we should do this.
-s causes a significant change in program behavior, breaking stack traces, I don't think it's something that we should do without a very explicit option, -c opt is not nearly enough.

**Comment by ianthehat** [comment]
Not sure.

I think the perfect solution would be to change the go stack reporting mechanism to work even when the binary is stripped, and then tie it to the --strip option, but as long as stripping causes the names in the stacktrace on panic to disappear, I don't think we can afford to do it without a *very explicit to go* option. This is especially true as the same stacktraces are available using runtime/debug.Stack, and people do things based on the presence of strings in the trace.

I could see adding it as another output group (like static), or using a go specific feature, so that it is at least available to people that know what they are doing and want it anyway.

**Comment by sethkoehler** [comment]
I see.  I'm a bit unclear on one point though...are you saying we lose names in the stacktrace when:

1) we strip symbols (specifying -s to the Go link tool IIUC), or
2) we keep symbols (omitting -s in the Go link tool)?

(1) makes sense to me, but as far as I understand from #220 above, bazel is already stripping symbols during the link phase...except on Mac according to [this code](https://github.com/bazelbuild/rules_go/blob/master/go/toolchain/toolchains.bzl#L97).  Indeed, that's what seems to be happening when I objdump symbols as well from bazel built binaries...I only see symbols on go binaries I build with "go build".

(2) was perhaps what you were saying above?  However, I'm racking my brain to think of why the presence of symbols would cause the stack trace to lose names, although anything is possible of course :)

**Comment by ianthehat** [comment]
I spent yesterday looking at this and it seems that things have changed, and the  comments are no longer accurate.

It does not seem that you need the `-s` flag on the mac, so there is no reason to hard code it in the toolchain, and it seems that the `-s` flag also has no impact on the correctness of stack traces.

Given this, I propose we tie `-s` directly to the `--strip` behavior of Bazel. I already did all the work to detect it correctly when I added the `-w` flag in #871, we just need to rip out the current stripping behavior an add the -s next to the `-w`

**Comment by sethkoehler** [comment]
Wow, that's great news, thanks for looking into this!

**Comment by ianthehat** [comment]
I think everything asked for here is now fully working.
