### ISSUE TITLE
Dependency on rules_cc requires a git_archive which is difficulty with Bazel offline

### ISSUE THREAD

**Issue by mescanne** [bazelbuild/rules_go#2397]
### Overview

In a controlled (to the internet) environment using distdir and http_archive is important to be able to cache locally all dependencies. git_archive is incompatible with this.

Due to rules_cc not having any official releases yet, there are no archives to download. There is no easy mitigation to this in the enterprise (controlled) context.

### What version of rules_go are you using?

0.22.1

### What version of gazelle are you using?

Not relevant

### What version of Bazel are you using?

2.2.0

### Does this issue reproduce with the latest releases of all the above?

It applies only to the later releases which started using rules_cc.

### What operating system and processor architecture are you using?

Not relevant.

### What did you expect to see?

Ability to package an archive into distdir for offline use.

### What did you see instead?

No easy solution to enable a single WORKSPACE for the casual (internet-connected) developer and the build environment that is tightly controlled. I will be able to find one, but it will be a terrible hack that should not be needed.

**Comment by jayconrod** [comment]
This isn't actionable at the moment because there's no `rules_cc` release. Maybe file an issue with the `rules_cc` project?

`rules_cc` is a hard requirement. The native `cc_library` and `cc_binary` rules are being deprecated. rules_go will fail tests in Bazel CI if we use those instead of `rules_cc` (#2318).

As a workaround, you can declare your own version of the `rules_cc` repository before calling `go_rules_dependencies`. See [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies).

**Comment by mescanne** [comment]
If rules_cc is a hard requirement, then there needs to be a release of rules_cc.

I did do an override, but that means either I need to create my own archived copy and host it somewhere or mirror my own tree of rules_cc. Neither one is appealing when we're not doing this for anything else and it's just a temporary measure.

I'll file an issue with rules_cc.

**Comment by mescanne** [comment]
FYI - https://github.com/bazelbuild/rules_cc/issues/68
