### ISSUE TITLE
Runfiles library should not look in working directory

### ISSUE THREAD

**Issue by phst** [bazelbuild/rules_go#2421]
Currently runfiles.go searches the working directory (https://github.com/bazelbuild/rules_go/blob/master/go/tools/bazel/runfiles.go#L44). This fails when running a Bazel-built binary directly with an arbitrary working directory. Rather, runfiles.go should only look at known environment variables (`RUNFILES_DIR` etc.) and `os.Argv[0]` to find the runfiles directory/manifest. That's consistent with what C++ does and should work well in most cases (unless the user tampers with the environment variables or moves the runfiles away).

**Comment by jayconrod** [comment]
I think it makes sense to search the working directory as a last step, rather than a first step.

This needs to continue to work in configurations where it currently works, so I'm not willing to make major changes here.

**Comment by glukasiknuro** [comment]
Possibly we can create another `Runfile` version that does not look in the current working directory, or as @jayconrod said look in runfiles as a last resort?

It fails for example in our case when we create a binary that's supposed to later work on the same code-base (some utilities helping with development). Because Runfile looks at current working directory first, it may find different versions of some static files.
