### ISSUE TITLE
Support for go generate

### ISSUE THREAD

**Issue by danmx** [bazelbuild/rules_go#2446]
### What version of rules_go are you using?

`v0.22.4`

### What version of gazelle are you using?

`v0.20.0`

### What version of Bazel are you using?

`3.0.0`

### Does this issue reproduce with the latest releases of all the above?

Using current latest

### What operating system and processor architecture are you using?

darwin amd64

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

I'm learning `bazel` by moving my existing build scripts to `bazel`'s BUILD. I `go generate` to autogenerate interface mocks for my tests.

```go
//go:generate go run github.com/golang/mock/mockgen [...]
```

### What did you expect to see?

Gazelle generating some "generate" step.

### What did you see instead?

Only steps for dependencies and tests, no for `go generate`.

**Comment by jayconrod** [comment]
Sorry, this isn't feasible.

Bazel needs a completely specified set of inputs and outputs for every action. `go generate` can do basically anything, and there's no way to tell what's needed.

Instead, you can add targets in your build files that generate sources, then add those sources to the `srcs` lists of `go_library`, `go_binary`, or `go_test` targets. [`genrule`](https://docs.bazel.build/versions/master/be/general.html#genrule) can run most shell commands, so that's often a good place to start. You may want to write rules more tailored to your use case though. [`go_path`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path) helps for tools that expect to run in an environment that looks like a `GOPATH` directory.
