### ISSUE TITLE
Cannot build golang.org/x/sys with msan

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_go#2494]
### What version of rules_go are you using?

0.22.4

### What version of gazelle are you using?

0.20.0

### What version of Bazel are you using?

3.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

linux amd64

### What did you do?

```starlark
// WORKSPACE
go_repository(
    name = "org_golang_x_sys",
    commit = "fae7ac547cb717d141c433a2a173315e216b64c4",
    importpath = "golang.org/x/sys",
)
```

```
bazel build @org_golang_x_sys//unix:go_default_library --features=msan
```

### What did you expect to see?

Builds successfully

### What did you see instead?

```
# runtime/msan
gcc: error: unrecognized argument to '-fsanitize=' option: 'memory'
stdlib: error running subcommand: exit status 2
```

More specifically, I am having issues building with msan enabled with dependencies to this library and some standard libraries such as `io/ioutil` and `fmt`.

**Comment by jayconrod** [comment]
I couldn't reproduce this on my systems. It may be an issue with your C/C++ toolchain. Are you able to build `cc_binary` targets with `--features=race`?

If you're able to upgrade to rules_go `v0.23.0`, could you try building with `--@io_bazel_rules_go//go/config:race` instead of `--features=race`? That's the new recommended way to enable race mode. It will apply only to Go targets, not C/C++ dependencies.

`--features` was originally meant to control C/C++ toolchain features, but it was exposed in the Starlark API, and at the time, there wasn't any other way to define flags for Starlark rules, so rules_go abused `--features` for race mode and a few other things.
