### ISSUE TITLE
Using only go.mod and go.sum for dependencies

### ISSUE THREAD

**Issue by danmx** [bazelbuild/rules_go#2533]
From what I see Bazel's Node.js Rules use only `package.json` and `yarn.lock` for dependencies management. Why not use official Go module files instead of generating series of `go_repository` rules using Gazelle from the `go.mod` file?

**Comment by jayconrod** [comment]
There are a few reasons not to do this, at least not yet.

* Not everyone is using modules. I still see a lot of issues reported where people are using `go_repository` to download HTTP archives or git repositories instead of using `go_repository` in module mode. 
* There are repositories that have their own Bazel build files. `go_repository` may or may not be appropriate for these.
* There are repositories that require some patching or adjustment (for example, changing the proto mode).
* If all modules were fetched with a single repository rule, everything would have to be downloaded again when any module is upgraded.

**Comment by danmx** [comment]
Why not support both Go modules and `go_repository` same as JS Rules support both `yarn` and `npm`?

**Comment by achew22** [comment]
@danmx,

Can you describe how your question differs from how `rules_go` works today? You can manually write `go_repository` rules, or you can have `go.mod` generate a `repositories.bzl` file. It seems to me that it supports both right now.

**Comment by danmx** [comment]
Point is to remove an extra step of using `gazelle` to generate `repositories.bzl` making `go.mod` and `go.sum` a single source of truth.

Currently I have to have a [`pre-commit`](https://github.com/pre-commit/pre-commit) step rebuilding `repositories.bzl` whenever I (or my IDE) edit `go.mod` and `go.sum`. I find this weird since Go Modules are an official way to manage dependencies and current flow makes `repositories.bzl` the way to manage dependencies in Bazel.

[Python Rules](https://github.com/bazelbuild/rules_python#importing-pip-dependencies) is an another example of reading "standard" files instead of forcing developers to compile an additional file.

**Comment by jayconrod** [comment]
`go_repository` is the source of truth for Bazel external dependencies, much like `deps` in `go_library` is the source of truth for package imports. There are enough cases where people need to manually tweak these declarations or integrate changes from other repos, that I'd rather not provide an automatic solution.

One other practical concern: Bazel is working on an [overhaul for external dependency management](https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit). That will likely change a lot of things, so it doesn't make sense to make significant change's to `go_repository` until that path is ready.
