### ISSUE TITLE
How to override default for go_test timeout

### ISSUE THREAD

**Issue by stephenhyde** [bazelbuild/rules_go#2543]
### What version of rules_go are you using?

0.20.2

### What version of gazelle are you using?

0.19.0

### What version of Bazel are you using?

1.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS Catalina

BUILD.bazel is created when running gazelle. I want to add the attribute timout="short" to go_test by default. I am constantly forgetting to add it and get warnings on bazel build. Is there a way to have this attribute automatically set when running gazelle?

**Comment by jayconrod** [comment]
Gazelle won't set `timeout` or `size` since it can't infer how long a test should take. It will leave those attributes in place though.

You can could query test targets with `bazel query` and set `timeout` and `size` for a large number of targets using [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer).

**Comment by stephenhyde** [comment]
To confirm, you can't have gazelle blindly default all go_test timeouts to short and have you modify it manually if need be. You have to use buildozer to batch update it after?

**Comment by stephenhyde** [comment]
Thank you for your help. I'll go ahead and close this.
