### ISSUE TITLE
How to use google.golang.org/protobuf?

### ISSUE THREAD

**Issue by owenhaynes** [bazelbuild/rules_go#2549]
### What version of gazelle are you using?

v0.21.1

### What version of rules_go are you using?

v0.23.3

### What version of Bazel are you using?

v3.3.0

### Does this issue reproduce with the latest releases of all the above?
n/a

### What operating system and processor architecture are you using?

Ubuntu WSL2 X86

### What did you do?

n/a
### What did you expect to see?
n/a
### What did you see instead?
n/a

Trying to find out how to use gazelle with google.golang.org/protobuf v1.25.0 and not the old github.com/golang/protobuf v1.42.0 . As trying to migrate a project which uses the newer one to bazel. Don't see much mentioned in the docs about this new go protobuf generator.

**Comment by jayconrod** [comment]
The FAQ should probably be updated to explain this.

In short, `github.com/golang/protobuf` (APIv1) at `v1.4.0` or higher is forward compatible with `google.golang.org/protobuf` (APIv2). The former is a wrapper for the later.

rules_go continues to use `protoc-gen-go` from APIv1, since the generator from APIv2 is not backward compatible with APIv1 and doesn't generate code for gRPC services.

In code that uses protos, you should be able to import either runtime package; both should work.
