### ISSUE TITLE
go_test: don't include symbol table or DWARF by default

### ISSUE THREAD

**Issue by martinxsliu** [bazelbuild/rules_go#2550]
### Versions

OS: MacOS
Bazel: 3.3.0
Rules Go: 0.23.3
Gazelle: 0.21.0
Go: 1.14.4

### Problem

Performance of testing using Gazelle generated `go_test` targets seems to be taking 2x as long as simply running `go test`, and the majority of time is spent on the `GoLink` action for the test binaries. I understand there may be some overhead, but this seems more than what I would've expected.

My questions are, is this a known / expected issue? And if not how can I investigate / debug further?

#### Setup

I have an application that I've built & tested using `go build/test` and `bazel build/test` already so both caches are warm. I make an innocuous change in a low level package like change a value of an unused constant so that it triggers rebuilds of most of the application's packages / tests. Then I run `bazel test //path/...` (*) and `time go test ./path/...`.

I also don't specify any of the `pure`, `race`, or `static` flags. The `go_test` targets are completely generated by Gazelle.

(* Simply running `bazel test //path/...` also appears to build `go_binary` targets which aren't depended on by any tests. I'm not super familiar with Bazel behaviour but is it expected that bazel test will build provided targets before running only the test targets? In any case, I was careful to exclude the `go_binary` targets so that the Bazel test timings don't include linking non-test binaries.)

#### Results

Bazel test: ~50s (~20s critical path)
Go test: ~27s

#### Profile

I took a profile of the Bazel run which I've included a snippet here. As you can see most of the time is taken by `GoLink` actions for `go_default_test` targets. The other threads not included in the screenshot perform similarly.

![image](https://user-images.githubusercontent.com/13096680/86168115-8c68e200-bacc-11ea-9259-30e73cd01798.png)

#### Related issues?

Older performance related issues I've found (e.g. https://github.com/bazelbuild/rules_go/issues/1378) all seem related to std lib changes which have since been addressed.

**Comment by jayconrod** [comment]
Bazel imposes a lot of overhead that `go build` doesn't have via sandboxing and a more expensive file hashing scheme. I haven't measured the overhead in a while, but 50% is the ballpark I'd expect. 100% seems high.

While it's no longer necessary to rebuild the standard library in most cases, everything in there needs to be stat'd and hashed when Bazel starts, when symlinked and later removed for each action.

That overhead should affect all actions, not just `GoLink`. `GoLink` is far more expensive than `GoCompilePkg` though, and it's always on the critical path, so it doesn't surprise me that it's prominent.

There are some optimizations possible in how the standard library is handled, but I want to make more progress on #512 before pursuing them. For example, right now, we don't need standard library sources for any action in a non-cross-compiling build. But #512 will probably need them, so I'd hesitate to take them out now.

**Comment by martinxsliu** [comment]
So I did some more timings and I'm starting to suspect that `go test ./...` might be doing something smart with how it links/builds the test binaries.

Firstly, I noticed a much smaller perf gap when building a single binary. `go build` is about 5-10% faster than `bazel build` (10s overall). To me this feels like an appropriate amount of overhead as you mention.

When I build multiple binaries with `make -j 8` which in turn invokes `go build`, Bazel is actually about 10% faster. I can attribute this to Bazel's dep graph, whereas each of the make jobs has to `go build` from scratch without using the build cache from a parallel build.

Then, I attempted to build all the test binaries, also with `make tests -j 8` and `go test -c` (executing the test binaries themselves are very fast, the overall test time is dominated by building the test binaries). This takes ~53 seconds which is comparable to my `bazel test //path/...` timing earlier. It is slightly higher and this is consistent with building multiple binaries.

However, running `go test ./...` which to my understanding requires building of all the test binaries anyway only takes half as long! To me this suggests that `go test`, when given a package list, is doing something differently, and the performance gap between `go test` and `go_test` is more than just Bazel overhead. It could be building a different binary than what `go test -c` would produce, and hence builds them faster; or perhaps it's able to leverage it's internal compiler / linker state in a way that the Bazel rules do not. I'm not familiar with Go internals, but does this sound plausible to you?

**Comment by jayconrod** [comment]
I don't know enough about your setup to comment on any of this directly. Unfortunately I don't have bandwidth to dig into profiling data at the moment.

Some high-level differences:

* Bazel holds a global lock on the output directory, so you can't run multiple instances of Bazel in parallel (they can share a remote cache or a global disk cache though). `go build` has better support for running multiple instances in parallel, using the same cache.
* Bazel runs a server that keeps the analysis graph in memory. `go build` loads that every time from scratch.
* By default, Bazel sandboxes actions. I'm not sure how that works exactly, but I believe it involves at least creating (and later removing) a symbolic link for every input. `go build` doesn't do this.
* Bazel rules don't have access to source files, so input lists may be larger than necessary. rules_go passes all files in the standard library as inputs to every action, since there's no way to know which ones are needed.
* Bazel checks whether files have changed by taking a hash of the entire file. For compiled .a files and binary files `go build` stamps a hash that can be read much more quickly.
* Bazel stores linked binaries in the cache. `go test` does not; if a test result is invalidated, the test binary almost always needs to be relinked anyway.

**Comment by martinxsliu** [comment]
Thank you for the summary @jayconrod.

I followed up on my hunch that `go test pkg` is doing something differently than what `go test -c pkg` and the `go_test` rule is doing and I think I found the difference.

When linking the test binary with `go test pkg`, the linker flags will include [`-s -w`](https://github.com/golang/go/blob/a4ba411b19fa0111a3c8fe059fcf5489d3bd6bbf/src/cmd/go/internal/work/gc.go#L510-L512) which [omits the symbol table and DWARF debug info](https://github.com/golang/go/blob/a4ba411b19fa0111a3c8fe059fcf5489d3bd6bbf/src/cmd/link/internal/ld/main.go#L85-L87). These flags are gated by an `OmitDebug` variable which is only set for the `go run` subcommand as well as for `go test` if `-c` or the profile flags are not present. This makes sense as the binary is only used ephemerally in those 2 cases.

When I added `-s -w` to `rules_go`'s linker flags [here](https://github.com/bazelbuild/rules_go/blob/66d26131d23e527ebd208db04b4ebbc9b2b4d4c5/go/private/actions/link.bzl#L69), then my performance gap completely goes away. Running the same `bazel test //path/..` command now effectively takes the same time as running `go test ./path/...` (i.e. dropped from ~50s to ~27s).

Given the significant performance improvement, and that this will decrease the gap between `go` and Bazel, how would you feel about using these linker flags for `go_test`? I'm not familiar enough with Bazel to know if this can be made conditional on whether Bazel was invoked with `bazel test //test/target` or `bazel build //test/target`, but if not do you think it would be appropriate? Alternatively, there could be a config of some sort to permit users to toggle? I'm happy to take a stab at implementation if you are onboard.

**Comment by jayconrod** [comment]
Thanks for investigating this. I'm surprised DWARF generation makes that big of a difference.

Given that `go test` does this and that debug symbols are generally off by default in Bazel, I think it makes sense to pass these flags to the linker when building test binaries, especially since we don't have to rebuild individual libraries in a different configuration.

I think the best way to do that would be to add `["-s", "-w"]` to the `gc_linkopts` argument passed to `go.binary` from `_go_test_impl` in `go/private/rules/test.bzl`. That should only be done if `go.mode.debug` is `False`.

If you're up for submitting a PR, I'd be happy to merge it. Otherwise, I'll try and make the change some time before the next minor release, which should be in August.
