### ISSUE TITLE
package conflict and undefined genproto/googleapi errors between rules_go 23.8 -> 24

### ISSUE THREAD

**Issue by salrashid123** [bazelbuild/rules_go#2633]
### What version of rules_go are you using?

`rules_go-v0.24.0`
`rules_go-v0.23.8`

### What version of gazelle are you using?

`bazel-gazelle-v0.22.0`

### What version of Bazel are you using?

```
$ bazel version
Build label: 3.4.1
```

### Does this issue reproduce with the latest releases of all the above?

Yes, though different erros between the two version of `rules_go`

### What operating system and processor architecture are you using?

Linux, debian 5.7

### What did you do?

Trying to use bazel with google generated `secretmanager` and `protobuf/proto`

```golang
import (
	secretmanager "cloud.google.com/go/secretmanager/apiv1"
	"github.com/golang/protobuf/proto"
	secretmanagerpb "google.golang.org/genproto/googleapis/cloud/secretmanager/v1"
)
```

I'm trying to use gcp secret manager within bazel but seeing conflict errors and unable to comple against the two version of `rules_go` cited.  

### What did you expect to see?

To generate the go libraryand binary since it works w/o bazel.

### What did you see instead?

Two different erros:

- with `rules_go-v0.23.8`:

```
    <autogenerated>:1: undefined: "google.golang.org/genproto/googleapis/iam/v1".m
    Target //:client failed to build
```

- with `rules_go-v0.24.0`:

```
  >> package conflict error: github.com/golang/protobuf/protoc-gen-go/descriptor: multiple copies of package passed to linker:
```

I did search the issues about the last error and found citations to disable gazelle from using a global `com_google_protobuf`  but not sure how to use that or if it applies here.

---

Minimal repro

The following is a minimal app that uses secretmanager and proto.

[testbazel.tar.gz](https://github.com/bazelbuild/rules_go/files/5147072/testbazel.tar.gz)

to use, see `README.md`
```
go mod init main
go mod tidy

bazel run //:gazelle -- update-repos -from_file=go.mod
bazel build :client
```

then swap out the `io_bazel_rules_go` version in `WORKSPACE` for the two errors

**Comment by jayconrod** [comment]
The package conflict error is reported because two different copies of the same package are linked into the same binary. One copy, `@io_bazel_rules_go//proto/wkt:descriptor_go_proto`, is built from sources generated by protoc-gen-go at build time. The other copy, `@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library`, is built from pre-generated sources.

You may have this problem with other packages, too. The copies in `@go_googleapis` are generated at build time. The copies in `@org_golang_google_genproto` are pre-generated.

[Avoiding conflicts](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#avoiding-conflicts) explains this more completely, but in short: try to use only one set or the other. Gazelle will resolve dependencies based on the proto mode you're in. Since you've set `# gazelle:proto disable_global` in the root build file, you'll also need to use that mode in each `go_repository`. You can accomplish that as follows:

* `go mod tidy` - add missing dependencies.
* `bazel run :gazelle -- update-repos -from_file=go.mod -build_file_proto_mode=disable_global` - add `go_repository` rules with `build_file_proto_mode = "disable_global"`.
* `bazel build :client`

**Comment by jayconrod** [comment]
The `package conflict` error seems to be truncated here, so I've opened #2635 to track that. It should be:

```
package conflict error: github.com/golang/protobuf/protoc-gen-go/descriptor: multiple copies of package passed to linker:
	@com_github_golang_protobuf//protoc-gen-go/descriptor:descriptor
	@io_bazel_rules_go//proto/wkt:descriptor_go_proto
Set "importmap" to different paths or use 'bazel cquery' to ensure only one
package with this path is linked.
```

**Comment by salrashid123** [comment]
@jayconrod Thanks.   
I used the precompiled `.pb.go` files for the googleapis as well as the gRPC client.   The build rule for a minimal grpc client is [here](https://github.com/salrashid123/go-grpc-bazel-docker#using-pregenerated-protopb-and-gazelle)
