### ISSUE TITLE
go_path: references multiple files (same file)

### ISSUE THREAD

**Issue by amscanne** [bazelbuild/rules_go#2670]
# What version of rules_go are you using?

0.24.3

### What version of gazelle are you using?

0.22.2

### What version of Bazel are you using?

Build label: 3.6.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 6 13:11:20 2020 (1601989880)
Build timestamp: 1601989880
Build timestamp as int: 1601989880

### Does this issue reproduce with the latest releases of all the above?

These are the latest releases.

### What operating system and processor architecture are you using?

Linux, amd64.

### Any other potentially useful information about your toolchain?

Not relevant.

### What did you do?

The bug is reproducible in the following way:

git clone https://github.com/amscanne/gvisor
cd gvisor
git checkout repro_bazel_gopath_bug
bazel build //:gopath

### What did you expect to see?

Successful build of the gopath tree.

### What did you see instead?

ERROR: /usr/local/google/home/ascannell/gvisor/BUILD:74:8: in go_path rule //:gopath: 
Traceback (most recent call last):
        File "/usr/local/google/home/ascannell/.cache/bazel/_bazel_ascannell/3b2705248f065ff20779ff338c114003/external/io_bazel_rules_go/go/private/tools/path.bzl", line 70, column 32, in _go_path_impl
                _add_manifest_entry(manifest_entries, manifest_entry_map, inputs, f, dst)
        File "/usr/local/google/home/ascannell/.cache/bazel/_bazel_ascannell/3b2705248f065ff20779ff338c114003/external/io_bazel_rules_go/go/private/tools/path.bzl", line 184, column 17, in _add_manifest_entry
                fail("{}: references multiple files ({} and {})".format(dst, entry_map[dst], src.path))
Error in fail: src/gvisor.dev/gvisor/pkg/state/addr_range.go: references multiple files (bazel-out/k8-fastbuild-ST-4c64f0b3d5c7/bin/pkg/state/addr_range.go and bazel-out/k8-fastbuild-ST-d17813c235ce/bin/pkg/state/addr_range.go)
ERROR: Analysis of target '//:gopath' failed; build aborted: Analysis of target '//:gopath' failed

**Comment by jayconrod** [comment]
I took a quick look, but this is a large example, and I didn't have time to analyze in detail.

I don't think this is a bug though. The two conflicting files are:

```
bazel-out/k8-fastbuild-ST-4c64f0b3d5c7/bin/pkg/state/addr_range.go
bazel-out/k8-fastbuild-ST-d17813c235ce/bin/pkg/state/addr_range.go
```

These files are built in different configurations (with different hashes). They might have the same content, but they could easily be different. It's not safe to ignore one of them.

My guess the difference is due to `//runsc` being included in the archive. It is a `go_binary` with `pure = True`. That attribute triggers a configuration transition for everything the binary depends on, which probably includes `addr_range.go`. If you depend on `addr_range.go` through a different path, you'd get a conflict like this.

`go_path` is not sophisticated enough to handle files in multiple configurations. I'd recommend removing `pure = True` and similar attributes from `go_binary` targets and instead using flags like `--@io_bazel_rules_go//go/config:pure`.

**Comment by amscanne** [comment]
I don't really understand the comment, because there is only a single path that is including this dependence as far as I can tell:
[//runsc:runsc](https://github.com/google/gvisor/blob/master/BUILD#L79)
 -> //pkg/state:state
 -> //pkg/state:addr_range (which defines addr_range.go)

The files have the exact same content, and are produced by a [non-Go starlark rule](https://github.com/google/gvisor/blob/master/tools/go_stateify/defs.bzl#L17). The Go build configuration really has nothing to do with this particular file, so I'm still super confused and don't understand how this can be WAI. That would mean that //:gopath is simply not capable of handling generated files?

**Comment by jayconrod** [comment]
There are at least two paths. I tried commenting out the binaries, then running this query command:

```
$ bazel cquery 'somepath(//:gopath, //pkg/state:addr_range)'
//:gopath (1e8d0f15339810256dc1c2e13697377b575cc28268297b26fbc9ecf41e986d74)
//pkg/tcpip/sample/tun_tcp_connect:tun_tcp_connect (1e8d0f15339810256dc1c2e13697377b575cc28268297b26fbc9ecf41e986d74)
//pkg/tcpip/link/rawfile:rawfile (1e8d0f15339810256dc1c2e13697377b575cc28268297b26fbc9ecf41e986d74)
//pkg/state:state (1e8d0f15339810256dc1c2e13697377b575cc28268297b26fbc9ecf41e986d74)
//pkg/state:addr_range.go (1e8d0f15339810256dc1c2e13697377b575cc28268297b26fbc9ecf41e986d74)
//pkg/state:addr_range (1e8d0f15339810256dc1c2e13697377b575cc28268297b26fbc9ecf41e986d74)
```

Those libraries are built in the default configuration, which includes the default `@io_bazel_rules_go//go/config:pure` setting (`False`).

`//:runsc` has `pure = True` set. That triggers a transition to a different configuration where `@io_bazel_rules_go//go/config:pure` is `True`. The binary and all its dependencies will be built in that configuration.

The generated content of `addr_range.go` might not depend on the configuration, but it's possible that it does, and `go_path` must assume that's the case. The generating rule could read configuration values from `@io_bazel_rules_go//:go_context_data` and generate different code based on that.

There are a couple workarounds I can think of:

* `go_path` could depend on libraries rather than binaries. For `//runsc`, that would mean defining a `go_library` target with the sources and deps, then embedding that in `go_binary`. `go_path` would only depend on the `go_library`.
* You could try generating files in the `host` or `exec` configuration so they don't conflict across different target configurations. You'd likely need some intermediate rule that gathers sources with `cfg = "exec"` set.
* You could remove the `pure = True` attribute from `//runsc` and build with `--@io_bazel_rules_go//go/config:pure` on the command line.

**Comment by amscanne** [comment]
Ah, thanks for your patience. I think I understand where the extra dependency is snaking in now. Yes, I think the first workaround is best. We need to copy the binary source files manually anyways, since they are generated by go_path.
