### ISSUE TITLE
go_path needs to go through go_reset_transition

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_go#2689]
### What version of rules_go are you using?

```
3f47128dd00917a5a139868766f9ece59f9f4103
```

### What version of Bazel are you using?

```
3.7.0
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

```
macOS / darwin_amd64
```

### What did you do?

The `go_path` binary, when consumed though a platform transition, will match the go platform options (linkmode etc..).

**Comment by steeve** [comment]
Actually, this is true for any binary that is depended even in `exec` configuration.

I have a rule that depends on 2 binaries like this:
```
        "_gobind": attr.label(
            executable = True,
            cfg = "exec",
            default = "@org_golang_x_mobile//cmd/gobind:gobind",
        ),
        "_gobind_wrapper": attr.label(
            executable = True,
            cfg = "exec",
            default = "@co_znly_rules_gomobile//:gobind_wrapper",
        ),
```

I'm not sure what I need to do ?

**Comment by jayconrod** [comment]
I ran into this problem with proto compiler plugins earlier. Unfortunately, transitioning to the `exec` configuration doesn't reset all build settings.

Within rules_go, `go_reset_transition` (in go/private/rules/transition.bzl) can be used to reset the Go build settings to default values. It can be used with the `cfg` parameter instead of `"exec"`.

`go_reset_target` is a rule that forwards Go providers from a target, using `go_reset_transition`. Unfortunately, there's no way to forward all providers (they must be explicitly named), and it can't be used as an executable since executable rules can't provide files from other targets.

Both definitions are pretty limited and expose some rules_go internals, so neither are exported in `//go:def.bzl`. They'll probably work for `go_path`, but you may need to write your own transition for other rules.
