### ISSUE TITLE
Local nogo rules

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2752]
In a large repository, many nogo analyzers are intended to be used on a subset of projects. In the current rules_go design, nogo is registered as part of `go_register_toolchains` globally. With "only_files" and "exclude_files" configuration for analyzers, they only check subset of projects. However, any addition and deletion of nogo analyzers and their "only_files" and "exclude_files" configurations would invalidate the cache for all Go targets, causing very expensive repo-wide rebuild. For example, when we add a new nogo analyzer and configure it to only apply to a specific directory in the repo, the cache for all Go targets, most of them are outside that directory, are invalidated.

Is it possible to create local `nogo` rules and apply them to a subset of Go targets? For example, adding a `nogo` attribute to `go_library` to take a list of `nogo` rules that the `go_library` runs besides the ones registered in `go_register_toolchains`.

**Comment by jayconrod** [comment]
The discussion in #2513 is pretty similar.

Unfortunately, this is not possible today. It's definitely something we thought about when designing nogo, but I haven't had bandwidth to complete the design.

Part of the early nogo design was that we'd three sets of analyzers:

* Global analyzers would be applied to all packages (except those excluded by global configuration). This would be useful for very general analyses with no false positives, like those enabled in `go test`. This is all that's implemented today.
* Top-down analyzers would be specified by a binary or test and would be applied to everything it depends on (maybe using an aspect).
* Bottom-up analyzers would be specified by a library and would be applied to everything using that library (perhaps verifying the library's usage).

Analyzers probably need to be compiled into the nogo binary, since it's part of the toolchain, but there might be some ways to get around that. Configuration is a bit harder: in order to avoid invalidating the cache after a configuration change, we'd need to make more configuration visible during analysis.

**Comment by jayconrod** [comment]
Closing in favor of #2513
