### ISSUE TITLE
Test output not copied to the bazel-testlogs directory

### ISSUE THREAD

**Issue by dejan-lokar** [bazelbuild/rules_go#2756]
### What version of rules_go are you using?
v0.25.0

### What version of gazelle are you using?
v0.22.2

### What version of Bazel are you using?
3.7.1

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
OSX amd64

### What did you do?
I ran a test with the `race` flag enabled.
```
go_test(
    name = "go_default_test",
    race = "on",
    ...
)
```

### What did you expect to see?
I expected test outputs to be copied to the `bazel-testlogs` directory.

### What did you see instead?
Test outputs are not copied to the `bazel-testlogs` directory. They can still be found in the `bazel-out` directory but that is not as convenient.

Disabling the `race` flag fixes the problem.

**Comment by jayconrod** [comment]
Sorry, this can't be changed in rules_go. Tests just write their output to stdout and stderr. Bazel directs that output to log files. rules_go has no control over that.

What's probably happening is that `bazel-testlogs` is a symbolic link to a directory specific to the default configuration in `bazel-out`. On my system, it's `/private/var/tmp/_bazel_jayconrod/60e122df6a2a16ab6af86d77e9a71ec5/execroot/__main__/bazel-out/darwin-fastbuild/testlogs`. When `race = "on"` is set, the output is written to `darwin-fastbuild-ST-fcb5cf22ec9a` instead of `darwin-fastbuild`. Bazel separates the output by configuration so that it's possible to run the same test in multiple configurations.
