### ISSUE TITLE
Calling go_register_toolchains(version) twice causes a failure

### ISSUE THREAD

**Issue by rgs1** [bazelbuild/rules_go#2761]
rules_docker breaks for us after updating to rules_go 0.25.0, though this patch fixes it for us:

https://github.com/bazelbuild/rules_docker/pull/1700

The problem is that in our setup, `go_register_toolchains()` gets called more than once. Simply passing the version isn't a
solution, since after the first call an sdk rule becomes available and then we hit:

```
go_register_toolchains: version set after go sdk rule declared
```

Would it be ok to have `go_register_toolchains()` return gracefully when an sdk is available do to a previous call instead of failing here:

https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl#L405

?

**Comment by rgs1** [comment]
cc: @fishcakez

**Comment by jayconrod** [comment]
I think this is the right behavior for `go_register_toolchains`. If it's called twice with two different versions, which one should be selected? It's much better to fail with an error instead of leaving it ambiguous.

You can resolve this in your workspace by calling [`go_download_sdk`](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go-download-sdk) explicitly in your WORKSPACE instead of `go_register_toolchains`, before calling the function from rules_docker.

`go_register_toolchains` may be called without a version (as in rules_docker) if it's preceded by a call to `go_download_sdk` or one of the other similar rules.

**Comment by rgs1** [comment]
That mostly works (I had to massage things a bit), thanks @jayconrod.
