### ISSUE TITLE
Create a new_local_go_repository rule

### ISSUE THREAD

**Issue by gbrail** [bazelbuild/rules_go#283]
It'd be really really handy to have a "new_local_go_repository" rule for WORKSPACE that works just like "new_local_repository", but automatically generates a BUILD file using the generic "go" rules.

This would greatly ease my team's life, because we have a multi-repo Go project and the Go world isn't really set up for that. Everything is great for a build that pulls all the components remotely from GitHub or elsewhere, but it's painful if we want to check out some of the submodules locally and use them to generate a developer build.

It'd really help to be able to put in something like this:

new_local_go_repository(
  name = "com_github_foo_bar",
  importpath = "github.com/foo/bar",
  path = "/home/go/src/github.com/foo/bar",
)

This rule would work just like "new_local_repository," except it would generate a BUILD file the same way that Bazel generates build files for new_go_repository and others.

**Comment by jayconrod** [comment]
It would be nice to have a repository rule like this. I'm not sure how it would work though. [repository_ctx](https://www.bazel.build/versions/master/docs/skylark/lib/repository_ctx.html) has primitives for downloading and extracting archives, but it doesn't have any methods for dealing with local repositories.

Maybe this would need to be a repository rule that generates BUILD files for a given repository, which would be a local_repository. There could be a macro that ties that together.

**Comment by ianthehat** [comment]
I believe as of #446 this use case is now covered, but I want to check I understand your needs correctly.
If you use
```python
go_repository(
    name = "com_github_foo_bar",
    importpath = "github.com/foo/bar",
    vcs = "git",
    remote = "/home/go/src/github.com/foo/bar",
    commit = "a_commit_sha",
)
```
then a copy of the local repository will be cloned into your build externals at the specified commit, and then have build files added to it by gazelle.

**Comment by gbrail** [comment]
I will have a chance to try this early next week the way things look so
I'll let you know...

**Comment by jayconrod** [comment]
Not with `go_repository` unfortunately. The path is passed directly to `golang.org/x/tools/go/vcs.RepoRoot.Repo`, so we support whatever that library supports. In the future, we will recommend using `new_git_repository` (or `new_local_repository` in this case) with flat BUILD files instead of `go_repository`. `new_local_repository` supports relative paths.

You can generate a flat build file for a repository by running `gazelle -repo_root . -go_prefix <prefix> -experimental_flat` from that repository's root directory. Copy this somewhere in your own repository (for example, to `third_party/<repo_name>.bazel`). Then reference this from the `new_local_repository` rule.

Sorry this is an inconvenient process at the moment. I'm working on automating it before we officially deprecate `go_repository`.

**Comment by nictuku** [comment]
I'm trying to import a repository containing Go code. `go_repository` almost works:

```
go_repository(
    name = "com_github_yourbase_test_ci",
    importpath = "github.com/yourbase/test-ci",
    build_file_generation = "on",
    build_file_name = "BUILD.bazel",
    urls = ["file:///Users/yves/src/github.com/yourbase/test-ci"],
#    commit = "5cdc5a4e30ad081c0eb1b3dad7fccd86256c6c0a",
)
``` 
The only problem is that the `commit` requirement makes this very inconvenient, when compared to the way `local_repository` works.

With the plans of deprecating `go_repository`, will you support `local_repository` as a first-class citizen for pulling in Go code? 

Thanks!

**Comment by jayconrod** [comment]
@nictuku I've been experimenting with an `overlay_repository` rule as a potential replacement for `go_repository`. It's intended to download a repository via HTTP or VCS, then copy in a set of files (pre-generated build files). It should be simple to extend it to work with local paths. If that works for you, I can push that out in bazelbuild/bazel-gazelle in the next day or two.

If that doesn't work, you might want to try writing your own [repository rule](https://docs.bazel.build/versions/master/skylark/repository_rules.html) for this.

**Comment by nictuku** [comment]
I'm not familiar with `overlay_repository` but it seems like it would work.

On Feb 5, 2018 9:19 AM, "Jay Conrod" <notifications@github.com> wrote:

@nictuku <https://github.com/nictuku> I've been experimenting with an
overlay_repository rule as a potential replacement for go_repository. It's
intended to download a repository via HTTP or VCS, then copy in a set of
files (pre-generated build files). It should be simple to extend it to work
with local paths. If that works for you, I can push that out in
bazelbuild/bazel-gazelle in the next day or two.

If that doesn't work, you might want to try writing your own repository rule
<https://docs.bazel.build/versions/master/skylark/repository_rules.html>
for this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/rules_go/issues/283#issuecomment-363154819>,
or mute the thread

**Comment by kaoet** [comment]
Please also provide `local_repository` in `overlay_repository` rules to use relative paths in workspace

**Comment by pcj** [comment]
If I need to temporarily hack in an external repository (to figure out what it is doing, for example), I've done the following (not pretty, but it works):

1. make a `go_repository` rule as usual, let gazelle do its magic.
2. Copy the entire thing, including all the generated BUILD.bazel file into a work dir, like `cp -rp $(bazel info output_base)/external/go_foo ~/github.com/go_foo`
3. Temporarily substitute `@go_foo` by now importing go_foo as a `local_repository` (no need to generate build files again, it's ready to go).  
4. Hack away, bazel picks up changes in local repo as needed.

**Comment by gonzojive** [comment]
I needed this recently, so I made this tool that

* watches a directory for changes
* runs an HTTP server that serves a zip file with the contents of the directory
* updates a WORKSPACE rule whenever the directory's contents change, pointing at the HTTP server using a new sha256

It probably would have been better to do something in starlark, but this should work: https://github.com/gonzojive/rules_go_local_repo
