### ISSUE TITLE
Gazelle spams "finding module for path"

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_go#2876]
### What version of rules_go are you using?

v0.26.0

### What version of gazelle are you using?

v0.23.0

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

linux/amd64

### What did you do?

Build a relatively normal Go project which imports a package which in turn imports `github.com/sirupsen/logrus`.

### What did you expect to see?

A quiet build.

### What did you see instead?

Thousands of lines of

```
gazelle: finding module path for import github.com/Sirupsen/logrus: go get: github.com/Sirupsen/logrus@v1.0.6 updating to
        github.com/Sirupsen/logrus@v1.8.1: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

Why is Gazelle even trying to resolve dependencies at build time?

**Comment by robfig** [comment]
I agree that "go" output has become very verbose with modules, and that is unwelcome in a bazel workspace. I have also experienced the same phenomenon of thousands of lines of log spam, possibly all related to case mismatches like the one you pasted. 

Thoughts / options:

* Suppress output entirely. This might be undesirable since it could hide true errors. 
* Recognize these specific warnings. We could write code to recognize this warning and elide it, although that seems somewhat brittle / unpleasant.
* Open an upstream issue. The output from go modules seems similar in nature to what you get from `go build -v` or `go install -v`. Maybe `go mod` should be silent on success, as other commands are, and only print those details when requested with `-v`. 

@bazelbuild/go-maintainers, what are your thoughts on the direction to take?

**Comment by robfig** [comment]
This issue is also about suppressing gratuitous output:
https://github.com/bazelbuild/rules_go/issues/2897

**Comment by uhthomas** [comment]
Potentially fixed by https://github.com/bazelbuild/bazel-gazelle/pull/1201 and https://github.com/bazelbuild/bazel-gazelle/pull/1205?
