### ISSUE TITLE
new_go_repository should export files other than .go

### ISSUE THREAD

**Issue by rosun82** [bazelbuild/rules_go#294]
Amazon AWS unittest failure because of this.

bazel test -c opt @com_github_aws_aws_sdk_go//...

@com_github_aws_aws_sdk_go//aws/credentials:go_default_test              FAILED in 1 out of 2 in 0.1s
@com_github_aws_aws_sdk_go//aws/session:go_default_test                  FAILED in 1 out of 2 in 0.1s
@com_github_aws_aws_sdk_go//vendor/github.com/go-ini/ini:go_default_test FAILED in 1 out of 2 in 0.1s

The reason is aws/credentials/example.ini is not exported from BUILD but used in unittest.

**Comment by pmbethe09** [comment]
How would we know to reference that file, or should we just always add such files to a 'data' attribute?

**Comment by jayconrod** [comment]
I think Gazelle (which generates BUILD files inside new_go_repository) should add files in testdata directories to the data attribute of go_default_test rules, probably through a glob. The go tool has some special handling of this directory already, and we probably should, too.

Tests probably still won't pass because the initial directory of the test is logically the root of the repository, not the directory of the test sources.

I don't think there's any need for Gazelle to add other data files to the data attribute or export them. Custom BUILD files should be used if that's desired.

**Comment by rosun82** [comment]
I like pmbethe09's solution better, maybe adding all these files to a target and put data=target in all unittest.

The point is, there could (should) be many open source go projects, where the author put data files in the code folder and "go test" happily passes (cannot blame them as they usually do not have 3 Googlers reviewing their code, and they do not start from using blaze). When you import those projects as bazel project, suddenly a ton of unittest fails, which creates a lot of trouble for everyone.

**Comment by jayconrod** [comment]
How would Gazelle know which files to include though? Including a file makes it available for a test, but the test has to be re-run whenever that file changes. Data files also have to be copied when tests are run remotely. That might be annoying if a directory contains generated documentation or a definition index, or something else that changes frequently.

I could see making this behavior available behind an option, but I don't think it should be the default.

**Comment by pmbethe09** [comment]
And separate point of @jayconrod, should the rules_go testrunner for go_test change to the code directory, which would be inline with how 'go test' works, but different than the bazel-style of running from the repository-root?

**Comment by jayconrod** [comment]
The directory issue is a really good point. We should support both conventions. I've filed #299 to track that.

**Comment by jayconrod** [comment]
Closing this issue, since I don't think there's anything else to do. If a `testdata` directory exists, `gazelle` now adds a `filegroup` on it, and a `data` dependency in any `go_test` rules. Other data dependencies need to be added manually.

#162 is still open and will track custom working directories for tests. The default behavior is for tests to run in the directory where the `go_test` rule was defined.
