### ISSUE TITLE
make `_detect_host_platform` public

### ISSUE THREAD

**Issue by tek** [bazelbuild/rules_go#2946]
In `rules_nixpkgs`, we need to determine the host platform to set up the Go toolchain, so we copied the function from `rules_go`:

https://github.com/tweag/rules_nixpkgs/blob/master/nixpkgs/toolchains/go.bzl#L14

Would it be acceptable to allow this function to be imported?

**Comment by robfig** [comment]
We'd prefer to avoid making that part of the public interface so that we can retain the ability to refactor / move / rename it in the future without it being a breaking change. Sorry about that. A truly dedicated consumer of the function could always use the [http_archive.patches](https://docs.bazel.build/versions/main/repo/http.html#http_archive-patches) attribute to rename the function so that it can be imported, but that doesn't seem advisable either.

**Comment by aherrmann** [comment]
> A truly dedicated consumer of the function could always use the [http_archive.patches](https://docs.bazel.build/versions/main/repo/http.html#http_archive-patches) attribute to rename the function so that it can be imported, but that doesn't seem advisable either.

Indeed, that would not be a good solution for rules_nixpkgs, as it itself is going to be a dependency of other projects, making rules_go a transitive dependency.
