### ISSUE TITLE
Why gazelle skips the directories which begin with '_'

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/rules_go#298]
see https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/packages/walk.go#L41

The case is, I use Godep to manage my external dependencies in my project. So my project has the directories like that 
```
|- src/
     |- myproject/
          |- Godeps/
               |- Godeps.json
               |- _workspace/
```
The problem is, if I prefer to use vendoring, and after I run `gazelle` under `myproject`, no `BUILD` files are generated in the directories under `_workspace` .

**Comment by jayconrod** [comment]
Gazelle is emulating the behavior of `golang.org/x/tools/go/buildutil`. See [allpackages.go](https://github.com/golang/tools/blob/f60b69ed8cd7a29e91f87050ae23a29581a0f367/go/buildutil/allpackages.go#L93) for the equivalent logic. It excludes directories starting with ".", "_", since they're considered hidden. It also excludes "testdata".

I'm not super-familiar with Godep, but I'm surprised that dependencies are ending up in Godeps/_workspace. Shouldn't they be in vendor? If you run Gazelle with `-external vendored`, it will resolve imports of external packages to the vendor directory.

**Comment by GinFungYJF** [comment]
Got it! Thanks!
