### ISSUE TITLE
Supporting the incoming bzlmod

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#3020]
The new dependency manager for bazel, bzlmod, will be available on Bazel 5.0. Both rules_go and Gazelle need to support it. Work needed:

* Make rules_go and Gazelle Bazel modules
* implement a module rule for Go
* Update `gazelle update-repos` to work with Bazel modules

**Comment by sluongng** [comment]
Will these changes be compatible with 4.x LTS releases? Or are we forcing everyone to move to 5.x?

If its the latter, I would suggest waiting until after Go 1.18 release to make the switch?

**Comment by fmeum** [comment]
It's possible to support usage via bzlmod while staying backwards compatible with Bazel 4.x. Modules can apply arbitrary patches to release archives, so every change that wouldn't be compatible can be moved into a patch.

There is one step that would require more widespread changes: Making rules_go available with module name `rules_go` rather than `io_bazel_rules_go`. This can mostly be done in a way that still allows `WORKSPACE` users to refer to it the old way, but would make it necessary to patch the patches that add pre-generated BUILD to Go dependencies of rules_go itself.

**Comment by fmeum** [comment]
Does anyone already have thoughts about how SDK downloads would work with extensions? The existing repository rules could be ported to module extensions quite faithfully, but is there anything that you would like to change about their API now that there is a chance?

**Comment by achew22** [comment]
@fmeum, could you write out (or just point to) what part of the APIs would be solidified by [doing the bzlmod](https://youtu.be/fiOMbqPHFwo?t=29)? Would it just be the `go_*_sdk` targets that would become immutable? How much pain would there be if we want to change those in 2 years?

**Comment by davidzchen** [comment]
Has there been any updates on this?

**Comment by fmeum** [comment]
Yes, see https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md
