### ISSUE TITLE
go_library to support gotags

### ISSUE THREAD

**Issue by edieYoung** [bazelbuild/rules_go#3203]
Hi there, we have a library which requires custom build tags to build it (because there is a TinyGo specific target that cannot be complied by Bazel for now https://github.com/bazelbuild/rules_go/issues/3197, and we want to exclude it using go build tags).
Can we pass in the gotags to it? Why does go_library not support gotags?  We found this previous issue similarly https://github.com/bazelbuild/rules_go/issues/1351, but it seems only added support to go_binary and go_test, not go_library.

**Comment by sluongng** [comment]
Adding "manual" is a great idea!

We also tinkered with "--define gotags=" but that would have set it up globally for entire repo.

**Comment by fmeum** [comment]
Actually, with all the transitions around, maybe go_library should be manual by default to prevent build failure or duplication? @linzhp Have you thought about this before?

**Comment by achew22** [comment]
One of the nice things about having go_libraries not be manual is that they will perform type/syntax checking in most CI systems that `bazel build //...` as the last step, or I'm misunderstanding something possibly?

**Comment by fmeum** [comment]
Yes, but they would still typecheck if they were dependencies of something else. 

Having thought about this some more, I think that the current semantics of `//...` aren't ideal in the presence of transitions anymore. It would make far more sense if `//...` ended up being equivalent to specifying all targets that aren't dependencies of other targets matched by the wildcard (i.e. the nodes in the directed dependency graph with no incoming edges). I will see whether I can start this discussion in a more general venue.

Since adding `gotags` to `go_library` would have potentially very surprising semantics, I would prefer to close this issue with the recommendation to use `tags = ["manual"]` as a workaround until Bazel as a whole does a better of dealing with intermediate targets that rely on transitions to build correctly.

**Comment by sluongng** [comment]
```
# .bazelrc
build --define gotags=containers_image_openpgp
```

A quick hack for use cases where you could apply a global go tag to all `go_library`.
`gotags` accept comma-separated values like `gotags=tag_a,tag_b`.

`"manual"` bazel tag seems like a decent workaround for now. I can see cases where a package was primarily made for external consumption (imported by repositories outside of Bazel workspace) to have a `go_library` and does not `go_binary` depending on it. However, it should be relatively forward to create a workaround:
- Adjust go build tag to give it a sensible default
- Add a dummy test (and go_test) that depends on the library, then mark the library with `"manual"`

**Comment by smocherla-brex** [comment]
Following up on a usecase here where having `build_tags` on `go_library` targets could perhaps help. We use this go package https://github.com/wundergraph/cosmo/blob/main/composition-go/vm_v8.go with `go_repository` as a third-party dep. We pass `build_tags` with the value `wg_composition_v8` in the `go_repository` but depending on the library fails compilation because the tags are not passed in compilation. Adding `--define gotags` solves the problem but it feels like this would be cleaner if we could apply `gotags` on the `go_library` targets in the third-party package and not pass `--define` which applies globally, and not just for `go_binary` or `go_test` targets. Would the recommendation still be to pass `gotags` for our leaf targets in the repo (`go_binary`/`go_test`) and make the compilation work or possibly support this for `go_library` targets in third-party deps?  Doing the former does seem like a fair bit of work if you have many targets in the repo that depend on such a package but not the majority. Or perhaps ability to scope gotags to certain packages would be nice through `--define`.

**Comment by oakad** [comment]
I'd vote for this issue to be reopened and acted upon.

1. Go build tags are used for the same purpose as C `ifdef`s, and `cc_library` has no issue with allowing custom `defines` on each and every rule.
2. The library `gotags` attribute may be filtered to exclude toolchain defined tags. After all, the commonly desirable behavior for custom tags (those, not recognized by Go compiler toolchain) is to be applied only locally, to the current target.

The main victim of the current state of affairs is gopls and any IDE depending on it (and thus, poor, suffering developers). While Bazel itself requires the user to explicitly enumerate dependencies for each target variant, allowing multiple implementation variants to co-exist in the same directory, gopls chokes on such things outright (as there will be multiple definitions of symbols around).
