### ISSUE TITLE
Non-go deps built twice with gotags

### ISSUE THREAD

**Issue by ripatel-fd** [bazelbuild/rules_go#3430]
### What version of rules_go are you using?

v0.38.0

### What version of Bazel are you using?

6.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

amd64 RHEL 8

### Any other potentially useful information about your toolchain?

GCC 8.5.0

### What did you do?

Run https://github.com/terorie/rules_go_bug

### What did you expect to see?

Dep tree as follows `go_test -> go_library -> cc_library`.

The `go_test` has one string in `gotags` set.

When I `bazel build` the `go_test` and `go_library`, I expect `cc_library` to be only built once.

### What did you see instead?

`cc_library` is built twice.

### Related

 - https://github.com/bazelbuild/rules_go/pull/3108 (The PR that was originally supported to fix it) 
 - https://github.com/bazelbuild/rules_go/pull/3116 (suspected regression)

**Comment by fmeum** [comment]
I don't think this is a regression. With v0.33.0, which doesn't contain https://github.com/bazelbuild/rules_go/commit/b0b7d85e10e6ae882ca13453e3c525a895c83181, running `bazel build --nobuild //... && bazel cquery //clib:clib` (twice, not sure why that's necessary), you can see that the C library is built twice.

The fix is to use a recent version of rules_go, Bazel 6, and the flag `--experimental_output_directory_naming_scheme=diff_against_baseline`. I am working on getting this enabled by default in Bazel 6.1.

**Comment by fmeum** [comment]
Well, let's call it a missing optimization. But yes, short of ditching transitions entirely or using quite complex and fragile tricks, there is nothing rules_go can do about this by itself.

**Comment by fmeum** [comment]
Will be fixed by default in Bazel 7 and can be fixed by setting `--experimental_output_directory_naming_scheme=diff_against_dynamic_baseline` in Bazel 6.4.0.
