### ISSUE TITLE
Runfiles allows invalid file path

### ISSUE THREAD

**Issue by jgao54** [bazelbuild/rules_go#3726]
### What version of rules_go are you using?

0.42.0

### What version of gazelle are you using?

0.33.0

### What version of Bazel are you using?

6.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Apple M1

### What did you do?

While upgrading the runfiles library to `//go/runfiles`, it appears that runfiles.Rlocation does not error if the path is absolute or invalid. For example:
```
# any absolute path
p1, err1 := runfiles.Rlocation("/foo/bar")

# non-existent path
p2, err2 := runfiles.Rlocation("myworkspace/invalid")

```

With `bazel.Runfile`, the method will throw an error in both cases with:
```
Runfile /foo/bar: could not locate file
Runfile myworkspace/invalid: could not locate file
```

This makes the the deprecation non-trivial to upgrade.

### What did you expect to see?

Error given path is invalid.

### What did you see instead?

err1 and err2 are nil; p1 and p2 return `/foo/bar` and `<abs_runfile_path>/myworkspace/invalid` respectively.

**Comment by fmeum** [comment]
Other runfiles libraries return an absolute path unchanged, so that's something we should also be doing here as well. Would you be interested in sending a PR for this?

Not failing on paths that don't exist when a runfiles directory is used is, for better or worse, consistent with the behavior of most other runfiles libraries (Bash is the odd one here). In the interest of backwards compatibility and consistency, we probably shouldn't change that, even if the alternative behavior may make a bit more sense. However, ultimately you will do something with the file anyway and then learn that it didn't exist without performing extra I/O.

**Comment by jgao54** [comment]
> Other runfiles libraries return an absolute path unchanged, so that's something we should also be doing here as well. 

This is the current behavior of runfiles.Rlocation. I just didn't realize this is the intended behavior.

> Not failing on paths that don't exist when a runfiles directory is used is.

This is also the current behavior of runfiles.Rlocation.

sounds like in both cases, it's intended and consistent with other rules?

**Comment by fmeum** [comment]
Returning an absolute path unchanged is intended as it makes it easier to accept `argv` arguments that may either be absolute or runfiles paths. 

Accepting non-existent relative paths may be considered a "spec bug" as it makes the behavior differ between Windows and other OSes. But consistency wins, I guess, and you can always produce your own wrapper that checks for existence. 

Thanks for bringing this up though, I agree that these libraries have rough edges that in hindsight probably could have been done better.
