### ISSUE TITLE
test timeout errors is a little funky

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#397]
I've got 4 Go tests inside a test target, and one of them ran into an infinite loop and the reporting of the timeout was a little funky. I'm not sure if this is a bazel thing or a rules_go thing.

When the test timed out, I got some logging info from the logging (per usual), but didn't get told the exact test that timed out, just the target, and it says there were was a timeout in "1 out of 2" which I'm not sure it means. I've only got one test target I hit up, so maybe the `2` is the number of tests it managed to run? Would be nice for the count to be all the tests available, maybe.

The output I got from `bazel test go/svc/muxtov:go_default_test --test_output=all` was:

```
Target //go/svc/muxtov:go_default_test up-to-date:
  bazel-bin/go/svc/muxtov/go_default_test.a
  bazel-bin/go/svc/muxtov/go_default_test_main_test.a
  bazel-bin/go/svc/muxtov/go_default_test_main_test.go
  bazel-bin/go/svc/muxtov/go_default_test
INFO: Elapsed time: 300.419s, Critical Path: 300.11s
//go/svc/muxtov:go_default_test                                         TIMEOUT in 1 out of 2 in 300.0s
  /private/var/tmp/_bazel_jmhodges/ee957dabdee1b1a9e1f2fe90369cf80f/execroot/founding/bazel-out/local-fastbuild/testlogs/go/svc/muxtov/go_default_test/test.log

Executed 1 out of 1 test: 1 fails locally.
```

The same stuff was in the test log file.

**Comment by jayconrod** [comment]
Bazel doesn't have much awareness of what happens inside a test binary. It just runs the binary, checks the return code when it's done, and kills it if it takes too long. The binary itself is responsible for printing outcomes of individual test cases, and we rely on the "testing" package for that. You can run Bazel with `--test_arg=-test.timeout=30s` to make the "testing" package enforce the timeout instead of Bazel. That will print a stack for all goroutines.

Doesn't sound like it's the case in this test, but if you need to increase the time limit for long running tests, you can do so with the `size` or `timeout` attributes on `go_test`. See the [Bazel test encyclopedia](https://bazel.build/versions/master/docs/test-encyclopedia.html#role-of-the-test-runner) for more info.

I believe the "1 out of 2" output is related to the number of times Bazel ran the test. If you set `flaky = True` on a `cc_test`, It says "FAILED in 3 out of 4 in 0.1s" because Bazel ran the test three times. The second number seems too big though.

**Comment by jmhodges** [comment]
Hm, k! Thanks!
