### ISSUE TITLE
Gazelle doesn't generate BUILD files for github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore

### ISSUE THREAD

**Issue by tomwilkie** [bazelbuild/rules_go#423]
I suspect because of the underscore in the package name `_thrift`.

**Comment by jayconrod** [comment]
This is indeed because of the the leading underscore in `_thrift`. Gazelle treats this as a hidden directory (it also ignores names that start with `.`) and avoids recursing into it.

I'm not sure this is consistent with anything in the Go toolchain. If not, this is a bug, and we should fix it. `go/build` does ignore files that start with `_`, but that doesn't affect directories.

As a workaround, you should be able to run Gazelle manually for that directory (pass the directory name on the command line).

**Comment by tomwilkie** [comment]
Thanks for the response!  I've manually created the BUILD files in those directories for now.  I'd like to get to the point where gazelle can automatically create them, and then I don't have to check them in.

**Comment by tomwilkie** [comment]
Looks like we've regressed on this one; minimal reproduction at: https://github.com/tomwilkie/gazelle-test

```bash
$ # go fetch latest vendored dependancies
$ dep ensure && dep prune 

$ # update BUILD.bazel files
$ bazel run //:gazelle  
..............
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle_script.bash
  bazel-bin/gazelle
INFO: Elapsed time: 84.195s, Critical Path: 5.27s

INFO: Running command line: bazel-bin/gazelle

$ # try and build
$ bazel build //:test
..............
ERROR: /Users/twilkie/Documents/src/github.com/tomwilkie/gazelle-test/BUILD.bazel:13:1: no such package 'vendor/github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore': BUILD file not found on package path and referenced by '//:go_default_library'.
ERROR: Analysis of target '//:test' failed; build aborted.
INFO: Elapsed time: 12.356s

$ ls vendor/github.com/openzipkin/zipkin-go-opentracing/_thrift/gen-go/zipkincore
constants.go	ttypes.go
```
