### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by Mistobaan** [bazelbuild/rules_go#44]
Why re-implement all the logic to compile the golang sources instead of using the standard go tools from within bazel i.e. with a genrule or similar ?

**Comment by yugui** [comment]
I don't know the exact discussion which initially happened. I guess @damienmg knows some of past discussions, though.

But several factors which support the current implementation come to my mind.
* We cannot simply build the final product with "go build" because Bazel requires fine-grained and deterministic rules to take two of `{Fast, Correct}`.  Instead, we have to build each package in its own rule.
* We have to build a fake go source tree structure in any way every time we build a package to support `go_prefix` both in a non-sandboxed environment and in a sandboxed or distributed execution environment.
  * Assuming this "fake tree" operation is inevitable, `go build` is not much more convenient than `go compile -pack`.
    Or rather it restricts flexibility to support additional features like cgo.
  * Actually it would be impossible to build a cgo-enabled package which depends on another `cc_library` which exposes a public header if we used `go build`.

**Comment by Mistobaan** [comment]
>Actually it would be impossible to build a cgo-enabled package which depends on another cc_library which exposes a public header if we used go build
I understand this point. 
But for all the other cases the motivation feels a bit weak.

Ideally we have a basic set of rules and a tool inside this repository that parses the output of `go build -work -n` or/and `go generate ./...` and creates a local "def.gen.bzl" file that needs to be loaded from "BUILD". 
Generating the BUILD file seems wrong, because I can't think of a right way of supporting the external `cc_library` case ( see for example the https://github.com/tensorflow/tensorflow/tree/go/tensorflow/contrib/go that requires a library built in another folder ).

**Comment by yugui** [comment]
> Ideally we have a basic set of rules and a tool inside this repository that parses the output of go build -work -n or/and go generate ./... and creates a local "def.gen.bzl" file that needs to be loaded from "BUILD". 

That sounds very interesting.  Let me ask several questions to understand better.
* What is the difference between `def.gen.bzl` and generating `BUILD` files?
   Although both must run before loading phase.
* How can we build code generator binaries required by `go generate`?

> see for example the https://github.com/tensorflow/tensorflow/tree/go/tensorflow/contrib/go that requires a library built in another folder.

Right.  In other words, usually a Go package has less information than `BUILD`, e.g. dependency to `cc_library`, `license` or `visibility`.  So we still cannot avoid manually modifying the generated files.
And the BUILD file generator must respect such manual configurations.

IIUC, Bazel requires users to manually maintain dependency graph and node attributes. BUILD file generators help users to maintain but generators don't do everything for users.

**Comment by Mistobaan** [comment]
I posted a question with some example code of how I think I could generate a BUILD file 
http://stackoverflow.com/questions/38358504/can-i-generate-a-build-file-in-bazel
Ideally we add a tool to rules_go that does this step and uses the buildifier core package to update existing rules.

**Comment by jayconrod** [comment]
Closing some old issues. Gazelle solves the problem of generating BUILD files now.
