### ISSUE TITLE
Make proto rules more queryable

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#440]
`go_proto_library` is a macro, which combines a private rule (`_go_proto_library_gen`) with `go_library`. This makes it hard to list proto libraries with `bazel query`. It should be converted into a rule.

We should consider exposing generated .pb.go files somehow in case people want to depend on those directly.

**Comment by pmbethe09** [comment]
The reason go_proto_library is a macro, is because historically a rule could not call another rule -- that is the case in internal Java and I believe also in skylark.  So in order to take advantage of go_library, the top-level was written as a macro.  If we were to change go_proto_library to a rule, we would need to figure out a way for go_library to provide some sort of public go_library_impl that is not a rule and could be called out to.

The generated  .pb.go files should already be available for a given go_proto_library(name="foo"...) at the '_protos' suffix target of ":foo_protos"

**Comment by pmbethe09** [comment]
However, I believe the new world is to use the core 'proto_library' to build a file-graph, and then write a go_proto_library as an aspect 
https://bazel.build/versions/master/docs/skylark/aspects.html

**Comment by ianthehat** [comment]
We need to rethink the proto rules in terms of the proto_library system, using aspects anyway, we should revisit this at the same time.

**Comment by jayconrod** [comment]
+1 to rebuilding this with aspects.

The main question I have is whether we should produce library binaries directly or .pb.go files that can be incorporated into `go_library` explicitly. If the former, we could use `_emit_go_compile_action`. It can be moved to a .bzl file in go/private which would not be visible outside of rules_go.

**Comment by ianthehat** [comment]
When not using bazel it is possible to add more go files to the same package as the ones generated by protoc to provide helpers and extra methods. If we go straight to a go library we prevent this use case, so I think we need to try to produce the .pb.go files and allow them to be used in a normal library declaration.
