### ISSUE TITLE
 Failed to generate BUILD files for library which has a dir named 'build'

### ISSUE THREAD

**Issue by lazutkin** [bazelbuild/rules_go#441]
I've found that `new_go_repository` cannot generate BUILD files for some libs like

```
new_go_repository(
    name = "com_github_docker_docker",
    commit = "<hash>",
    remote = "https://github.com/moby/moby",
    vcs = "git",
    importpath = "github.com/docker/docker",
)

```

because of error:

```
ERROR: /<....>/external/com_github_fsouza_go_dockerclient/BUILD:5:1: no such package '@com_github_docker_docker//pkg/stdcopy': failed to generate BUILD files for github.com/docker/docker: 2017/05/05 21:55:53 open /<....>/external/com_github_docker_docker/api/server/router/BUILD: is a directory
 and referenced by '@com_github_fsouza_go_dockerclient//:go_default_library'.
```

So I just want to know if there is any known workarounds?

**Comment by jayconrod** [comment]
This happens on case-insensitive file systems (common on macOS, Windows) because the `BUILD` file name collides with directories named `build`.

Bazel accepts files named `BUILD.bazel` since 0.4. We generate these by default in `new_go_repository` since #383. Before that, you can add the argument `build_file_name = "BUILD.bazel"` to `new_go_repository` rules that need it.
