### ISSUE TITLE
Gazelle fails on case-insensitive file systems when repository contains file named "build"

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_go#456]
When a repository contains a file named "build" for example https://github.com/coreos/fleet

Gazelle will fail to generate on a case-insensitive FS even when given the "build_file_name" flag with "BUILD.bazel". I'm presuming this is because findBuildFile uses the hardcoded list of build file names, and will return the "build" file, which Gazelle will attempt to merge with.

Workaround atm is to delete the file in a fork of the repo but potential fix proposals are

1) Allow buildFileNames to be passed in as a flag
2) Add a --[no]merge flag to Gazelle, as I'm not sure it should be attempting to merge w/ build files in external repositories anyway

**Comment by ains** [comment]
Currently opted for 1) and defaulting to build_file_name == valid_build_file_names for new_go_repository which unblocks us for now but open to discussing better issues.

https://github.com/improbable-io/rules_go/commit/4f0fb98aa0e6158c4e1d27ab6927e39558e5f4df

**Comment by ianthehat** [comment]
The approach I took when fixing this issue for the go_repository rule detecting the root build file was to check whether the "build" file is a file, rather than just that it exists, and always use BUILD.bazel when a directory is found. I think the same thing would work inside gazelle, and cover this case easily, I will try to add both a test and a fix.

**Comment by ains** [comment]
The issue with coreos/pkg coreos/fleet and coreos/etcd is that the "build" file is a file, it's just a bash script as opposed to a bazel build file, but the fact that it exists / is a file is good enough for Gazelle

**Comment by ianthehat** [comment]
Sorry, I misunderstood problem.
Honestly I think the right answer is for all tooling to work only with BUILD.bazel by default, and for BUILD files to be a thing for the history books, the more explicit name is better for almost every possible use case. However, given that is not the case for where we are right now, I think your solution is mostly the best choice.
I think I would probably change it so that we don't take a new flag, but just split build buildFileName on commas and if there are multiple entries, the first one is used when generating new files, otherwise we start getting into the crazy world of "what if the value of buildFileName is not in validBuildFileNames".

**Comment by ains** [comment]
@ianthehat agreed, will clean up commit and send a PR
