### ISSUE TITLE
Download all the go packages each time

### ISSUE THREAD

**Issue by Mistobaan** [bazelbuild/rules_go#46]
I find it annoying that the rule has to download the whole go package each time (~100MB+).

Can we assume instead that the HOST has go installed and maybe just have a rule to enforce the version ?

**Comment by yugui** [comment]
Right.  I feel the same issue.

Unfortunately we cannot simply assume that because I have no plan to force users install anything other than Bazel and it prerequisites.
But there are several other solutions come to my mind.

1. Cache `http_xxx` rules independently from workspace when it has sha256 sum specified.
    * Pro: solves the same problem not only in rule_go but also in other language supports
    * Cons: requires a change in Bazel itself.  I am not sure if it is feasible.
2. Have another version of `go_repositories()` rule and detect the go runtime installed in the system as [cc_configure.bzl](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl) does.
   * Pro: No extra download is even better than download once.
   * Con: Makes the implementation of `go.bzl` even more complex.

BTW, even today it should not be a big problem for you because Bazel is good for building a larger, complex and potentially polyglot repositories fast and correctly.  So you usually don't need to work on a different repository than the one you worked on yesterday.
So the downloading the runtime should be mostly a one-off overhead.

**Comment by pmbethe09** [comment]
What about adding a config_setting "use_local_go" which uses a
new_local_repository looking for go in /usr/local/go?

**Comment by yugui** [comment]
@pmbethe09 Right.  That's a better alternative to the option 2.

**Comment by jayconrod** [comment]
Closing some old issues. There are a couple ways to avoid the large download now.

Bazel has an experimental flag, --experimental_repository_cache, which specifies a directory for caching downloaded archives. You can add this to a bazelrc file. This is probably the most portable mechanism.

```
echo build --experimental_repository_cache ~/.bazel_downloads >>~/.bazelrc
```

When #321 lands, you'll also be able to use your local Go installation instead of downloading a Go toolchain. This can result in non-hermetic builds though, and it requires that all developers have Go installed in the same place.

```bzl
new_local_repository(
    name = "local_go",
    path = "/opt/go-1.8",
    build_file_content = "",
)

go_repositories(go_linux = "@local_go")
```
