### ISSUE TITLE
Gazelle attribute sorting

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#584]
At the moment gazelle sorts
a/b/dir:target
a/b:target
where the more natural order (and the one kubernetes uses) would be
a/b:target
a/b/dir:target

**Comment by pmbethe09** [comment]
Whatever it is, it should be the same as buildifier does -- which I think is what gazelle uses.

So any changes would have to be to buildifier as well and the LSC that comes out of that.

**Comment by jayconrod** [comment]
This is because of the `select` expressions that Gazelle now emits for platform-specific sources and deps. buildifier sorts lists in the more natural order, but it doesn't recognize these expressions.

```bzl
go_library(
    name = "go_default_library",
    srcs = [
        "main.go",
    ] + select({
        "@io_bazel_rules_go//go/platform:linux_amd64": [
            "extra.go",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:private"],
    deps = [
        "//foo/bar:go_default_library",
        "//foo:go_default_library",
    ] + select({
        "@io_bazel_rules_go//go/platform:linux_amd64": [
            "//linuxonly:go_default_library",
        ],
        "//conditions:default": [],
    }),
)
```

Gazelle is a little sloppy when it generates attributes because it assumes buildifier will rewrite. We sort deps as strings ('/' < ':' in ASCII) just to be deterministic and testable.

@pmbethe09 Should buildifier handle expressions like this? If so, I can submit a PR (or is the internal version canonical?). If not, I'll fix gazelle to generate lists in the correct order.

**Comment by pmbethe09** [comment]
buildifier *should* but currently does not handle this case.  Probably a fix will come this quarter.

**Comment by jayconrod** [comment]
For now, I'll change Gazelle to do the sorting itself.
