### ISSUE TITLE
gazelle/wtool does not understand gopkg.in

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#592]
If you run gazelle on a project that imports `"gopkg.in/yaml.v2"` you get a reference to `"@in_gopkg_yaml_v2//:go_default_library"`
If you then run wtool on that reference
```wtool in_gopkg_yaml_v2```
you get a message `unrecognized import path "gopkg.in/yaml/v2"`

**Comment by achew22** [comment]
This will probably work if you run

`wtool -asis gopkg.in/yaml.v2`

I wonder if it wouldn't be a good idea to switch to `-asis` as the default. Any thoughts on that from maintainers?

**Comment by jayconrod** [comment]
I basically always run `wtool -asis`. Agree the current default isn't very useful.

We'd really like to get rid of wtool though. It's super-painful to add external repositories that has 50+ transitive dependencies. It really needs to be automated, and it needs to be recursive. It makes sense for Gazelle to do this, since only Gazelle can discover external dependencies. As soon as this is working, we'll deprecate wtool.

I'll try and figure out a short term solution. Having Gazelle manage external dependencies is nuanced, since when we resolve import paths, we need to be aware of vendor, visibility declarations, and explicit `importpath` attributes. We could do something fairly simple, like external mode, hidden behind an experimental flag though.

**Comment by jayconrod** [comment]
Closing old Gazelle issues. We're getting closer to Gazelle managing external dependencies, so I don't think there will be a different short term solution.
