### ISSUE TITLE
document new_go_repository to go_repository migration

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_go#593]
I'm having to upgrade my rules_go to HEAD for rules_webtesting, and got the warnings to change from new_go_repository to go_repository. It might be nice to have a little bit of docs that talks about migrating.

All of the go_repository args are marked as optional in the docs now, so it's unclear what it takes to work correctly.

**Comment by jmhodges** [comment]
Ah, the importpath is talked about in the longer docs on it, so I guess that's just an autogeneration bug that's maybe unavoidable?

**Comment by jmhodges** [comment]
Just got burned by trying to use rules_webtesting using `url =` in a `go_repository` called instead of `urls =`. It might be nice to make that backwards compatible for at least a while.

I'll try to fix their deal, though.

**Comment by jmhodges** [comment]
Agh, similarly, there's now a new error about both `tag` and `urls` be specified at the same time.

**Comment by ianthehat** [comment]
Sorry about that. The intent was that you could just straight replace new_go_repository with go_repository, without changing any of the arguments, before the recent change they were just aliased anyway for quite a while.
Just using url was deprecated a long time ago, in all the various rules that take those kinds of arguments across all of bazel. At the moment we are kind of assuming that it is okay to break compatibility on the assumption that if you want newer features you are willing to abandon older ones, and if you need older ones you are okay with sticking to a previous version. If it's going to be difficult for you we can add back some compatibility features, maybe with a warning print.
The tag and url thing is something we discussed, the reason we left it not allowing both is because we felt if you had both, but they did not match it would be confusing, and trying to validate that they did match was too expensive, so better to just disallow it for now, especially as our longer term goal is to totally kill go_repository (see #460).
