### ISSUE TITLE
Gazelle - "build tags can't be negated"

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_go#600]
I was wondering what the reasoning is behind not allowed build tags to be negated when passed to Gazelle.

Was trying to avoid the issue in #551 by using the build_tag "!cgo" (not certain that's a valid approach) but it appears it'd solve the issue for https://github.com/shirou/gopsutil

**Comment by jayconrod** [comment]
cgo is a special case in Gazelle. It's always turned on in Gazelle for consistency with the rules. It's always on in the rules because we don't have a good way to control `CGO_ENABLED` from the Bazel command line; `CGO_ENABLED` should be applied for an entire build, not individual targets. We could implement something with `--define`, but we might want to do something with toolchains instead. Not sure yet. Once we have a way to control cgo in the rules, we will add a flag in Gazelle.

Besides cgo, Gazelle treats all tags as false, except for those in `-build_tags` and a few more special cases.

* Anything that looks like a Go release tag is true (`go1.8`, `go2.34`, etc).
* `gc` is true. We don't support gccgo yet.
* `amd64`, `linux`, `darwin`, and `windows` are true on specific platforms. The platforms are hard coded for now.

Remember, `go_library` and other rules also apply tags before compiling source files, so it's better for Gazelle to include too many files than not enough. Doesn't help with cgo though.

**Comment by ianthehat** [comment]
Yes, nocgo is definitely going to be a separate toolchain.
I am waiting to see the finished constraint/platform and toolchain selection system to see how to do this option, and what you will have to specify on the command line to select it.

**Comment by ianthehat** [comment]
I believe this is no longer an issue.
Work on supporting pure go builds is blocked on Bazel always requiring a working c toolchain even if it's not needed, but that is tracked in #663. Once we have that, we will add the ability to specify you want the pure go version of a library, probably with the same method we used for building in "race" mode.
