### ISSUE TITLE
"bazel fetch" broken with "circular" platform specific dependencies.

### ISSUE THREAD

**Issue by ains** [bazelbuild/rules_go#604]
This one is a little convoluted and appears to be an interplay between Gazelle generating a single BUILD file for all platforms using `select` the the behaviour of `bazel fetch ./...`.

The external dependency https://github.com/shirou/gopsutil contains a lot of platform specific code, and Gazelle handles the generation of build files for it fine, `bazel build` also works fine when using it as a dependency.

However, the repository has an unfortunate dependency graph which looks to Bazel like a circular dependency when the `select` statements aren't taken into account. To reproduce add `github.com/shirou/gopsutil` to your WORKSPACE and run `bazel fetch @com_github_shirou_gopsutil//..`

The error returned is
```
ERROR: /private/var/tmp/_bazel_ains/d5881538c6f49328692a7434d44d9eb5/external/com_github_shirou_gopsutil/process/BUILD.bazel:3:1: in go_library rule @com_github_shirou_gopsutil//process:go_default_library: cycle in dependency graph:
.-> @com_github_shirou_gopsutil//process:go_default_library
|   @com_github_shirou_gopsutil//host:go_default_library
`-- @com_github_shirou_gopsutil//process:go_default_library.
```

Looking at the relevant generated build files `process/BUILD.bazel` contains
```
select({
        "@io_bazel_rules_go//go/platform:linux_amd64": [
            "//host:go_default_library",
        ],
        "@io_bazel_rules_go//go/platform:windows_amd64": [
            "@com_github_StackExchange_wmi//:go_default_library",
            "@com_github_shirou_w32//:go_default_library",
        ],
        "//conditions:default": [],
    })
```

and `host/BUILD.bazel` contains
```
select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": [
            "//process:go_default_library",
        ],
        "@io_bazel_rules_go//go/platform:windows_amd64": [
            "//process:go_default_library",
            "@com_github_StackExchange_wmi//:go_default_library",
        ],
        "//conditions:default": [],
    })
```

Whilst there is technically a circular dependency if the deps are flattened this is never encountered with either `bazel build` or `go build` as the conditions under which the dependencies are used are mutually exclusive.

I'm leaning towards this being a Bazel issue with the behaviour of the fetch command, as you also can't select certain configurable outputs via flags like you can with `bazel build` (`bazel fetch --cpu=darwin` is invalid, and would at least offer a workaround) but I figured i'd also an open an issue here to get any thoughts you guys might have, as without restructuring gopsutil it'll break the bazel fetch command in any workspaces that include it.

**Comment by ianthehat** [comment]
That's a fairly extreme edge case...
My personal feeling is that fetch is getting less and less useful because it operates on unconfigured targets, and this one of the reasons. The same argument applies to query.

They are talking about adding a no-execute option to the build command. You could use this to replace fetch for normal uses, which would do the job much better. It will trigger the full loading and analysis phases for fully configured targets, thus causing exactly the correct set of downloads, and understanding select statements correctly.

Also we could just send gopsutil a pull request that just makes it stop doing that 'cause it's bad and wrong... :)

Whatever the solution, I think that gazelle is doing the right thing when it generates those files, so there is not much we can do to improve this.
Even if there was a way of changing the BUILD files that fixed the problem, I am not sure it should be done automatically by gazelle, which means we would need #460 so we could have a manually modified build file (or try to add BUILD files to the gopsutil project).

**Comment by ains** [comment]
Yeah it's a pretty gnarly edge case, just wanted to document it more than anything.

I have a custom branch of gopsutil that doesn't have this issue, although it's not technically wrong if it builds with the default go toolchain.

**Comment by ianthehat** [comment]
I'm going to close this as I am not sure there is anything we can actually do about it in rules_go
