### ISSUE TITLE
gazelle should support a mode where it writes src and dep info to a .bzl file

### ISSUE THREAD

**Issue by mikedanese** [bazelbuild/rules_go#614]
Instead of maintaining BUILD files directly, it would be useful if gazelle could run in a mode where it maintains a .bzl file in the package that contains the src and deps lists. The BUILD file in the package could then depend on these lists and we could leave the lists out of source control. This will prevent a lot of merge conflict pain.

**Comment by jayconrod** [comment]
Hi Mike, could you comment with an example of what a generated .bzl file would look like? Would srcs and deps need to be lists, or would they use select for platform-specific sources and deps as well?

Also could you say more about what kinds of merge conflicts you're seeing? Is it the normal thing where two sources are added that would be inserted at the same place in an alphabetized list, or something else?

This seems useful, but also pretty specific. I wonder if It would be better for Gazelle to have a "raw" mode, where it generates a file with package information that can be turned into a BUILD file by some other tool. .bzl would already be pretty close to that though.

**Comment by pmbethe09** [comment]
What if for packages with no conditionals gazelle could attempt to generate using 'glob'
`go_library(srcs = glob(["*.go"], exclude = ["*_test.go"]), ...)`
and
`go_test(srcs = glob(["*_test.go"]), ...)`

How many build files would that improve things for?

**Comment by jayconrod** [comment]
Closing old issues. If this is still something you want, please reopen in bazelbuild/bazel-gazelle.

However, I don't think we should move forward with this. This would affect every package in Gazelle, and it would complicate the implementation significantly. I think you'd inevitably end up with partially checked-in files, since for any large project, you'd need a few `# keep` comments and other directives. So the configuration will end up complicated as well.
