### ISSUE TITLE
bazel test: GOPATH environment variable not set

### ISSUE THREAD

**Issue by minorhacks** [bazelbuild/rules_go#621]
When I execute a `go_test` rule with `bazel test`, I'm getting a panic from the test binary:

```
panic: GOPATH environment variable not set
```

The binary can manually run successfully by e.g. `bazel-bin/logging/devlog/devlog_test` (I assume by using the GOPATH I have set in my environment - maybe Bazel trying to execute the test in a clean environment?)

My BUILD file for the package in question:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["devlog.go"],
    deps = ["@com_github_pkg_errors//:go_default_library"],
)

go_test(
    name = "devlog_test",
    srcs = ["devlog_test.go"],
    library = ":go_default_library",
)
```

Is there a piece that I'm missing to be able to run Go tests from Bazel?

Bazel version:
```
Build label: 0.5.2
```

rules_go tag: `0.5.1`

**Comment by jayconrod** [comment]
> maybe Bazel trying to execute the test in a clean environment?

This is exactly what's happening. Bazel executes tests in a sandbox so that the results are reproducible on different machines.

Could you say more about how you're using GOPATH in your test? Is it possible to use a testdata directory or a temp directory and point GOPATH to that in TestMain?

**Comment by ianthehat** [comment]
In general tests should not be relying on a GOPATH anyway, they are just a binary, that could be run outside the normal build setup. This is true even without bazel. When possible they should be totally self contained, short of that they should only rely on things from their test data directory.
When using bazel, there is no need to have a GOPATH, I would expect that most people would not bother. When running a test from inside bazel, not only will GOPATH not be set, but it would not do you any good if it was, because access to the contents of the GOPATH would also be blocked. You can punch holes through this protection, but if you do you will never be able to take advantage of remote execution, and you probably are not going to be able to get the dependancies correct so your test may either not run when it should, but just give you cached results, or run all the time.
If you can tell us more, or show us the test, we could advise on what your best path forward is.

**Comment by minorhacks** [comment]
Apologies - I dug more into this over the weekend and this is our bug - the test had an implicit dependency on GOPATH which can be fixed by pulling in the dependent files using data dependencies instead.
