### ISSUE TITLE
Support defining stamping on libraries

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/rules_go#628]
I have a mono-repo where I would like to provide a library that exposes a handler that displays (among other things) build info to the user of the software.

I see how I'd do this with `linkstamp` on the binary, pointing at the package containing this library, but it would be awesome if instead we could do it on the library (we wouldn't even need an attribute per se, we could just use the standard `stamp` attribute to turn it on/off). I saw a mention of potentially going this way in #432 but it apparently was not implemented over a fear that we'd constantly rebuild. I propose instead that we depend on the --stamp argument to bazel to control this.

The reason I want this is so that I don't have to go and annotate each `go_binary` that uses this dependency with the correct `linkstamp` setting.

**Comment by ianthehat** [comment]
I don't really like the linkstamp system, I think the x_def form is considerably more powerful and easier to understand.

It would be fairly easy to make the x_def system inherit x_def's from the transitive set of all dependancies. This would cause all binaries that depend on a library that has an x_def that changed to have to relink, but its not a huge deal. Binaries could also override a setting from library to a different value (a stable one would prevent the relinking for instance) or just to disable all inherited x_def's, ideally this system would obey the normal stamp trivalue, but I don't think we have access to that in skylark yet.

If we also make it so that x_def's declared without an import path use the one from the library/binary they were declared on it would also make adding them in this way much easier to read.

We would have to have some kind of stable rule to cope with when the same x_def is supplied by multiple dependancies, but I don't think that's a huge deal either.

**Comment by swsnider** [comment]
Yeah, that'd probably work for me just as well -- as long as I only have to specify stamping in one place, I'm good.

**Comment by jayconrod** [comment]
@ianthehat's suggestion seems like a good way forward to me. Binaries will always need to be relinked when stamping is in use, so no change there. This avoids the need to recompile when stamping is in use.
