### ISSUE TITLE
Coverage fails with "GoCover_0 redeclared in this block"

### ISSUE THREAD

**Issue by ypomortsev** [bazelbuild/rules_go#629]
```
$ bazel coverage ...:*
ERROR: /.../BUILD.bazel:10:1: null failed: Process exited with status 1 [sandboxed].
bazel-out/local-fastbuild/.../main_GoCover_0.cover_GoCover_0.cover.go:47: GoCover_0 redeclared in this block
	previous declaration at bazel-out/local-fastbuild/.../main_GoCover_0.cover_GoCover_0.cover.go:32
```

The generated `main_GoCover_0.cover_GoCover_0.cover.go` has:

```
var GoCover_0 = struct {
	Count	[2]uint32
	Pos	[3 * 2]uint32
	NumStmt	[2]uint16
}{
	Pos: [3 * 2]uint32{
		9, 10, 0x2e000d,
		10, 12, 0x3002e,
	},
	NumStmt: [2]uint16{
		1,
		1,
	},
}

var GoCover_0 = struct {
	Count     [2]uint32
	Pos       [3 * 2]uint32
	NumStmt   [2]uint16
} {
	Pos: [3 * 2]uint32{
		9, 11, 0x2e000d, // [0]
		11, 14, 0x3002e, // [1]
	},
	NumStmt: [2]uint16{
		2, // 0
		2, // 1
	},
}
```

**Comment by jayconrod** [comment]
The problem affects `go_binary` targets with sources listed in a `library` attribute. Coverage instrumentation is applied twice for these sources. The `go_library` rule applies coverage once and exposes the sources through the `GoSource` provider instead of the original sources. The `go_binary` rule applies coverage again on these rules.

This doesn't affect `go_test` rules because `ctx.coverage_instrumented()` returns false for test rules. I guess that makes sense.

I'm not sure whether it makes sense to return sources with coverage applied through `GoSource`. When we compile cgo, we definitely need to returned processed sources, but it should be possible for tools to discover original sources. That should be possible with aspects, so I guess providers don't need to do that.

The simplest fix is probably to just exclude files that have already been processed for coverage. We already do this with non-.go files and test files.

**Comment by ianthehat** [comment]
I had come to the same conclusion, but when I tried to not return the covered sources from the library, coverage stops working...
This is because the test is not using the library, but getting the source out of the library and recompiling it without coverage.
