### ISSUE TITLE
Why does the cgo_binary not handle pure Go code?

### ISSUE THREAD

**Issue by nathantchan** [bazelbuild/rules_go#63]
I would like to understand the reasoning behind why the cgo_binary target cannot compile pure Go code that does not import "C". [link](https://github.com/bazelbuild/rules_go#note) It seems to me that having to list out manually and separately the Go files that import C and those that do not is a little onerous for a large project.

**Comment by ahyangyi** [comment]
I have the same question. Is there any particular reason this cannot happen? Even silently inserting an empty `import "C"` sounds better than the current situation.

**Comment by yugui** [comment]
@nathantchan 
Bazel requires us to explicitly declare build dependency by policy.  So we cannot/shouldn't dispatch build actions based on the contents of the file. That's why we need to distinguish cgo-enabled files and pure-go files as rules.
For larger projects #15 covers that part.

@ahyangyi's idea is interesting, and it is what we didn't think about when we design. But I still think `cgo_library` is better to be {Fast,Correct}.
If we still have big issues even after #15, I'd like to think about @ahyangyi's idea.

**Comment by AustinSchuh** [comment]
@yugui I'm thinking out loud here, but just because you can't read the file contents at action generation time, doesn't mean your action can't be smart enough to check the file content when it is run.

#15 would help a lot though.

**Comment by yugui** [comment]
You can see more background of the current design in [a past discussion thread](https://groups.google.com/d/msg/bazel-dev/xFcxQyaxQec/YqIYjqA2CAAJ).

Also I'd like to add several factors here:
* A possible downside of the idea by .@ahyangyi is that it adds unnecessary dependency from the output binary to libc.
* We preferred fine-grained actions to a single large smart action (Actually I have even implemented it but abandoned) to be {Fast, Correct}.

**Comment by ahyangyi** [comment]
If one uses go_binary, there's no dependency on libc. If one uses cgo_binary, there might be false dependencies on libc. Sounds fair enough for me.

Note that I'm not advocating merging the two into one rule. I just think letting the users to maintain the two filegroups might be tedious in certain contexts.

**Comment by yugui** [comment]
> Note that I'm not advocating merging the two into one rule. I just think letting the users to maintain the two filegroups might be tedious in certain contexts.

I see.  Then, #15 solves the problem.
