### ISSUE TITLE
output_group breaks run task

### ISSUE THREAD

**Issue by kyessenov** [bazelbuild/rules_go#658]
Adding `output_group=static` to my tools/bazel.rc breaks run task for go binaries.
`bazel build <go-task>` succeeds.
`bazel run <go-task>` fails to find the executable.
This is bazel 0.5.2 and latest rules_go.

**Comment by jayconrod** [comment]
Could you post your bazel.rc file along with the actual commands you're running?

**Comment by jayconrod** [comment]
Also the exact error you're getting would be helpful.

**Comment by kyessenov** [comment]
bazel.rc:
```
build --verbose_failures
test --test_output=errors
build --workspace_status_command=bin/get_workspace_status --action_env=ISTIO_VERSION
build --output_groups=static
build --sandbox_tmpfs_path=/dev/shm
```

script:
```
bazel clean
bazel build //cmd/pilot-agent
INFO: Found 1 target...
Target //cmd/pilot-agent:pilot-agent up-to-date:
  bazel-bin/cmd/pilot-agent/pilot-agent.static
INFO: Elapsed time: 29.007s, Critical Path: 10.69s
bazel run //cmd/pilot-agent
INFO: Found 1 target...
Target //cmd/pilot-agent:pilot-agent up-to-date:
  bazel-bin/cmd/pilot-agent/pilot-agent.static
INFO: Elapsed time: 0.481s, Critical Path: 0.06s
ERROR: Non-existent or non-executable /home/kuat/.cache/bazel/_bazel_kuat/9ff0653fb8eda31e5f7b80b7b7a8a577/execroot/com_github_istio_pilot/bazel-out/local-fastbuild/bin/cmd/pilot-agent/pilot-agent.
```

**Comment by ianthehat** [comment]
That's basically expected behavior.

bazel run always tries to run the *executable* output file, which is always in the default files and always named after the rule. By setting the output group, you are telling it not to build that file, but a different one instead. Bazel should probably be more vocal about this case, complaining about you asking to run something you are excluding from the build, but I don't think the behavior itself would change, just the error message you get.

I don't think there is any good way for bazel to support this use case. Even if you allowed each output group to specify what it's executable was, what would you run if you asked it to build multiple output groups?

Would it be better if we could allow you to specify on the target itself that it's default output should be the static one instead?

**Comment by kyessenov** [comment]
This mostly manifested in the dependency from rules_docker on rules_go. I was trying to build a docker image from a static go binary by setting output_group. This somehow worked until I run `bazel clean`. I think the dependency should be explicit. If the build task is not building the default binary, then any task that depends on it should fail. Otherwise, the error mode is very confusing.

Since then, I abandoned the idea of using rules_docker, and now use regular Dockerfile, which work fine with just rules_go and output_group.

**Comment by jayconrod** [comment]
If you're consuming the static binary in another rule, you can put a [`filegroup`](https://docs.bazel.build/versions/master/be/general.html#filegroup) in between. `filegroup` lets you specify the `output_group` you want.

**Comment by ianthehat** [comment]
As Jay said, something like
```
go_binary(
    name = "bin",
    srcs = ["bin.go"],
)
filegroup(
   name = "static_bin",
   srcs = [":bin"],
   output_group = "static",
)
docker_build(
  name = "bin_package",
  files = [":static_bin"],
)
```
should do what you want.
If you want the file renamed (to remove the .static bit), you could replace the filegroup with a custom rule that picks out the static output and then copies it, using `dep[GoBinary].static` to get the static binary.

I am going to close this issue for now, please re-open if you want us to do anything, or have any more questions, and maybe open a bug on bazel itself for better error handling with output groups.
