### ISSUE TITLE
support compiling tests as binary artifacts

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#670]
We currently build a few of our e2e tests outside of Bazel using `go test -c`, as these tests are run later after the system-under-test has been started (using a separate framework).

Under Bazel, we [use a genrule that depends on the `go_test` target](https://github.com/kubernetes/kubernetes/blob/d8205661b700c6f99c33ea0ac1e5ed3e49c202b2/test/e2e/BUILD#L132-L141), but after #554 this stopped working, as the test first attempts to chdir to the test package, failing if it can't. And the way we run the tests, this always fails.

Is there a more obvious way we could do this that it'd actually work?

**Comment by jayconrod** [comment]
I've been thinking about adding an attribute to `go_test` that would make it cd to a custom directory, relative to the repository root. You would be able disable the cd behavior by passing in `"."`. Do you think that would work?

The problem fixed by #554 was that the directory is different depending on whether the test is built in an external repository, so we'd have to be careful about that. Maybe the test could attempt to change to both `external/repo/test/dir` and `test/dir`.

**Comment by ixdy** [comment]
Your first suggestion would work for us.

Neither `external/repo/test/dir` nor `test/dir` exists the way we run our `e2e.test` binary - it gets put into a tarball with only the dependencies it needs, not the entire source tree, and the layout looks nothing like the source tree.

**Comment by jayconrod** [comment]
@ixdy PTAL at #676. I think this is the simplest change that will fix the situation for you.

**Comment by ixdy** [comment]
fantastic. I'll test against that change and let you know whether it works.
