### ISSUE TITLE
Gazelle: generate http archive go_repository URL's

### ISSUE THREAD

**Issue by kevinburke** [bazelbuild/rules_go#675]
There's some suggestion that generating http archive URL's is faster than the commit URL's. It would be nice if there was a flag to gazelle to generate these automatically (if it's true that they are faster).

**Comment by jayconrod** [comment]
It's usually faster to download an HTTP archive than to clone a git repository because you don't have to download all the history. However, at least with GitHub, there is a major caveat: the contents of an  archive at a given commit can change if the repository is renamed. The directory structure of the archive contains the current name of a project, not the name from the URL. This means that SHA-256 of the archive won't match, so builds can fail retroactively.

Because of this, HTTP archives will never be the default in Gazelle. I'd be happy to add this behavior behind a flag (with a warning label) when Gazelle starts managing external dependencies though.

**Comment by jayconrod** [comment]
Closing old Gazelle issues.

The SHA-256 thing is still an issue. We were bitten by it again in September.

We're still thinking about deprecating `go_repository`. We need a viable replacement for `new_http_archive` and `new_git_repository` though that accepts a tree of build files, rather than a single flat file. We're thinking about Skylark replacements for these in some standard repository, but I need to work out the design with core Bazel folks.
