### ISSUE TITLE
Use build_file_name arg in gazelle Bazel rule

### ISSUE THREAD

**Issue by RenatoUtsch** [bazelbuild/rules_go#690]
I want to make gazelle generate `BUILD` files instead of `BUILD.bazel` when running `bazel run //:gazelle`.

This is easy to do by running gazelle as a standalone application:
```bash
$ gazelle -build_file_name BUILD
```

However, I can't manage to make the `//:gazelle` target do the same thing. Even if I specify it like this:
```python
gazelle(
    name = "gazelle",
    args = ["-build_file_name BUILD"],
)
```

Or like this:
```python
gazelle(
    name = "gazelle",
    args = [
        "-build_file_name",
        "BUILD",
    ],
)
```

In both cases running `bazel run //:gazelle` still generates a `BUILD.bazel` file instead of only `BUILD`. How can I make it work with the bazel rule?

**Comment by ianthehat** [comment]
I just tested
```python
gazelle(
    name = "gazelle",
    args = ["-build_file_name", "BUILD"],
)
```
which is the same as your second version, and it works. The setting is only used when gazelle generates a new file, it ignores it if it is updating and existing file, maybe you had BUILD.bazel files left over from a previous attempt?

**Comment by RenatoUtsch** [comment]
Nope, I tried it again and it still generated a BUILD.bazel file.

I'm using 0.5.2, maybe this was fixed on master? Will test that.

**Comment by RenatoUtsch** [comment]
Yep, I can confirm that. It doesn't work in the 0.5.2 tag (still creates a `BUILD.bazel` file), but works correctly on master.

Guess I'll use the master branch until the next release.

**Comment by ianthehat** [comment]
It seems the problem was actually that gazelle at that version had a bug, it would equally have not worked if you had run that version of gazelle from the command line I think. I get 
`multiple Bazel files are present: BUILD.bazel, BUILD`
errors for directories that there were no BUILD files of any name when gazelle was started when I use that option.
It is fine at tip, and we will be tagging a new 0.5.3 release very soon.

**Comment by RenatoUtsch** [comment]
OK, thanks for the help!
