### ISSUE TITLE
How to import tensorflow/go with gazelle?

### ISSUE THREAD

**Issue by mauri870** [bazelbuild/rules_go#697]

**Comment by jayconrod** [comment]
What problems are you having exactly? I tried building this and ran into some issues, but let you me know if you're seeing something else.

The full import path is `github.com/tensorflow/tensorflow/tensorflow/go`. There are some BUILD files present already. Unfortunately, they interfere with the rules that Gazelle generates. In particular, in `tensorflow/go/BUILD`:

```bzl
filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    ),
    visibility = ["//tensorflow:__subpackages__"],
)
```

Gazelle generates BUILD files in subdirectories, including `tensforflow/go/op`, which means this `glob` crosses a package boundary.

```
$ bazel build //tensorflow/go:go_default_library
____Loading package: tensorflow/go
ERROR: /usr/local/google/home/jayconrod/.go/src/github.com/tensorflow/tensorflow/tensorflow/go/BUILD:26:12: Label '//tensorflow/go:op/generate.go' crosses boundary of subpackage 'tensorflow/go/op' (perhaps you meant to put the colon here: '//tensorflow/go/op:generate.go'?).
```

Gazelle can't work with all custom BUILD files; it's certainly possible to make custom BUILD files compatible with Gazelle, but I don't think we can support this case.

Since TensorFlow uses Bazel already, perhaps they can use `rules_go` and Gazelle directory and check in the generated files. Then you would be able to simply add a `git_repository` dependency in your WORKSPACE. We can work with them on this once our API is more stable.

**Comment by mauri870** [comment]
It's exactly the problem I am facing @jayconrod.
The BUILD file present in tensorflow/go prevents gazelle to generate one. I tryed to remove the file and run gazelle again, it seems to work but the copts in the cgo_library that gazelle generates is trying to import the header files out of the package scope(-I ./../../), generating an error on bazel build.

**Comment by jayconrod** [comment]
The rule generated by Gazelle will need some manual tweaking. Gazelle will be able to find headers in the same directory, but not in other directories. You'll need to add a `cdeps` attribute to `go_library` or `cgo_library` to reference headers in other `cc_library` rules.

I'm noticing that Gazelle is expanding `// #cgo CFLAGS: -I${SRCDIR}/../..` to an absolute path. That is a bug, and I'll open another issue for that specifically.

**Comment by jayconrod** [comment]
@akashgangil I took a quick look, but someone from TF will need to give a more thorough review.

* Instead of `library = ":go_default_library`, use `embed = [":go_default_library"]`. The `library` attribute is deprecated and will be removed soon.
* Instead of `-L`, `-l`, and `-I` flags in `copts` and `clinkopts`, reference `cc_library` rules in `cdeps`.
* In tensorflow/go, there's no need to write separate `go_test` rules for internal and external tests. Gazelle still generates separate rules, but I'm working on fixing that.
