### ISSUE TITLE
Allow wrappers

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/rules_go#748]
Allow people to mark rules as a wrapper for a go rule, so they can be managed by gazelle as if the were the underlying rule.
It would be even nicer if you could do this once for an entire rule type rather than per rule. The original example was bazelbuild/rules_docker#119 where go_image is a proxy for go_binary as far as gazelle should be concerned.

**Comment by jayconrod** [comment]
I think it only makes sense to do this for rule kinds, not individual rules. I don't think you'd want some `go_image` rules to be treated as `go_binary` but not others.

The main challenge is how to configure Gazelle to support this. We could support a new directive in build files. This would apply in the Bazel package containing the directive and sub-packages.

```
# gazelle:kindalias go_image = go_binary

go_image(
    name = "cmd",
    srcs = ...,
    deps = ...,
    visibility = ["//visibility:public"],
)
```

Should we have a command-line argument for this instead? I expect we'll want to support more directives like this in the future which are project-specific and maybe package-specific. We should have a persistent configuration saved in build files so that Gazelle may be invoked consistently without needing to remember arguments. We could accomplish that by adding attributes to the `gazelle` rule which get converted into command line arguments. I think I prefer directives though.

**Comment by fejta** [comment]
I do not understand the use case for having both a go_image  and go_binary rule for the same package.

**Comment by jayconrod** [comment]
You probably wouldn't need both; you would need `go_image` *instead of* `go_binary`. With this proposal, Gazelle would recognize and update `go_image` rules, treating them as `go_binary`.

**Comment by jayconrod** [comment]
Migrated to bazelbuild/bazel-gazelle#18
