### ISSUE TITLE
Example gazelle project layout

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_go#76]
I'd like to start up a bazel go project with a vendor directory and gazelle without wading through a ton of documentation. I've shipped bazel projects in other languages before.

Is there an example in the tests somewhere @yugui?

**Comment by yugui** [comment]
@sayrer No.
I plan to regenerate `BUILD` files in `//examples` with Gazelle once it has enough functionality to do so, but for now there's no good example.

Also if you are thinking about the pattern 2 in https://github.com/bazelbuild/rules_go/issues/16#issuecomment-216010843, you would need to wait for ["flat" style](https://github.com/bazelbuild/rules_go/commit/5ebffb24977666f88f24e208bfb39dd0d208858e).
If otherwise, you can just try running gazelle with "--help".

**Comment by jayconrod** [comment]
Closing old Gazelle issues.

https://github.com/bazelbuild/bazel-gazelle/blob/master/README.rst is the new location for Gazelle documentation.
