### ISSUE TITLE
go_library(cgo=True, ...) emit .h file with exports as an output

### ISSUE THREAD

**Issue by ajbouh** [bazelbuild/rules_go#776]
I'm using a simple go file that looks something like this:

main.go
```
package main
import "C"

//export MyFunction
func MyFunction() {}

func main() {}
```

I'd like to use this as a src or dep in a cc_library, but the _cgo_export.h that I'm expecting to be emitted as an output doesn't seem to be propagating to the cc_library.

I know the _cgo_export.h file is being exported, because my work around right now is to manually copy it out of its generated location and commit it into my project. Any tips here about what I should do to ensure the file is properly exported?

**Comment by jayconrod** [comment]
_cgo_export.h is provided to an internal cc_library through the srcs attribute. We would need to pass it through hdrs for it to be visible to other libraries. That should be a fairly easy fix.

How would you access this though? Do you have another cc_library that references the cgo-generated library through deps? I'd be very surprised if that linked correctly. If you have other C files that can be part of the same library, you can include them in the go_library srcs (they will be passed to the cgo-generated cc_library srcs).

**Comment by ajbouh** [comment]
I'm using another undocumented feature and generating a .so file with
-buildmode=c-shared

I basically built a library in go, but am testing it from c++. I assume it
links properly because all the tests pass. :)

**Comment by jayconrod** [comment]
Ah, sorcery! :)

I'm glad this works for you, but we're not ready to support it officially yet. There are some obstacles to making this work in the general case, in particular, the [Bazel sandwich problem](https://bazel.build/designs/2016/08/04/extensibility-for-native-rules.html). Go, C, and C++ all compile to native code, so in theory they can be linked into the same binary, but in Bazel, they are different rules that don't know about each other. If you have a cc_library A that depends on a go_library B that depends on a cc_library C, there's no way to propagate hdrs (or other C/C++-specific attributes) from C through B to A. The go_library rule won't know about them. Since C/C++ are implemented natively within the Bazel core (not in Skylark), I'm not sure we could even be compatible with them.

There are also some linking issues. If a cc_binary depends on several go_libraries, how do they know about each other? How does the runtime get linked?

I'll leave this issue open for now because I'd like to check the status of the cc_library providers is. It may have improved since the last time I looked. I don't think we'll be able to support this yet though.

**Comment by ajbouh** [comment]
So the native providers aren't using a sort of duck typing where they pull
things out of the output structs they need? They care about the precise
rule that emitted the output structs? That seems to run counter to the rest
of how structs are created/used in outputs elsewhere. Is that really how
they work?

I'm currently using:

(A) cc_library -> (B) go_library -> (C) go_binary -> (D) cc_test
(C) go_binary -> (E) py_test
(A) -> (E)
(A) -> (D)

Where:
- X -> Y means "X is a dep of Y"
- (B) inherits from a c++ class in (A) using swig
- (C) is a .so file using -buildmode c-shared
- (E) dlopens (A) then (C)

I don't think I'm directly exposed to the sandwich problem, but perhaps
I'll run up against it in a later phase of my project.

I know the above seems complicated, but I've tried to distill it down to
its essence.

I'm happy to help test or refactor or implement stuff in rules_go if it
will help others. Would love some guidance on how to do things in a way
that's right and true for all. :)

**Comment by jayconrod** [comment]
@ianthehat suggested that we might expose these headers via an output group that could be selected with `filegroup`. It's a little clunky, but maybe that would work for you? Something like this:

```bzl
go_library(
    name = "go_default_library",
    cgo = True,
    ...
)

filegroup(
    name = "cgo_exports",
    srcs = [":go_default_library"],
    output_group = "cgo_exports",
)

cc_test(
    name = "test",
    srcs = [
        ":cgo_exports",
        ...,
    ],
)
```

In general, Bazel doesn't care about the precise rule; it looks for providers. Skylark lets us define named providers (`GoLibrary` is our main one), along with some restrictions on attributes, so that provides some degree of type checking. Not all of the native providers defined inside Bazel are exposed to Skylark though, so we can't be compatible with those.

**Comment by ajbouh** [comment]
That seems much better than my copy/paste approach!

Is that something I can whip up on my own or does it require a decent
amount of context to know all the files that would need to be modified?

**Comment by jayconrod** [comment]
It requires a fair amount of context, but it should be a small amount of code. I'll try to push something out by the end of tomorrow.

**Comment by ajbouh** [comment]
Awesome, looking forward to it!

**Comment by jayconrod** [comment]
@ianthehat beat me to it. @ajbouh, can you patch in that PR and see if it works?

**Comment by ajbouh** [comment]
Yes will try it before lunch

**Comment by ajbouh** [comment]
I'm having trouble getting that PR to work. Maybe I need to cherry pick it, because I'm getting caught up on changes made in master since 0.5.3.

I'm seeing this error message:
```
key "@io_bazel_rules_go//go:toolchain" not found in dictionary.
```

**Comment by ianthehat** [comment]
I think that's the error you get if you are not calling go_register_toolchains

**Comment by ajbouh** [comment]
Hmm, I am calling it. But perhaps this is a lifecycle thing related to use
of nested workspaces?
