### ISSUE TITLE
go_path: outputs are not useful

### ISSUE THREAD

**Issue by asf-stripe** [bazelbuild/rules_go#787]
I'm experimenting with integrating `go_path` in our system (to get stuff like a `godoc` server that includes bazel-generated sources, etc). To that end, I thought that I could use the `go_path` rule's output as an input to my other rules. However, `go_path`'s outputs appear to be all the files in the gopath created.

On the surface, that's a decent conceptual fit for Bazel: it did create all those files. However, I think I would prefer if this was a single file (maybe a tarball?) that contains the directory making up the generated gopath. That way, downstream rules can actually hope to use that generated gopath (-:

My current, super-gross, work-around is to take the first file and `sed` away everything past the first occurrence of `/src/`, which ... is not optimal IMHO ):

``` python
def _impl(ctx):
    ctx.actions.run_shell(
        command = """
# XXX: This is a horrible workaround:
tree "$(echo "$2" | sed 's/\/src\/.*//')" > $1
        """,
        # XXX: this [0] too is a horrible workaround:
        arguments = [ctx.outputs.out.path, ctx.files.gopath[0].path],
        inputs = ctx.files.gopath,
        outputs = [ctx.outputs.out],
    )

_go_tree = rule(
    implementation=_impl,
    attrs = {
        "gopath": attr.label(mandatory=True, allow_files=True),
    },
    outputs = {"out": "%{name}.txt"},
)

def go_tree(name, gopath):
    _go_tree(name = name, gopath = gopath)

```

One additional benefit of emitting an archived package could be that the files that come out of that tarball will be regular files, and not symlinks; various go tools seem to hate those.

**Comment by ianthehat** [comment]
It should be all the files, the idea was to form a fully functional gopath, which requires all the files. The go_vet would not work otherwise.
If you look in the go_vet example, the go_path result is a provider that has more than just the files in it though, it also gives you the gopath (which will be the directory you wanted) and the list of packages it put in it.

Note that the the providers that go_path uses are fairly stable now, but the go_path rule itself is highly experimental and about to change quite a lot.
I will be taking the core of it and making it into an action generator that can be used directly inside other rules.
Then the go_vet rule will be changed totally so that we have a go_verify_test rule that you can have per package that knows how to verify just that package, and delegates the verification to a go_verify toolchain, which by default will probably be populated by a vet and fmt test.

Most go tools I have encountered so far have no problem with symlink files, what they often cannot cope with is symlink directories.

**Comment by jayconrod** [comment]
Closing old issues.

[go_path](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path) was largely rewritten recently. It now supports three output modes: copies of files, symlinks, or a single zip archive. It also returns a [`GoPath` provider](https://github.com/bazelbuild/rules_go/blob/master/go/providers.rst#gopath) that contains information about all the packages.

Let me know if you have any issues.
