### ISSUE TITLE
go_sdk doesn't prevent the download and use of external go sdk

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_go#800]
```
local_repository(
	name = "io_bazel_rules_go",
	path = "/home/barriosj/rules_go",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains","go_sdk")

go_sdk(name="go1_8_3_linux_amd64", path="/prod/lib/go")
go_rules_dependencies()
go_register_toolchains()
```
still forces the download and use of external go sdk

**Comment by ianthehat** [comment]
I need more information...
What did you see it do?
What is the contents of the external/go1_8_3_linux_amd64 folder?
which sdk(s) did it download (and how did you see it download them)
if you build with -s what command line gets issued?

**Comment by jeb2239** [comment]
I am on the most recent commit. git pull says up to date.  

I can't show you the output. But i can show this


WARNING: Output base '/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Downloading https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz: 94,886,770 bytes

**Comment by jeb2239** [comment]
Why does this download occur even with go_sdk?

**Comment by jeb2239** [comment]
This also occurs with --experimental_platforms=@io_bazel_rules_go//go/toolchain:host

**Comment by ianthehat** [comment]
It's downloading go 1.9, and you overrode go1.8.3
You either need to select the version of go you overrode, or override the version of go that will naturally be selected.

**Comment by jeb2239** [comment]
so it will force me to use 1.9?

**Comment by jeb2239** [comment]
You state here:

It's not documented yet because it's not finished yet, but if you want to try it
```
go_sdk(name="go1_8_1_linux_amd64", url="https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz")
```
would result in no change as it overrides it with the original value, but it shows you the idea
```
go_sdk(name="go1_8_1_linux_amd64", path="/full/path/to/skd")
```
would replace it with a locally installed one

There is no checking that you are matching the version, so you can replace the 1.8.3 version in the toochains with a different version and it will not complain

So do I pretend 1.8.3 is actually 1.9 ? or ...

**Comment by ianthehat** [comment]
There are two levels of things in the system, the sdk and the toolchain.
There is a one to may relationship between the sdk and the toolchain.
The toolchain is the thing selected by the platform system in bazel, to match the host/target/version constraints.
If you don't set the version constraint, it defaults to 1.9 at the moment (we change the default every time a new go version ships)
The toolchains all refer to an sdk by name, they don't actually check right now that the sdk provides the version they were expecting.
the go_sdk rule substitutes a single sdk, with no idea whether it would be used or not.
You need to make sure (either by changing the selection or changing the name) that you are replacing the sdk that would be used, but you can replace it with anything you like so long as it has the right structure inside it. Thus:
```
go_sdk(name="go1_9_linux_amd64", url="https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz")
```
would replace the sdk the 1.9 toolchain would normally use on linux with an sdk that is actually 1.8.1
In your case, you are leaving the default version, so you must substitute the go sdk that matches that version, which right now is 1.9, and you are replacing it with a local copy. It will not matter what version that local copy is. So you should be doing
```
go_sdk(name="go1_9_linux_amd64", path="/prod/lib/go")
```
but note that that rule will only substitute the linux sdk, you will need equivalents for mac and windows, and you probably want to force the version otherwise it will suddenly start downloading an sdk as soon as go.1.9.1 comes out and I bump the default

**Comment by jeb2239** [comment]
And doing that gives me these errors
```
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:172:1: no such package '@go1_9_linux_amd64//': Traceback (most recent call last):
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 40
		_cross_compile_stdlib(ctx, "windows", "amd64")
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 90, in _cross_compile_stdlib
		fail(("go standard library cross comp...)))
go standard library cross compile go1_9_linux_amd64 to windows-amd64 failed and referenced by '@io_bazel_rules_go//go/toolchain:bootstrap-1.9.0_linux_amd64-impl'.
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:172:1: no such package '@go1_9_linux_amd64//': Traceback (most recent call last):
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 40
		_cross_compile_stdlib(ctx, "windows", "amd64")
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 90, in _cross_compile_stdlib
		fail(("go standard library cross comp...)))
go standard library cross compile go1_9_linux_amd64 to windows-amd64 failed and referenced by '@io_bazel_rules_go//go/toolchain:bootstrap-1.9.0_linux_amd64-impl'.
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:172:1: no such package '@go1_9_linux_amd64//': Traceback (most recent call last):
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 40
		_cross_compile_stdlib(ctx, "windows", "amd64")
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 90, in _cross_compile_stdlib
		fail(("go standard library cross comp...)))
go standard library cross compile go1_9_linux_amd64 to windows-amd64 failed and referenced by '@io_bazel_rules_go//go/toolchain:bootstrap-1.9.0_linux_amd64-impl'.
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:172:1: no such package '@go1_9_linux_amd64//': Traceback (most recent call last):
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 40
		_cross_compile_stdlib(ctx, "windows", "amd64")
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 90, in _cross_compile_stdlib
		fail(("go standard library cross comp...)))
go standard library cross compile go1_9_linux_amd64 to windows-amd64 failed and referenced by '@io_bazel_rules_go//go/toolchain:bootstrap-1.9.0_linux_amd64-impl'.
ERROR: /home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:172:1: no such package '@go1_9_linux_amd64//': Traceback (most recent call last):
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 40
		_cross_compile_stdlib(ctx, "windows", "amd64")
	File "/home/barriosj/.cache/bazel/_bazel_barriosj/b4dc1a5bf3b24f4f245fa18f7ea20c4d/external/io_bazel_rules_go/go/private/toolchain.bzl", line 90, in _cross_compile_stdlib
		fail(("go standard library cross comp...)))
go standard library cross compile go1_9_linux_amd64 to windows-amd64 failed and referenced by '@io_bazel_rules_go//go/toolchain:bootstrap-1.9.0_linux_amd64-impl'.
```

**Comment by ianthehat** [comment]
Because we don't yet have rules for how to compile the standard library on demand, the repository rule has to pre-build any cross compiles that it needs. At the moment it assumes that a linux-amd64 sdk needs a windows cross compiled standard library so it runs
```
go install -v std
```
in the sdk, and that command is failing in the sdk you provided for some reason.
It is supposed to print the reason but I am not seeing it in the logs you pasted.

**Comment by ianthehat** [comment]
No, there is no way for bazel to support go generate in a general sense because generate is not principled enough. It does not specify inputs or outputs, allows commands with arbitrary side effects and does not localise the potential impact of those effects to a restricted portion of the tree, and in general most people use it to modify the source tree itself which is not acceptable in bazel.
In general there is always  a better way to achieve the desired goals in bazel though, for instance people use go generate to build .pb.go files from proto files, the go proto rules do the same thing but in a much more effective way that happens on demand with no chance of it being accidentally out of date.
If you have some specific go generate lines in mind I can advise you on how to implement them, and if there are standard go tools that you have generate lines for we can write or accept contributed rules for those (for instance we have discussed supplying rules for things like x/tools/cmd/stringer)

**Comment by jayconrod** [comment]
@jeb2239 No, but you can rig up something equivalent with a [`genrule`](https://docs.bazel.build/versions/master/be/general.html#genrule) or your own custom rule. You can include the generated sources in the `srcs` list of any of the Go rules in the same package. Gazelle will automatically include .go files mentioned in `out` or `outs` attributes of rules in the same build file.

**Comment by jeb2239** [comment]
Do the go rules for bazel currently support junit style text.xml generation as I am trying to integrate the jenkins ci ? @jayconrod thanks for the suggestion if I come up with anything I will be sure to share it.

**Comment by jayconrod** [comment]
@jeb2239 Not directly, no. We basically do whatever `go test` does. You can pass arguments to tests on the command line after `--` or with `--test_arg`.

We could potentially add xml output support to the generate test main code. There is an issue to do that, #236, which has been open for a while.

**Comment by ianthehat** [comment]
I am going to close this issue as it is not tracking any work we need to do and all questions have been answered, please feel free to re-open or open new issues if you need to.
