### ISSUE TITLE
bazel run --output_groups=race does not work

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#815]
I'm trying to follow a tip from https://github.com/bazelbuild/rules_go/issues/70#issuecomment-327186121 but it does not work. I think there might be a bug somewhere:
```bzl
go_binary(
    name = "smith",
    importpath = "github.com/atlassian/smith/cmd/smith",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)
```
```console
bazel run --output_groups=race //cmd/smith
INFO: Found 1 target...
Target //cmd/smith:smith up-to-date:
  bazel-bin/cmd/smith/smith.race
INFO: Elapsed time: 0.178s, Critical Path: 0.05s
ERROR: Non-existent or non-executable /private/var/tmp/_bazel_ash2k/ea451d98a8bdaad3872b7aa995bea02c/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/cmd/smith/smith.
```
```console
ls -la /private/var/tmp/_bazel_ash2k/ea451d98a8bdaad3872b7aa995bea02c/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/cmd/smith/      
total 104104
drwxr-xr-x  5 ash2k  wheel       170 Sep  8 21:44 .
drwxr-xr-x  3 ash2k  wheel       102 Sep  8 20:47 ..
drwxr-xr-x  3 ash2k  wheel       102 Sep  8 20:47 app
-r-xr-xr-x  1 ash2k  wheel  53299656 Sep  8 21:44 smith.race
drwxr-xr-x  3 ash2k  wheel       102 Sep  8 20:47 ~race~smith~
```
So, the rule builds `smith.race` but bazel tries to run `smith.` which does not exist.

**Comment by ianthehat** [comment]
This is a limitation of Bazel.
For you to be able to run a rule (either a binary or a test) it must me marked as "executable=True" and if you do that it picks the executable file name for you based on the rule name and the target platform. This means that the "smith" rule only has one *executable* output, which will be the file used by `bazel run`.
This is why for tests we added the system where you use
`bazel test —features race`
which switches the mode of the main executable output of test rules.
We did not do the same for binaries because the patterns of use I have seen meant that people normally want to build and then run separately when doing race mode checks, so there was no real benefit with the possible cost of accidentally shipping a binary with race turned on. We can revisit that decision if people like though.

**Comment by ash2k** [comment]
My use case:
I have a system where multiple binaries (possibly built from the same repo) run against Kubernetes API. For local development (and maybe integration tests in the future) I'd like to start all/some of them to be able to play with the system interactively. I always start them with `-race` because I want to catch races. I used `go run -race` before and now I'd like to use `bazel run` to do this.

**Comment by jayconrod** [comment]
One thing to watch out for: you won't be able to `bazel run` multiple binaries concurrently. Bazel holds a lock on its output directory (where binaries run), and if you start another Bazel command, it will block until the running binaries exits.

I wonder if you would be better off building binaries with `--output_group=race`, then starting them with a script? The only drawback to that is your binaries won't automatically have access to files listed in `data` attributes, since they won't run in the Bazel output directory.

**Comment by ash2k** [comment]
Hm, ok. I guess for this use case I don't have a choice then even if this feature is implemented.
However, I still would like to be able to do `bazel run` with race detector on. I have other use cases where it would be useful. Thanks for explaining all the details, I appreciate that.

**Comment by ianthehat** [comment]
I have been thinking about it a lot, and I have mostly come to the conclusion that we should change binary to behave the same as test. The main worry is accidentally shipping a race mode binary, but you should always be shipping from a build bot, which will never accidentally have features race turned on, and the confusion of test binaries being different to normal binaries is probably worse than the minimal risk.
The only other awkward case is for tools that are built in order to build other things, you probably don't want those in race mode, so I would need to detect that a binary was in host configuration vs target configuration, even for cases where host and target were the same platform, which I am not certain is possible.
I think I will make the change if I can see a clean way to do it.
I also think we need to ask the Bazel team to give us a way of using `bazel run` where it releases the lock before it runs the program, there are just too many cases where we are going to need that kind of thing.
