### ISSUE TITLE
Gazelle not adding importpath to go_binary

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_go#819]
```bzl
go_binary(
    name = "main-race",
    gc_linkopts = ["-race"],
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

go_binary(
    name = "main",
    importpath = "github.com/atlassian/smith/examples/sleeper/main",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)
```
```bzl
gazelle(
    name = "gazelle",
    external = "vendored",
    prefix = "github.com/atlassian/smith",
)
```
When I run `bazel  run //:gazelle` it does not add `importpath` attribute to the first rule. If I remove `importpath` from the second rule it adds it back.

This is with rules_go commit bd13f2d59c804acae7ca8c18fdeb4bf0ecfa1e93 (tip at the moment)

**Comment by jayconrod** [comment]
This is working as intended.

`importpath` doesn't get added to the first rule because Gazelle will only update rules that it might have created. For example, if you have multiple `go_library` rules in a package, Gazelle will only update `go_default_library`.

Gazelle will add or update `importpath` attributes on rules it knows about, but you can stop it from changing them by adding a `# keep` comment.

```
go_library(
    name = "go_default_library",
    importpath = "github.com/example/project",  # keep
)
```

You might want to check out Bazel's [configurable attributes](https://docs.bazel.build/versions/master/be/common-definitions.html#configurable-attributes) for conditionally adding flags to a binary. You won't be able to build the same binary in multiple configurations in the same build though.
