### ISSUE TITLE
Gazelle: doesn't add a files with 2 periods in it to srcs.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_go#835]
I ported over the kubecfg tool to bazel. gazelle doesn't include a header file named "std.jsonnet.h" in a cgo package. I assume it's because of the two periods in the filename. [see](https://github.com/hsyed/kubecfg/blob/bazel/vendor/github.com/strickyak/jsonnet_cgo/BUILD.bazel).

Also another issue which prevents me from removing the `gazelle ignore` directive from the file is that gazelle copied over the `copts` flag which included `-std=c++0x` on OSX this results in a:

```
error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
```

I don't know the ins and outs of this stuff, is this worthy of a new issue ?

**Comment by jayconrod** [comment]
Thanks for reporting. The reason std.jsonnet.h isn't included by Gazelle is because there's an I/O error reading it. Gazelle reads part of each file in order to look for `// +build` comments. This file consists of one extremely long line, and `bufio.Scanner` returned an error when reading it.

I'm not going to work around the I/O error, but I admit that Gazelle shouldn't skip files like this. They should be included in the srcs list, and the compiler should be the one that deals with them. I'll send out a fix shortly.

The `-std=c++0x` error is a problem with that package. That option is not valid for pure C, and cgo code is compiled with a C compiler. On my Linux machine, I see that as a warning, but it's an error on my Mac. `go build` reports the same error.
