### ISSUE TITLE
Gazelle: warn if proto rules are present but proto_register_toolchains is not called

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/rules_go#942]
Gazelle should print a warning if it detects or generates proto rules but `proto_register_toolchains` is not called in WORKSPACE.

This will help developers avoid a mistake which is easy to make but produces an opaque message.

**Comment by ianthehat** [comment]
In the long run this will be wrong, because the purpose of that function existing is so that people that want custom toolchains register their own ones instead, and they will be deliberately not calling it (I do this in the gogo example code I wrote)
Once optional toolchains arrive (bazelbuild/bazel#3601) we can produce a better message inside the rules by checking if the toolchain was available and suggesting that function if there were no matches. Until then, having gazelle print a warning would be better than nothing though.

**Comment by jayconrod** [comment]
Agreed. Presumably, Bazel 0.8 will have a better error message, and we can remove this.
